### ISSUE TITLE
Creative Mode: Strange behavior with damage values

### ISSUE THREAD

**Issue by Kobata** [Inventory-Tweaks/inventory-tweaks#10]
Tools of the same type but different damage values do not sort correctly in creative mode.

The original report said it crashed, but I was unable to reproduce a crash -- it did like to pick a random one of the two to sort and leave the other one in its original spot however.

**Comment by shadowz15** [comment]
Basically with my inventory like this "http://i.imgur.com/5X4GDTb.png", when the sort button is clicked (middle-click or keybind), my game freezes with no crash.

**Comment by Kobata** [comment]
Yeah, it's not freezing in my dev copy -- what mod are you running for the item ID/damage info?

**Comment by shadowz15** [comment]
That is vanilla minecraft if u hit f3+h, it shows up, i only have forge 7.7.0.565 invTweaks installed right now
