### ISSUE TITLE
Game crashes on opening chat

### ISSUE THREAD

**Issue by kaitoyuuki** [Inventory-Tweaks/inventory-tweaks#103]
Up until a few minutes ago, I was having no issues playing the game with inventory tweaks and all my other mods. However, when I started up the game this time and got on multiplayer, I tried to open up the chat, causing my game to crash.
on subsequent tests, I opened up my inventory and found that the sort button was missing, and I couldn't use any of InvTweaks' other features.
This is the error report I got: http://pastebin.com/DJfukeTt

**Comment by Kobata** [comment]
Duplicate #93
