### ISSUE TITLE
crashes when launched with WR-CBE

### ISSUE THREAD

**Issue by restjack** [Inventory-Tweaks/inventory-tweaks#107]
WR-CBE 1.4.0.5
Wireless Redstone Chicken Bones Edition (WR-CBE)
http://www.minecraftforum.net/topic/909223-162-smp-chickenbones-mods/

it crashes whenever you press a key any key

**Comment by Kobata** [comment]
Needs more detail, including the specific Invtentory Tweaks version and the crash report.
