### ISSUE TITLE
Incompatibility with modified inventory GUI

### ISSUE THREAD

**Issue by qchronod** [Inventory-Tweaks/inventory-tweaks#108]
Currently playing on a custom private mod pack with a bunch of mods and both Tinkers Contruct and Galacticraft modify the inventory gui. TC isn't much of an issue since it uses a separate gui screen, but Galacticraft adds 5 new slots to the inventory screen.  

Apparently this is resulting in all of the inventory slots being moved 5 places higher than you would expect with D5-D9 ending up in the new GC slots. (See http://imgur.com/70DCQcQ for better illustration.) It appears to me that InvTweaks is counting backwards from the last inventory slot available to calculate the value of each position in the grid. Is it possible to add a check to make see whether the inventory slot values are as expected, or modify it to calculate the locations based on the beginning of the list?

Almost forgot, this is under MC 1.5.2 w/ Forge 738 and InvTweaks 1.54

**Comment by Kobata** [comment]
It is not possible to determine exactly what a given slot is in general, the default counts from the end to match vanilla behavior. All vanilla GUIs (Except for the extra 'trash' slot in creative inventory tab, which is specially handled) put the player inventory at the end of the slots.

The compatibility API supports placing sections over any set of slots, so mods that do strange things should use that to provide the correct mapping.

**Comment by micdoodle8** [comment]
This is fixed in the 1.6.2 version of Galacticraft, btw.
