### ISSUE TITLE
InvTweaks also orders the elements of hotbar

### ISSUE THREAD

**Issue by WileTheCoyot** [Inventory-Tweaks/inventory-tweaks#109]
sometimes (not always) when I order my inventory invtweaks also orders the hotbar (basically removes the item from hotbar and puts them in the inventory). I have version 1.54b (the config file is the default) and use the openjdk 1.7 with linux. PS: sorry for my bad english

**Comment by WileTheCoyot** [comment]
I have made some tests and i founds that the failure only occur when trying to sort items in an modded interface like ic2 machines. If i sort in a regular chest everything works fine

**Comment by Kobata** [comment]
IC2 changed some things around a while ago, which is why 'guessing' the layout of the inventory in random thing was removed in 1.55 final. See issue #55
