### ISSUE TITLE
Creative Mode: InvTweaks shortcuts do not work.

### ISSUE THREAD

**Issue by Kobata** [Inventory-Tweaks/inventory-tweaks#11]
Attempting to use any InvTweaks shortcut in creative mode results in nothing happening.

**Comment by shadowz15** [comment]
Ahh so that means the drop keybind for dropping when not in the inventory is persisting inside the gui and it isn't InvTweaks, maybe its something with 1.5 or forge?
Edit: its actually a feature in 1.5, i just tested it on an unmodded client

**Comment by Kobata** [comment]
Updated issue to reflect the fact it seems like creative mode is suppressing ALL of invtweaks-specific shortcut handling, instead of just the drop shortcut.

**Comment by Kobata** [comment]
Oh, this seems to be intentional: https://github.com/Kobata/inventory-tweaks/blob/develop/src/minecraft/invtweaks/InvTweaks.java#L744

I'll leave this be for the moment, but it would be nice to get shortcuts to work eventually.

**Comment by mkalam-alami** [comment]
Yeah at the time it was a mess to figure things out, but now that the mod uses MCP it shouldn't be too complicated to make shortcuts work on creative mode too.

**Comment by Kobata** [comment]
Not seeing any major bugs in testing with that check disabled -- alt, shift, control, space, and various combinations appeared to work correctly.
