### ISSUE TITLE
Sort does not work on certin containers provided by other mod

### ISSUE THREAD

**Issue by nohappiness** [Inventory-Tweaks/inventory-tweaks#111]
Like multi-page chest , it was worked fine when 1.5.x and before.
http://www.minecraftforum.net/topic/506109-162-cubex2s-mods-everything-updated/#MultiPageChest

**Comment by nohappiness** [comment]
Sorry about this , just found the InvTweakCompatibility.xml part, I'll have a try.
Even though I hope there's more capability with other mods.

**Comment by Kobata** [comment]
Support for mod things is the responsibility of the mod that added those things.

**Comment by nohappiness** [comment]
Just for curiosity, It worked when in 1.5.x or 1.4.x, how come it does not work now ?

**Comment by Kobata** [comment]
I don't remember off the top of my head if this was ever an explicitly supported mod, but older versions did some guesswork that had major issues with some popular mods after they decided to change things to not match the order vanilla puts slots in.
