### ISSUE TITLE
Help! I don't know what I've done to my inventory!

### ISSUE THREAD

**Issue by tyie** [Inventory-Tweaks/inventory-tweaks#114]
So, I am playing minecraft on a server that my brother owns, using the FTB Ultimate mod pack and usually when I go to view my inventory I see all the items on the right and mod options in bottom left. But I either pressed something by mistake or it just happened for no reason and now it looks like this and I can't get it back to looking how it originally did :( help please! (ps. i have tried reloading minecraft many times)

http://puu.sh/4M8IF.png <---what it looks like at the mo

**Comment by Kobata** [comment]
You turned on NEI's search thing, nothing to do with this.
