### ISSUE TITLE
Any sorting causes crashes

### ISSUE THREAD

**Issue by Ahall0943** [Inventory-Tweaks/inventory-tweaks#116]
I was using InventoryTweaks-MC1.6.2-1.56-b77.
Here's the entire crash report:

---- Minecraft Crash Report ----
// I blame Dinnerbone.

Time: 11/23/13 1:52 PM
Description: Unexpected error

java.lang.IllegalAccessError: tried to access class net.minecraft.client.gui.inventory.SlotCreativeInventory from class invtweaks.InvTweaksObfuscation
    at invtweaks.InvTweaksObfuscation.getSlotNumber(InvTweaksObfuscation.java:176)
    at invtweaks.InvTweaksContainerManager.indexToSlot(InvTweaksContainerManager.java:447)
    at invtweaks.InvTweaksContainerManager.getItemStack(InvTweaksContainerManager.java:408)
    at invtweaks.InvTweaksContainerSectionManager.getItemStack(InvTweaksContainerSectionManager.java:105)
    at invtweaks.InvTweaksHandlerSorting.<init>(InvTweaksHandlerSorting.java:98)
    at invtweaks.InvTweaks.handleSorting(InvTweaks.java:541)
    at invtweaks.InvTweaks.onSortingKeyPressed(InvTweaks.java:182)
    at invtweaks.InvTweaks.onTick(InvTweaks.java:441)
    at invtweaks.InvTweaks.onTickInGUI(InvTweaks.java:133)
    at invtweaks.forge.ForgeClientTick.tickEnd(ForgeClientTick.java:43)
    at cpw.mods.fml.common.SingleIntervalHandler.tickEnd(SingleIntervalHandler.java:34)
    at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:140)
    at cpw.mods.fml.common.FMLCommonHandler.onRenderTickEnd(FMLCommonHandler.java:376)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:948)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:838)
    at net.minecraft.client.main.Main.main(SourceFile:101)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:27)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at invtweaks.InvTweaksObfuscation.getSlotNumber(InvTweaksObfuscation.java:176)
    at invtweaks.InvTweaksContainerManager.indexToSlot(InvTweaksContainerManager.java:447)
    at invtweaks.InvTweaksContainerManager.getItemStack(InvTweaksContainerManager.java:408)
    at invtweaks.InvTweaksContainerSectionManager.getItemStack(InvTweaksContainerSectionManager.java:105)
    at invtweaks.InvTweaksHandlerSorting.<init>(InvTweaksHandlerSorting.java:98)
    at invtweaks.InvTweaks.handleSorting(InvTweaks.java:541)
    at invtweaks.InvTweaks.onSortingKeyPressed(InvTweaks.java:182)
    at invtweaks.InvTweaks.onTick(InvTweaks.java:441)
    at invtweaks.InvTweaks.onTickInGUI(InvTweaks.java:133)
    at invtweaks.forge.ForgeClientTick.tickEnd(ForgeClientTick.java:43)
    at cpw.mods.fml.common.SingleIntervalHandler.tickEnd(SingleIntervalHandler.java:34)
    at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:140)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityClientPlayerMP['Ahall9096'/601, l='MpServer', x=260.71, y=65.62, z=255.56]]
    Chunk stats: MultiplayerChunkCache: 441
    Level seed: 0
    Level generator: ID 04 - BIOMESOP, ver 0. Features enabled: false
    Level generator options: 
    Level spawn location: World: (256,64,252), Chunk: (at 0,4,12 in 16,15; contains blocks 256,0,240 to 271,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 2819 game time, 2819 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: adventure (ID 2). Hardcore: false. Cheats: false
    Forced entities: 138 total; [EntityPig['Pig'/275, l='MpServer', x=250.69, y=72.00, z=300.47], EntityPig['Pig'/274, l='MpServer', x=253.84, y=72.00, z=295.22], EntityPig['Pig'/273, l='MpServer', x=243.72, y=70.00, z=276.78], EntityEnderman['Enderman'/272, l='MpServer', x=243.84, y=35.00, z=282.31], EntityMinecartChest['entity.MinecartChest.name'/279, l='MpServer', x=245.50, y=27.34, z=331.50], EntityItem['item.item.seeds'/278, l='MpServer', x=250.22, y=69.13, z=305.97], EntityPig['Pig'/277, l='MpServer', x=255.09, y=72.00, z=298.13], EntityPig['Pig'/276, l='MpServer', x=246.16, y=72.00, z=291.44], EntitySkeleton['Skeleton'/283, l='MpServer', x=247.84, y=28.00, z=329.63], EntitySkeleton['Skeleton'/282, l='MpServer', x=247.88, y=31.00, z=327.91], EntityMinecartChest['entity.MinecartChest.name'/280, l='MpServer', x=246.50, y=31.34, z=327.50], EntityCreeper['Creeper'/285, l='MpServer', x=246.50, y=31.00, z=328.50], EntityCow['Cow'/262, l='MpServer', x=248.50, y=63.00, z=185.31], EntityItem['item.tile.bop.flowers2.minersdelight'/263, l='MpServer', x=249.16, y=17.13, z=192.88], EntityCow['Cow'/260, l='MpServer', x=246.81, y=62.55, z=185.28], EntityCow['Cow'/261, l='MpServer', x=247.50, y=62.35, z=190.91], EntityPig['Pig'/266, l='MpServer', x=251.36, y=66.00, z=240.47], EntityBrainyZombie['Angry Zombie'/267, l='MpServer', x=254.50, y=27.00, z=264.50], EntityItem['item.tile.gravel'/264, l='MpServer', x=254.56, y=39.13, z=254.78], EntityItem['item.item.porkchopRaw'/265, l='MpServer', x=243.31, y=65.13, z=249.34], EntityZombie['Zombie'/270, l='MpServer', x=245.88, y=34.00, z=280.50], EntitySkeleton['Skeleton'/271, l='MpServer', x=242.72, y=35.00, z=282.88], EntitySkeleton['Skeleton'/268, l='MpServer', x=245.50, y=34.00, z=282.50], EntityZombie['Zombie'/269, l='MpServer', x=249.50, y=34.00, z=283.50], EntityItem['item.tile.bop.stoneFormations.stalactite'/1131, l='MpServer', x=222.13, y=50.36, z=222.32], EntityCreeper['Creeper'/343, l='MpServer', x=261.53, y=27.00, z=304.94], EntityZombie['Zombie'/342, l='MpServer', x=265.06, y=27.00, z=311.38], EntityItem['item.tile.bop.stoneFormations.stalagmite'/341, l='MpServer', x=268.28, y=29.13, z=316.88], EntityCreeper['Creeper'/340, l='MpServer', x=266.13, y=25.00, z=305.75], EntityBat['Bat'/339, l='MpServer', x=255.38, y=20.20, z=289.50], EntityItem['item.tile.bop.stoneFormations.stalactite'/338, l='MpServer', x=265.13, y=19.13, z=274.88], EntityPig['Pig'/337, l='MpServer', x=264.50, y=71.00, z=264.69], EntityCreeper['Creeper'/336, l='MpServer', x=270.26, y=40.57, z=253.32], EntityBat['Bat'/85, l='MpServer', x=201.63, y=21.67, z=210.16], EntityBat['Bat'/86, l='MpServer', x=190.00, y=19.60, z=218.22], EntitySkeleton['Skeleton'/93, l='MpServer', x=190.50, y=36.00, z=263.50], EntityPig['Pig'/95, l='MpServer', x=187.16, y=66.00, z=278.09], EntityZombie['Zombie'/94, l='MpServer', x=195.13, y=36.00, z=263.66], EntityCreeper['Creeper'/91, l='MpServer', x=184.25, y=29.00, z=233.88], EntityCreeper['Creeper'/90, l='MpServer', x=185.72, y=33.00, z=254.72], EntityCreeper['Creeper'/375, l='MpServer', x=290.50, y=21.00, z=203.50], EntityPig['Pig'/98, l='MpServer', x=186.50, y=65.00, z=275.50], EntityPig['Pig'/96, l='MpServer', x=188.50, y=66.00, z=277.53], EntityPig['Pig'/97, l='MpServer', x=188.50, y=66.00, z=276.47], EntityZombie['Zombie'/110, l='MpServer', x=196.50, y=23.00, z=299.50], EntityEnderman['Enderman'/381, l='MpServer', x=293.28, y=20.00, z=254.34], EntityItem['item.tile.gravel'/111, l='MpServer', x=198.28, y=17.13, z=300.34], EntityEnderman['Enderman'/380, l='MpServer', x=293.03, y=20.00, z=253.00], EntityItem['item.item.seeds'/108, l='MpServer', x=197.91, y=68.13, z=249.16], EntityItem['item.tile.bop.stoneFormations.stalactite'/383, l='MpServer', x=289.41, y=40.13, z=249.16], EntityItem['item.tile.bop.stoneFormations.stalactite'/382, l='MpServer', x=290.53, y=40.13, z=248.84], EntityBat['Bat'/109, l='MpServer', x=205.34, y=15.45, z=304.69], EntityItem['item.tile.bop.stoneFormations.stalagmite'/106, l='MpServer', x=203.84, y=19.13, z=206.19], EntityZombie['Zombie'/377, l='MpServer', x=298.50, y=8.00, z=216.50], EntityItem['item.tile.bop.stoneFormations.stalactite'/107, l='MpServer', x=207.88, y=19.13, z=198.81], EntityZombie['Zombie'/376, l='MpServer', x=293.50, y=8.00, z=216.50], EntityItem['item.tile.bop.stoneFormations.stalagmite'/104, l='MpServer', x=207.34, y=19.13, z=198.13], EntityCreeper['Creeper'/379, l='MpServer', x=300.44, y=23.00, z=245.97], EntityItem['item.tile.bop.stoneFormations.stalagmite'/105, l='MpServer', x=204.81, y=19.13, z=195.81], EntityItem['item.tile.bop.stoneFormations.stalagmite'/378, l='MpServer', x=301.88, y=36.13, z=222.31], EntityItem['item.tile.bop.stoneFormations.stalactite'/359, l='MpServer', x=280.28, y=16.13, z=232.19], EntityCreeper['Creeper'/114, l='MpServer', x=207.50, y=31.00, z=326.50], EntityItem['item.tile.bop.stoneFormations.stalagmite'/112, l='MpServer', x=204.13, y=11.13, z=307.47], EntitySkeleton['Skeleton'/364, l='MpServer', x=277.50, y=19.00, z=271.50], EntityItem['item.tile.bop.stoneFormations.stalactite'/365, l='MpServer', x=286.22, y=37.13, z=303.97], EntityItem['item.item.seeds'/366, l='MpServer', x=277.34, y=74.13, z=296.44], EntityClientPlayerMP['Ahall9096'/601, l='MpServer', x=260.71, y=65.62, z=255.56], EntityItem['item.tile.bop.stoneFormations.stalactite'/367, l='MpServer', x=284.88, y=37.13, z=305.38], EntityItem['item.tile.bop.stoneFormations.stalactite'/360, l='MpServer', x=284.97, y=17.13, z=245.63], EntityItem['item.tile.bop.stoneFormations.stalactite'/361, l='MpServer', x=286.78, y=40.13, z=252.31], EntityItem['item.tile.bop.stoneFormations.stalactite'/362, l='MpServer', x=287.69, y=40.13, z=250.16], EntityItem['item.tile.bop.stoneFormations.stalactite'/363, l='MpServer', x=286.59, y=40.13, z=251.25], EntityItem['item.item.seeds'/410, l='MpServer', x=313.97, y=72.13, z=266.53], EntityZombie['Zombie'/411, l='MpServer', x=312.03, y=34.00, z=303.50], EntityBat['Bat'/408, l='MpServer', x=299.41, y=21.02, z=277.06], EntityBat['Bat'/139, l='MpServer', x=208.63, y=24.57, z=204.59], EntityItem['item.item.seeds'/409, l='MpServer', x=313.06, y=71.13, z=268.91], EntityItem['item.tile.bop.stoneFormations.stalactite'/138, l='MpServer', x=210.66, y=21.13, z=207.91], EntityBat['Bat'/141, l='MpServer', x=206.50, y=51.70, z=250.44], EntityItem['item.tile.bop.flowers2.minersdelight'/140, l='MpServer', x=213.88, y=45.13, z=221.25], EntityBat['Bat'/412, l='MpServer', x=305.03, y=36.67, z=306.53], EntityItem['item.tile.rail'/143, l='MpServer', x=211.81, y=15.13, z=293.16], EntityBat['Bat'/142, l='MpServer', x=209.78, y=52.57, z=242.22], EntityItem['item.tile.bop.stoneFormations.stalactite'/406, l='MpServer', x=317.94, y=59.13, z=212.31], EntityBat['Bat'/407, l='MpServer', x=299.38, y=44.39, z=264.97], EntityItem['item.tile.bop.stoneFormations.stalagmite'/152, l='MpServer', x=209.44, y=15.13, z=291.19], EntityItem['item.tile.rail'/153, l='MpServer', x=214.31, y=15.13, z=304.88], EntitySkeleton['Skeleton'/393, l='MpServer', x=300.09, y=47.00, z=323.59], EntityItem['item.tile.rail'/154, l='MpServer', x=208.63, y=13.13, z=312.03], EntitySkeleton['Skeleton'/392, l='MpServer', x=297.00, y=47.00, z=329.53], EntityItem['item.tile.rail'/155, l='MpServer', x=210.34, y=13.13, z=309.81], EntityItem['item.tile.rail'/156, l='MpServer', x=209.19, y=11.13, z=307.44], EntityBat['Bat'/157, l='MpServer', x=208.50, y=15.10, z=314.75], EntityItem['item.tile.torch'/158, l='MpServer', x=209.59, y=27.13, z=310.88], EntityItem['item.tile.rail'/159, l='MpServer', x=214.13, y=19.13, z=319.13], EntitySkeleton['Skeleton'/387, l='MpServer', x=290.72, y=32.00, z=295.16], EntityItem['item.tile.rail'/144, l='MpServer', x=213.16, y=15.13, z=293.19], EntityCreeper['Creeper'/386, l='MpServer', x=297.50, y=21.00, z=277.50], EntityItem['item.tile.rail'/145, l='MpServer', x=215.19, y=15.13, z=293.19], EntityEnderman['Enderman'/385, l='MpServer', x=292.03, y=21.00, z=257.59], EntityItem['item.tile.bop.stoneFormations.stalagmite'/146, l='MpServer', x=216.19, y=15.13, z=293.16], EntityItem['item.tile.bop.stoneFormations.stalactite'/384, l='MpServer', x=291.16, y=40.13, z=249.72], EntityItem['item.tile.rail'/147, l='MpServer', x=212.75, y=15.13, z=295.28], EntitySkeleton['Skeleton'/391, l='MpServer', x=286.50, y=47.00, z=318.09], EntityItem['item.tile.bop.stoneFormations.stalagmite'/148, l='MpServer', x=211.47, y=15.13, z=295.34], EntitySkeleton['Skeleton'/390, l='MpServer', x=299.69, y=46.00, z=322.75], EntityItem['item.tile.rail'/149, l='MpServer', x=211.72, y=15.13, z=303.19], EntityMinecartChest['entity.MinecartChest.name'/150, l='MpServer', x=217.50, y=13.50, z=299.50], EntityItem['item.tile.bop.flowers2.minersdelight'/389, l='MpServer', x=303.13, y=36.13, z=307.88], EntityBat['Bat'/388, l='MpServer', x=284.75, y=26.55, z=291.25], EntityItem['item.tile.rail'/151, l='MpServer', x=210.81, y=15.13, z=294.34], EntitySkeleton['Skeleton'/170, l='MpServer', x=215.50, y=18.00, z=335.34], EntitySkeleton['Skeleton'/443, l='MpServer', x=338.91, y=31.00, z=181.56], EntityPig['Pig'/163, l='MpServer', x=209.50, y=70.00, z=314.50], EntityPig['Pig'/162, l='MpServer', x=210.50, y=77.00, z=314.50], EntityItem['item.tile.blockCustomPlant.0'/433, l='MpServer', x=321.34, y=70.13, z=242.13], EntityPig['Pig'/161, l='MpServer', x=210.50, y=77.00, z=314.50], EntityPig['Pig'/160, l='MpServer', x=211.41, y=69.00, z=307.13], EntityItem['item.tile.bop.stoneFormations.stalactite'/668, l='MpServer', x=292.50, y=32.13, z=229.63], EntitySquid['Squid'/207, l='MpServer', x=232.94, y=59.31, z=204.06], EntitySquid['Squid'/206, l='MpServer', x=224.25, y=59.78, z=205.72], EntityPig['Pig'/220, l='MpServer', x=231.97, y=70.00, z=318.69], EntityPig['Pig'/221, l='MpServer', x=236.78, y=69.00, z=319.78], EntityPig['Pig'/222, l='MpServer', x=228.34, y=70.00, z=317.47], EntityPig['Pig'/223, l='MpServer', x=233.50, y=70.00, z=318.88], EntityPig['Pig'/216, l='MpServer', x=226.53, y=72.00, z=263.31], EntityPig['Pig'/217, l='MpServer', x=228.34, y=67.00, z=262.75], EntitySpider['Spider'/218, l='MpServer', x=228.56, y=15.00, z=292.38], EntityItem['item.tile.bop.stoneFormations.stalagmite'/219, l='MpServer', x=229.13, y=30.13, z=293.13], EntitySquid['Squid'/212, l='MpServer', x=239.50, y=61.22, z=206.16], EntitySquid['Squid'/213, l='MpServer', x=226.66, y=60.00, z=212.50], EntityPig['Pig'/214, l='MpServer', x=227.13, y=67.00, z=244.97], EntityPig['Pig'/215, l='MpServer', x=237.31, y=69.00, z=257.50], EntitySquid['Squid'/208, l='MpServer', x=234.31, y=61.34, z=212.91], EntitySquid['Squid'/209, l='MpServer', x=241.50, y=62.00, z=211.97], EntitySquid['Squid'/210, l='MpServer', x=239.50, y=61.00, z=207.38], EntitySquid['Squid'/211, l='MpServer', x=234.66, y=62.38, z=211.38], EntityZombie['Zombie'/231, l='MpServer', x=225.50, y=25.00, z=335.03]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:440)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2312)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:863)
    at net.minecraft.client.main.Main.main(SourceFile:101)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:27)

-- System Details --
Details:
    Minecraft Version: 1.6.4
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.7.0_15, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 221247608 bytes (210 MB) / 639172608 bytes (609 MB) up to 954466304 bytes (910 MB)
    JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G
    AABB Pool Size: 17042 (954352 bytes; 0 MB) allocated, 1687 (94472 bytes; 0 MB) used
    Suspicious classes: FML and Forge are installed
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 60
    FML: MCP v8.11 FML v6.99.19.964 Minecraft Forge 9.11.1.964 40 mods loaded, 40 mods active
    mcp{8.09} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    FML{6.99.19.964} [Forge Mod Loader](forge-1.6.4-9.11.1.964.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Forge{9.11.1.964} [Minecraft Forge](forge-1.6.4-9.11.1.964.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    AppliedEnergistics-Core{rv14.finale} [AppliedEnergistics Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CodeChickenCore{0.9.0.6} [CodeChicken Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    NotEnoughItems{1.6.1.5} [Not Enough Items](NotEnoughItems 1.6.1.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    DamageIndicatorsMod{2.9.1.5} [Damage Indicators](1.6.4 DamageIndicatorsv2.9.1.5.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    AppliedEnergistics{rv14.finale} [Applied Energistics](appeng-rv14-finale-mc16x.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BiblioCraft{1.5.3} [BiblioCraft](BiblioCraft[v1.5.3].zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BiomesOPlenty{1.1.3} [Biomes O' Plenty](BiomesOPlenty-universal-1.6.4-1.1.3.305.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BiblioWoodsBoP{1.3} [BiblioWoods Biomes O'Plenty Edition](BiblioWoods[BiomesOPlenty][v1.3].zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    IC2{2.0.306-experimental} [IndustrialCraft 2](industrialcraft-2_2.0.306-experimental.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Forestry{2.3.0.7} [Forestry for Minecraft](forestry-A-2.3.0.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BiblioWoodsForestry{1.3} [BiblioWoods Forestry Edition](BiblioWoods[Forestry][v1.3].zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BinnieCore{1.8-dev2} [Binnie Core](binnie-mods-1.8-dev2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ExtraBees{1.8-dev2} [Extra Bees](binnie-mods-1.8-dev2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ExtraTrees{1.8-dev2} [Extra Trees](binnie-mods-1.8-dev2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Core{4.1.2} [BuildCraft](buildcraft-A-1.6.2-4.1.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Builders{4.1.2} [BC Builders](buildcraft-A-1.6.2-4.1.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Energy{4.1.2} [BC Energy](buildcraft-A-1.6.2-4.1.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Factory{4.1.2} [BC Factory](buildcraft-A-1.6.2-4.1.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Transport{4.1.2} [BC Transport](buildcraft-A-1.6.2-4.1.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Silicon{4.1.2} [BC Silicon](buildcraft-A-1.6.2-4.1.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CompactSolars{4.4.19.224} [Compact Solar Arrays](compactsolars-universal-1.6.4-4.4.19.224.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ForgeMultipart{1.0.0.212} [Forge Multipart](ForgeMultipart-universal-1.6.4-1.0.0.212.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    McMultipart{1.0.0.212} [Minecraft Multipart Plugin](ForgeMultipart-universal-1.6.4-1.0.0.212.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    inventorytweaks{1.56} [Inventory Tweaks](InventoryTweaks-MC1.6.2-1.56-b77.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    IronChest{5.4.1.649} [Iron Chest](ironchest-universal-1.6.4-5.4.1.649.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Thaumcraft{4.0.5} [Thaumcraft](Thaumcraft4.0.5.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ThaumicTinkerer{2.0} [Thaumic Tinkerer](ThaumicTinkerer 2.0-26.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MagicBees{2.1.7} [Magic Bees](magicbees-2.1.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    NEIAddons{1.9.3.r47} [NEI Addons](neiaddons-1.6.2-1.9.3.r47.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    NEIAddons|AE{1.9.3.r47} [NEI Addons: Applied Energistics](neiaddons-1.6.2-1.9.3.r47.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    NEIAddons|CraftingTables{1.9.3.r47} [NEI Addons: Crafting Tables](neiaddons-1.6.2-1.9.3.r47.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    NEIAddons|ExtraBees{1.9.3.r47} [NEI Addons: Extra Bees](neiaddons-1.6.2-1.9.3.r47.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    NEIAddons|Forestry{1.9.3.r47} [NEI Addons: Forestry](neiaddons-1.6.2-1.9.3.r47.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    NEIAddons|MiscPeripherals{1.9.3.r47} [NEI Addons: Misc Peripherals](neiaddons-1.6.2-1.9.3.r47.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    NEIPlugins{1.1.0.5} [NEI Plugins](NEIPlugins-1.1.0.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Railcraft{8.2.0.0} [Railcraft](Railcraft_1.6.2-8.2.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ForgeMicroblock{1.0.0.212} [Forge Microblocks](ForgeMultipart-universal-1.6.4-1.0.0.212.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Launched Version: 1.6.4-Forge9.11.1.964
    LWJGL: 2.9.0
    OpenGL: AMD Radeon HD 6320 Graphics GL version 4.1.10834 Compatibility Profile Context, ATI Technologies Inc.
    Is Modded: Definitely; Client brand changed to 'fml,forge'
    Type: Client (map_client.txt)
    Resource Pack: Default
    Current Language: English (US)
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 10481 (586936 bytes; 0 MB) allocated, 1198 (67088 bytes; 0 MB) used

**Comment by Ahall0943** [comment]
The only things I did differently when creating the world was activating cheats when make the world, adding the bonus chest, and make it Biomes o plenty world generation.

**Comment by Vlassie** [comment]
I can confirm this crash, it has happened to me as well

**Comment by Kobata** [comment]
Use older versions of forge for now, the 960-ish versions break many, many things because they're more of tests for some of the 1.7 changes.

**Comment by Vlassie** [comment]
Well, but my other mods like TE of TC need 960+ :(

**Comment by AEnterprise** [comment]
they don't realy need that, you could go back to older versions temporaly

**Comment by Vlassie** [comment]
at least one mod in my mod list said it needed 960+ when I loaded up minecraft, so I updated it

**Comment by Kobata** [comment]
Anyone requiring anything newer than 953 is doing things wrong and should be annoyed until they set their minimum version lower. All the newer versions of Forge break **many** mods and really shouldn't be used by anyone who isn't testing the build system changes.

**Comment by Vlassie** [comment]
Why should they be annoyed? They are doing things the right way, aren't they? Updating to newer versions so updating to 1.7 will be easier isn't something bad in my opinion.

**Comment by AEnterprise** [comment]
you can update to forge but it is best to wait to update until all your mods have made a new/tested version of the mod with that version of forge, sometimes something changes and mods have to be updated

**Comment by Kobata** [comment]
I meant the _devs_ of those mods should be annoyed. In any case, the Forge developers have just removed the installer downloads for the newer versions of Forge because they are not intended to be installed by users yet.

**Comment by AEnterprise** [comment]
they should make a seperate development chanel, so they have stable versions for everybody to use, and dev versions for testers and mod owners to start updating

**Comment by Kobata** [comment]
If you mean Forge, they do, and that has always pointed at an older version (it's currently 953, the last one before they started testing their new stuff) people just don't seem to pay attention to it much.
