### ISSUE TITLE
 crashes when i try to open my inventory.

### ISSUE THREAD

**Issue by sofien1** [Inventory-Tweaks/inventory-tweaks#117]
i have a problem with inventory tweaks! it crashes when i try to open my inventory.
[spoiler]---- Minecraft Crash Report ----

// You're mean.

Time: 11/25/13 10:23 AM
Description: Unexpected error

java.lang.IllegalAccessError: tried to access class net.minecraft.client.gui.inventory.SlotCreativeInventory from class invtweaks.InvTweaksObfuscation
    at invtweaks.InvTweaksObfuscation.getSlotNumber(InvTweaksObfuscation.java:176)
    at invtweaks.InvTweaksContainerManager.indexToSlot(InvTweaksContainerManager.java:447)
    at invtweaks.InvTweaksContainerManager.getItemStack(InvTweaksContainerManager.java:408)
    at invtweaks.InvTweaksContainerSectionManager.getItemStack(InvTweaksContainerSectionManager.java:105)
    at invtweaks.InvTweaksHandlerAutoRefill.autoRefillSlot(InvTweaksHandlerAutoRefill.java:93)
    at invtweaks.InvTweaks.handleAutoRefill(InvTweaks.java:579)
    at invtweaks.InvTweaks.onTickInGame(InvTweaks.java:117)
    at invtweaks.forge.ForgeClientTick.tickEnd(ForgeClientTick.java:45)
    at cpw.mods.fml.common.SingleIntervalHandler.tickEnd(SingleIntervalHandler.java:34)
    at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:140)
    at cpw.mods.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:366)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1970)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:910)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:838)
    at net.minecraft.client.main.Main.main(SourceFile:101)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:27)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at invtweaks.InvTweaksObfuscation.getSlotNumber(InvTweaksObfuscation.java:176)
    at invtweaks.InvTweaksContainerManager.indexToSlot(InvTweaksContainerManager.java:447)
    at invtweaks.InvTweaksContainerManager.getItemStack(InvTweaksContainerManager.java:408)
    at invtweaks.InvTweaksContainerSectionManager.getItemStack(InvTweaksContainerSectionManager.java:105)
    at invtweaks.InvTweaksHandlerAutoRefill.autoRefillSlot(InvTweaksHandlerAutoRefill.java:93)
    at invtweaks.InvTweaks.handleAutoRefill(InvTweaks.java:579)
    at invtweaks.InvTweaks.onTickInGame(InvTweaks.java:117)
    at invtweaks.forge.ForgeClientTick.tickEnd(ForgeClientTick.java:45)
    at cpw.mods.fml.common.SingleIntervalHandler.tickEnd(SingleIntervalHandler.java:34)
    at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:140)
    at cpw.mods.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:366)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityClientPlayerMP['neaiazuob'/4852, l='MpServer', x=-171.27, y=72.62, z=-0.52]]
    Chunk stats: MultiplayerChunkCache: 441
    Level seed: 0
    Level generator: ID 04 - BIOMESOP, ver 0. Features enabled: false
    Level generator options:
    Level spawn location: World: (-153,64,12), Chunk: (at 7,4,12 in -10,0; contains blocks -160,0,0 to -145,255,15), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
    Level time: 1140 game time, 1140 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
    Forced entities: 92 total; [EntityBat['Bat'/13140, l='MpServer', x=-214.56, y=52.78, z=69.65], EntityBat['Bat'/13141, l='MpServer', x=-220.35, y=56.00, z=59.69], EntityItem['item.tile.bop.stoneFormations.stalactite'/13087, l='MpServer', x=-214.00, y=16.13, z=24.53], EntityItem['item.tile.bop.mud.quicksand'/13083, l='MpServer', x=-171.75, y=71.05, z=1.75], EntityBat['Bat'/13117, l='MpServer', x=-235.25, y=22.00, z=-0.72], EntityItem['item.tile.bop.stoneFormations.stalagmite'/13089, l='MpServer', x=-222.13, y=13.13, z=-15.91], EntityFallingSand['Falling Block'/10884, l='MpServer', x=-151.50, y=21.49, z=138.50], EntityItem['item.tile.bop.stoneFormations.stalactite'/11229, l='MpServer', x=-222.69, y=32.13, z=7.38], EntityItem['item.tile.bop.stoneFormations.stalagmite'/12806, l='MpServer', x=-163.13, y=16.13, z=50.13], EntityItem['item.tile.bop.stoneFormations.stalagmite'/12813, l='MpServer', x=-164.97, y=16.13, z=57.19], EntityItem['item.tile.bop.stoneFormations.stalagmite'/12810, l='MpServer', x=-161.13, y=16.13, z=53.88], EntityItem['item.tile.bop.stoneFormations.stalagmite'/12808, l='MpServer', x=-160.28, y=17.13, z=47.41], EntityFallingSand['Falling Block'/11164, l='MpServer', x=-31.50, y=19.49, z=133.50], EntityFallingSand['Falling Block'/11163, l='MpServer', x=-31.50, y=19.49, z=132.50], EntityItem['item.tile.bop.stoneFormations.stalactite'/12998, l='MpServer', x=-197.63, y=33.13, z=-19.78], EntityItem['item.tile.bop.stoneFormations.stalagmite'/13017, l='MpServer', x=-136.16, y=41.13, z=-3.22], EntityBat['Bat'/12988, l='MpServer', x=-162.49, y=12.01, z=-42.45], EntityBat['Bat'/12986, l='MpServer', x=-155.23, y=11.78, z=-45.98], EntitySquid['Squid'/4916, l='MpServer', x=-112.72, y=52.34, z=62.69], EntityFallingSand['Falling Block'/7148, l='MpServer', x=-151.50, y=21.49, z=138.50], EntitySquid['Squid'/4973, l='MpServer', x=-197.16, y=56.30, z=15.47], EntitySquid['Squid'/4974, l='MpServer', x=-193.56, y=53.23, z=19.63], EntityItem['item.tile.bop.stoneFormations.stalactite'/12796, l='MpServer', x=-106.81, y=10.13, z=-57.41], EntityClientPlayerMP['neaiazuob'/4852, l='MpServer', x=-171.27, y=72.62, z=-0.52], EntityBat['Bat'/5058, l='MpServer', x=-125.53, y=31.90, z=-5.44], EntityBat['Bat'/5062, l='MpServer', x=-136.06, y=32.10, z=13.75], EntityBat['Bat'/5061, l='MpServer', x=-139.84, y=27.00, z=6.75], EntityBat['Bat'/5108, l='MpServer', x=-166.56, y=37.47, z=-20.48], EntityItem['item.tile.bop.stoneFormations.stalactite'/6837, l='MpServer', x=-182.41, y=41.13, z=5.88], EntityItem['item.tile.bop.flowers2.minersdelight'/12325, l='MpServer', x=-142.84, y=30.13, z=54.66], EntitySheep['Sheep'/4698, l='MpServer', x=-237.50, y=65.00, z=16.50], EntityItem['item.tile.bop.stoneFormations.stalagmite'/12348, l='MpServer', x=-148.88, y=26.13, z=41.13], EntityItem['item.item.seeds'/4707, l='MpServer', x=-221.38, y=61.78, z=-9.88], EntityItem['item.item.seeds'/4709, l='MpServer', x=-220.13, y=62.78, z=-6.47], EntityItem['item.tile.bop.stoneFormations.stalagmite'/4714, l='MpServer', x=-200.13, y=39.13, z=4.13], EntityItem['item.tile.bop.stoneFormations.stalagmite'/4713, l='MpServer', x=-200.69, y=40.13, z=2.13], EntityItem['item.tile.bop.flowers2.minersdelight'/4718, l='MpServer', x=-204.81, y=23.13, z=11.19], EntityItem['item.tile.bop.flowers2.minersdelight'/4717, l='MpServer', x=-206.19, y=23.13, z=9.81], EntityItem['item.tile.bop.flowers2.minersdelight'/4716, l='MpServer', x=-201.88, y=22.13, z=15.13], EntityItem['item.tile.bop.flowers2.minersdelight'/4720, l='MpServer', x=-205.03, y=23.13, z=10.34], EntitySheep['Sheep'/4744, l='MpServer', x=-180.03, y=71.00, z=0.09], EntitySheep['Sheep'/4745, l='MpServer', x=-193.06, y=69.00, z=-20.03], EntitySheep['Sheep'/4743, l='MpServer', x=-173.03, y=72.00, z=-8.97], EntityItem['item.tile.bop.stoneFormations.stalagmite'/4757, l='MpServer', x=-160.13, y=34.13, z=28.13], EntityItem['item.tile.bop.stoneFormations.stalagmite'/4756, l='MpServer', x=-161.13, y=32.13, z=29.13], EntityItem['item.tile.bop.stoneFormations.stalagmite'/4753, l='MpServer', x=-159.88, y=21.13, z=-35.88], EntityItem['item.tile.bop.stoneFormations.stalagmite'/4755, l='MpServer', x=-162.13, y=31.13, z=30.13], EntityItem['item.tile.bop.stoneFormations.stalagmite'/4754, l='MpServer', x=-162.88, y=32.13, z=28.13], EntitySheep['Sheep'/4776, l='MpServer', x=-126.50, y=72.00, z=-4.50], EntityMinecartChest['entity.MinecartChest.name'/4777, l='MpServer', x=-132.50, y=26.50, z=44.50], EntitySheep['Sheep'/4774, l='MpServer', x=-127.50, y=70.00, z=-0.50], EntitySheep['Sheep'/4775, l='MpServer', x=-125.81, y=72.00, z=-2.81], EntityMinecartChest['entity.MinecartChest.name'/4772, l='MpServer', x=-136.50, y=26.50, z=59.50], EntitySheep['Sheep'/4773, l='MpServer', x=-124.22, y=71.00, z=-1.22], EntityMinecartChest['entity.MinecartChest.name'/4770, l='MpServer', x=-146.50, y=27.50, z=29.50], EntityItem['item.tile.torch'/4771, l='MpServer', x=-138.78, y=26.13, z=57.84], EntityItem['item.tile.bop.stoneFormations.stalactite'/12503, l='MpServer', x=-228.56, y=34.13, z=10.51], EntityBat['Bat'/4857, l='MpServer', x=-246.75, y=49.00, z=16.25], EntitySkeleton['Skeleton'/7608, l='MpServer', x=-19.30, y=-246.62, z=9.72], EntityItem['item.tile.bop.stoneFormations.stalactite'/11861, l='MpServer', x=-233.66, y=17.13, z=19.88], EntityItem['item.tile.bop.flowers2.minersdelight'/12162, l='MpServer', x=-199.09, y=34.13, z=33.06], EntityItem['item.tile.bop.stoneFormations.stalagmite'/12170, l='MpServer', x=-198.09, y=41.99, z=0.01], EntityItem['item.tile.gravel'/7342, l='MpServer', x=-144.50, y=41.13, z=19.41], EntityItem['item.tile.gravel'/7343, l='MpServer', x=-144.50, y=41.13, z=20.22], EntityBat['Bat'/5135, l='MpServer', x=-103.13, y=22.10, z=60.56], EntityBat['Bat'/5134, l='MpServer', x=-95.25, y=22.10, z=55.13], EntityItem['item.tile.bop.flowers2.minersdelight'/12244, l='MpServer', x=-144.88, y=30.13, z=54.17], EntityItem['item.tile.bop.stoneFormations.stalactite'/12067, l='MpServer', x=-221.69, y=38.13, z=40.50], EntityItem['item.tile.bop.stoneFormations.stalagmite'/12052, l='MpServer', x=-160.78, y=17.13, z=50.09], EntityItem['item.tile.bop.stoneFormations.stalagmite'/7182, l='MpServer', x=-204.66, y=37.13, z=10.88], EntityFallingSand['Falling Block'/11508, l='MpServer', x=-152.50, y=24.72, z=139.50], EntityFallingSand['Falling Block'/11511, l='MpServer', x=-151.50, y=24.72, z=138.50], EntityFallingSand['Falling Block'/11512, l='MpServer', x=-149.50, y=24.49, z=138.50], EntityFallingSand['Falling Block'/11513, l='MpServer', x=-149.50, y=24.49, z=139.50], EntityBat['Bat'/13794, l='MpServer', x=-249.25, y=31.00, z=10.31], EntityBat['Bat'/13780, l='MpServer', x=-195.54, y=38.17, z=29.41], EntityBat['Bat'/13783, l='MpServer', x=-195.44, y=26.00, z=-65.60], EntityBat['Bat'/13779, l='MpServer', x=-190.03, y=41.00, z=30.90], EntityBat['Bat'/13789, l='MpServer', x=-239.50, y=27.00, z=50.75], EntityBat['Bat'/13788, l='MpServer', x=-230.20, y=27.02, z=49.63], EntityBat['Bat'/13785, l='MpServer', x=-229.19, y=26.37, z=47.34], EntityBat['Bat'/13784, l='MpServer', x=-198.25, y=26.90, z=-73.48], EntityBat['Bat'/13787, l='MpServer', x=-229.26, y=25.74, z=47.44], EntityItem['item.tile.bop.stoneFormations.stalactite'/6062, l='MpServer', x=-225.53, y=35.13, z=8.22], EntityItem['item.tile.bop.stoneFormations.stalactite'/7903, l='MpServer', x=-202.34, y=17.13, z=16.31], EntityItem['item.tile.bop.stoneFormations.stalactite'/13318, l='MpServer', x=-234.06, y=17.13, z=19.13], EntityItem['item.tile.bop.flowers2.minersdelight'/13336, l='MpServer', x=-205.72, y=35.13, z=32.78], EntityFallingSand['Falling Block'/9591, l='MpServer', x=-151.50, y=21.49, z=138.50], EntityItem['item.tile.bop.stoneFormations.stalagmite'/11769, l='MpServer', x=-208.91, y=37.13, z=11.22], EntityFallingSand['Falling Block'/11546, l='MpServer', x=-32.50, y=21.49, z=132.50], EntityFallingSand['Falling Block'/11543, l='MpServer', x=-31.50, y=21.61, z=133.50], EntityItem['item.tile.bop.flowers2.minersdelight'/7726, l='MpServer', x=-163.97, y=12.13, z=-43.81]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:440)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2312)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:863)
    at net.minecraft.client.main.Main.main(SourceFile:101)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:27)

-- System Details --
Details:
    Minecraft Version: 1.6.4
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.7.0_45, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 375805616 bytes (358 MB) / 796393472 bytes (759 MB) up to 954728448 bytes (910 MB)
    JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G
    AABB Pool Size: 6302 (352912 bytes; 0 MB) allocated, 984 (55104 bytes; 0 MB) used
    Suspicious classes: FML and Forge are installed
    IntCache: cache: 0, tcache: 0, allocated: 4, tallocated: 58
    FML: MCP v8.11 FML v6.99.19.964 Minecraft Forge 9.11.1.964 51 mods loaded, 51 mods active
    mcp{8.09} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    FML{6.99.19.964} [Forge Mod Loader](forge-1.6.4-9.11.1.964.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    Forge{9.11.1.964} [Minecraft Forge](forge-1.6.4-9.11.1.964.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    AppliedEnergistics-Core{rv14.finale} [AppliedEnergistics Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    CodeChickenCore{0.9.0.6} [CodeChicken Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    NotEnoughItems{1.6.1.5} [Not Enough Items](NotEnoughItems 1.6.1.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    TConstruct-Preloader{0.0.1} [Tinkers Corestruct](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    BuildCraft|Core{4.1.2} [BuildCraft](buildcraft-A-1.6.2-4.1.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    BuildCraft|Energy{4.1.2} [BC Energy](buildcraft-A-1.6.2-4.1.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    BiomesOPlenty{1.1.3} [Biomes O' Plenty](BiomesOPlenty-universal-1.6.4-1.1.3.300.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    Forestry{2.3.0.7} [Forestry for Minecraft](forestry-A-2.3.0.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    Thaumcraft{4.0.5a} [Thaumcraft](Thaumcraft4.0.5a.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    betterstorage{0.7.3.38} [BetterStorage](1.6.4.BetterStorage_0.7.3.38.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    bspkrsCore{v5.0(1.6.4)} [bspkrsCore]([1.6.4]bspkrsCorev5.0.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    TreeCapitator{Forge 1.6.4.r06} [Treecapitator]([1.6.4]TreeCapitator.Forge.1.6.4.r06.Universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    arsmagica2{1.0.2b} [Ars Magica 2](AM2_1.0.2b.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    AppliedEnergistics{rv14.finale} [Applied Energistics](appeng-rv14-finale-mc16x.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    Backpack{1.18.17} [Backpack](backpack-1.18.17-1.6.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    barrels{3.3} [The Barrels Mod](Barrels 3.3-1.6.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    BiblioCraft{1.5.1} [BiblioCraft](BiblioCraft[v1.5.1].zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    BuildCraft|Builders{4.1.2} [BC Builders](buildcraft-A-1.6.2-4.1.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    BuildCraft|Factory{4.1.2} [BC Factory](buildcraft-A-1.6.2-4.1.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    BuildCraft|Transport{4.1.2} [BC Transport](buildcraft-A-1.6.2-4.1.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    BuildCraft|Silicon{4.1.2} [BC Silicon](buildcraft-A-1.6.2-4.1.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    ChickenChunks{1.3.3.3} [ChickenChunks](ChickenChunks 1.3.3.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    CoFHCore{2.0.0.b7a} [CoFH Core](CoFHCore-2.0.0.b7a.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    CoFHLoot{2.0.0.b7a} [CoFH Loot](CoFHCore-2.0.0.b7a.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    CoFHMasquerade{2.0.0.b7a} [CoFH Masquerade](CoFHCore-2.0.0.b7a.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    CoFHSocial{2.0.0.b7a} [CoFH Social](CoFHCore-2.0.0.b7a.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    CoFHWorld{2.0.0.b7a} [CoFH World](CoFHCore-2.0.0.b7a.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    dimdoors{1.6.2R2.1.1RC1} [Dimensional Doors](DimensionalDoors-1.6.2R2.1.1RC1-10.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    eplus{1.16.5b} [Enchanting Plus](EnchantingPlus-1.16.5.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    EnderStorage{1.4.3.5} [EnderStorage](EnderStorage 1.4.3.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    ExtraUtilities{0.3.5} [Extra Utilities](extrautils - 0.3.5.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    inventorytweaks{1.56} [Inventory Tweaks](InventoryTweaks-MC1.6.2-1.56-b77.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    IronChest{5.4.1.642} [Iron Chest](ironchest-universal-1.6.4-5.4.1.642.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    Mystcraft{0.10.10.00} [Mystcraft](mystcraft-uni-1.6.4-0.10.10.00.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    NEIAddons{1.9.3.r47} [NEI Addons](neiaddons-1.6.2-1.9.3.r47.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    NEIAddons|AE{1.9.3.r47} [NEI Addons: Applied Energistics](neiaddons-1.6.2-1.9.3.r47.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    NEIAddons|CraftingTables{1.9.3.r47} [NEI Addons: Crafting Tables](neiaddons-1.6.2-1.9.3.r47.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    NEIAddons|ExtraBees{1.9.3.r47} [NEI Addons: Extra Bees](neiaddons-1.6.2-1.9.3.r47.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    NEIAddons|Forestry{1.9.3.r47} [NEI Addons: Forestry](neiaddons-1.6.2-1.9.3.r47.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    NEIAddons|MiscPeripherals{1.9.3.r47} [NEI Addons: Misc Peripherals](neiaddons-1.6.2-1.9.3.r47.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    NEIPlugins{1.1.0.4} [NEI Plugins](NEIPlugins-1.1.0.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    OpenBlocks{1.2.2} [OpenBlocks](OpenBlocks-1.2.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    Railcraft{8.2.0.0} [Railcraft](Railcraft_1.6.2-8.2.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    DarrenPR_RottenFleshToLeather{1.0.0} [Rotten Flesh to Leather](RottenFleshToLeather_1.6.4.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    ThermalExpansion{3.0.0.b7a} [Thermal Expansion](ThermalExpansion-3.0.0.b7a.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    TConstruct{1.6.X_1.5.1d} [Tinkers' Construct](TConstruct_1.6.4_1.5.1d9.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    Translocator{1.1.0.13} [Translocator](Translocator 1.1.0.13.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    TwilightForest{1.20.2} [The Twilight Forest](twilightforest-1.20.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    TConstruct Environment: Sane and ready for action. Bugs may be reported.
    Launched Version: 1.6.4-Forge9.11.1.964
    LWJGL: 2.9.0
    OpenGL: Intel(R) HD Graphics GL version 3.3.0 - Build 8.15.10.2712, Intel
    Is Modded: Definitely; Client brand changed to 'fml,forge'
    Type: Client (map_client.txt)
    Resource Pack: Defaultc
    Current Language: English (US)
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 4055 (227080 bytes; 0 MB) allocated, 566 (31696 bytes; 0 MB) used[/spoiler]

**Comment by Kobata** [comment]
#116
