### ISSUE TITLE
Crash after changing InvTweakTrees.txt

### ISSUE THREAD

**Issue by phoebustam** [Inventory-Tweaks/inventory-tweaks#118]
I tried to add somemore rules as I installed Galacticraft and wanted to sort Galacticraft items, but after I added some rules with the same name with existing rules, the game crashed.  I erased everything I added (kind of restore the InvTweakTree.txt file) and reopen the game, the mod was loaded on main page but it wasn't in the game.  And the game crashes everytime I go into a game with this mod.  I don't know how to delete the InvTweakTree.txt file and I don't know how to reinstall this mod with every settings this mod created, what am I supposed to do?

**Comment by Kobata** [comment]
Just deleting the file should work, it will be re-created from the default settings.

If it's crashing you should post the crash message at the very least though.

**Comment by phoebustam** [comment]
Kobata, I don't know where is the file located, how do I delete the file?  Also, can I set up new rules with the same name (but different ID) as rules existed?

**Comment by phoebustam** [comment]
oh, I found out the txt file is located in the config file.  The mod works again, thank you for your help.
