### ISSUE TITLE
Does this mod supports other mods' items?

### ISSUE THREAD

**Issue by phoebustam** [Inventory-Tweaks/inventory-tweaks#119]
Say for an example, I am playing Galacticraft and there are many new items available, such as Heavy Duty Sword, made with steel.  Not as durable as diamond sword, yet, it is three times durable than Iron Sword.  Last time I tried to sort an item of Galacticraft but I failed to do so because that item doesn't show up in creative mode item list.

Now the sword is available in the creative mode list and it can be crafted.  Now I found the ID 10141 and I inserted into the sword list in the tree file as follows(omitted angle brackets because of HTML):

stuff treeVersion="1.6.0"
    equipment
        weapon
            sword
                diamondSword id="276"/
                heavyDutySword id=“10141”/
                ironSword id="267"/
                stoneSword id="272"/
                goldSword id="283"/
                woodSword id="268"/
            /sword
(text below omitted...)

And try to sort, and the game crashed, with the following crash report:
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 12/8/13 12:03 PM
Description: Unexpected error

java.lang.NullPointerException
    at invtweaks.InvTweaks.isSortingShortcutDown(InvTweaks.java:901)
    at invtweaks.InvTweaks.handleConfigSwitch(InvTweaks.java:463)
    at invtweaks.InvTweaks.onTick(InvTweaks.java:448)
    at invtweaks.InvTweaks.onTickInGame(InvTweaks.java:114)
    at invtweaks.forge.ForgeClientTick.tickEnd(ForgeClientTick.java:45)
    at cpw.mods.fml.common.SingleIntervalHandler.tickEnd(SingleIntervalHandler.java:34)
    at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:141)
    at cpw.mods.fml.common.FMLCommonHandler.onRenderTickEnd(FMLCommonHandler.java:377)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:946)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:836)
    at net.minecraft.client.main.Main.main(SourceFile:101)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:57)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:18)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at invtweaks.InvTweaks.isSortingShortcutDown(InvTweaks.java:901)
    at invtweaks.InvTweaks.handleConfigSwitch(InvTweaks.java:463)
    at invtweaks.InvTweaks.onTick(InvTweaks.java:448)
    at invtweaks.InvTweaks.onTickInGame(InvTweaks.java:114)
    at invtweaks.forge.ForgeClientTick.tickEnd(ForgeClientTick.java:45)
    at cpw.mods.fml.common.SingleIntervalHandler.tickEnd(SingleIntervalHandler.java:34)
    at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:141)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [GCCorePlayerSP['phoebustam'/57, l='MpServer', x=267.16, y=64.62, z=194.32]]
    Chunk stats: MultiplayerChunkCache: 441
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: World: (252,64,196), Chunk: (at 12,4,4 in 15,12; contains blocks 240,0,192 to 255,255,207), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 1721 game time, 1721 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
    Forced entities: 123 total; [EntityCow['Cow'/12, l='MpServer', x=196.53, y=77.00, z=122.53], EntityCow['Cow'/13, l='MpServer', x=195.47, y=77.00, z=123.53], EntityCow['Cow'/14, l='MpServer', x=195.28, y=78.00, z=121.53], EntityCow['Cow'/15, l='MpServer', x=199.38, y=76.00, z=134.63], EntityChicken['Chicken'/17, l='MpServer', x=205.50, y=65.00, z=148.50], EntityChicken['Chicken'/16, l='MpServer', x=207.50, y=63.00, z=150.50], EntityChicken['Chicken'/19, l='MpServer', x=211.50, y=80.00, z=149.50], EntityChicken['Chicken'/18, l='MpServer', x=213.63, y=70.00, z=146.59], EntityCow['Cow'/25, l='MpServer', x=229.59, y=66.00, z=180.38], EntityCow['Cow'/24, l='MpServer', x=234.50, y=65.81, z=184.46], EntityCow['Cow'/27, l='MpServer', x=233.22, y=73.00, z=177.38], EntityItem['item.tile.sapling.oak'/23923, l='MpServer', x=224.78, y=84.13, z=147.75], EntityCow['Cow'/26, l='MpServer', x=231.19, y=64.00, z=182.94], EntityItem['item.tile.sapling.oak'/21996, l='MpServer', x=250.38, y=88.13, z=177.81], EntityPig['Pig'/29, l='MpServer', x=250.16, y=75.00, z=167.09], EntityPig['Pig'/28, l='MpServer', x=246.50, y=82.00, z=175.50], EntityPig['Pig'/31, l='MpServer', x=245.50, y=74.00, z=177.50], EntityPig['Pig'/30, l='MpServer', x=246.50, y=81.00, z=176.50], EntityCow['Cow'/42, l='MpServer', x=282.47, y=70.00, z=125.47], EntityCow['Cow'/43, l='MpServer', x=283.81, y=70.00, z=126.53], EntityCow['Cow'/40, l='MpServer', x=285.50, y=70.00, z=121.50], EntityCow['Cow'/41, l='MpServer', x=281.50, y=70.00, z=122.50], EntitySquid['Squid'/74, l='MpServer', x=218.94, y=59.94, z=222.69], EntityZombie['Zombie'/17556, l='MpServer', x=226.50, y=20.00, z=233.50], EntityZombie['Zombie'/17557, l='MpServer', x=229.50, y=20.00, z=225.50], EntityZombie['Zombie'/17561, l='MpServer', x=281.50, y=29.00, z=148.50], EntitySquid['Squid'/103, l='MpServer', x=208.16, y=53.28, z=206.59], EntitySquid['Squid'/97, l='MpServer', x=232.03, y=53.31, z=226.03], EntityItem['item.tile.sapling.oak'/23838, l='MpServer', x=258.16, y=86.13, z=181.75], EntitySquid['Squid'/158, l='MpServer', x=321.34, y=56.16, z=153.25], GCCorePlayerSP['phoebustam'/57, l='MpServer', x=267.16, y=64.62, z=194.32], EntityItem['item.tile.sapling.oak'/6407, l='MpServer', x=246.66, y=85.13, z=162.81], EntitySquid['Squid'/174, l='MpServer', x=232.84, y=51.34, z=217.19], EntitySquid['Squid'/173, l='MpServer', x=223.28, y=51.19, z=211.03], EntityCreeper['Creeper'/182, l='MpServer', x=227.50, y=27.00, z=222.50], EntityItem['item.tile.sapling.oak'/19603, l='MpServer', x=245.88, y=75.13, z=183.41], EntityBat['Bat'/199, l='MpServer', x=240.50, y=22.00, z=228.25], EntityItem['item.tile.sapling.oak'/21796, l='MpServer', x=274.75, y=79.13, z=136.38], EntityItem['item.tile.sapling.oak'/23992, l='MpServer', x=251.84, y=83.13, z=142.06], EntityItem['item.item.apple'/23964, l='MpServer', x=259.19, y=68.13, z=141.13], EntityItem['item.tile.sapling.oak'/17866, l='MpServer', x=229.66, y=71.13, z=157.13], EntityCreeper['Creeper'/316, l='MpServer', x=220.50, y=19.00, z=255.50], EntitySkeleton['Skeleton'/299, l='MpServer', x=215.50, y=38.00, z=173.50], EntityCreeper['Creeper'/332, l='MpServer', x=268.59, y=26.00, z=250.00], EntityZombie['Zombie'/328, l='MpServer', x=275.70, y=11.40, z=128.30], EntityBat['Bat'/21580, l='MpServer', x=209.46, y=15.00, z=252.27], EntityCreeper['Creeper'/461, l='MpServer', x=222.00, y=35.00, z=192.53], EntityCreeper['Creeper'/17721, l='MpServer', x=249.50, y=24.00, z=217.50], EntitySkeleton['Skeleton'/501, l='MpServer', x=256.50, y=47.00, z=184.91], EntityBat['Bat'/23684, l='MpServer', x=206.75, y=45.10, z=191.25], EntityBat['Bat'/23685, l='MpServer', x=218.28, y=36.74, z=177.46], EntityZombie['Zombie'/492, l='MpServer', x=213.97, y=15.00, z=233.47], EntityItem['item.tile.sapling.jungle'/17702, l='MpServer', x=282.81, y=69.13, z=142.13], EntityCreeper['Creeper'/20054, l='MpServer', x=263.50, y=32.00, z=207.50], EntityItem['item.tile.sapling.oak'/639, l='MpServer', x=259.78, y=85.13, z=168.22], EntityItem['item.tile.sapling.oak'/18050, l='MpServer', x=254.16, y=89.13, z=179.38], EntityItem['item.item.apple'/22362, l='MpServer', x=243.09, y=74.13, z=184.34], EntityItem['item.tile.sapling.oak'/8429, l='MpServer', x=313.19, y=76.13, z=133.28], EntityBat['Bat'/25663, l='MpServer', x=283.53, y=14.20, z=191.00], EntityBat['Bat'/25664, l='MpServer', x=276.22, y=16.60, z=194.16], EntityBat['Bat'/25665, l='MpServer', x=270.13, y=13.98, z=191.63], EntityItem['item.tile.sapling.oak'/17971, l='MpServer', x=250.50, y=87.13, z=182.06], EntityCreeper['Creeper'/22328, l='MpServer', x=200.50, y=27.00, z=173.50], EntitySkeleton['Skeleton'/24488, l='MpServer', x=211.50, y=17.00, z=180.50], EntityZombie['Zombie'/22322, l='MpServer', x=201.47, y=23.00, z=168.06], EntityCreeper['Creeper'/22323, l='MpServer', x=190.50, y=26.00, z=168.50], EntityZombie['Zombie'/22326, l='MpServer', x=292.59, y=20.00, z=123.53], EntityZombie['Zombie'/22327, l='MpServer', x=281.50, y=25.00, z=117.50], EntityItem['item.item.seeds'/8527, l='MpServer', x=247.16, y=69.13, z=143.56], EntityItem['item.item.apple'/4763, l='MpServer', x=236.06, y=77.13, z=148.28], EntityItem['item.tile.sapling.oak'/4805, l='MpServer', x=251.13, y=76.13, z=134.38], EntityItem['item.tile.sapling.oak'/25925, l='MpServer', x=268.84, y=80.14, z=143.23], EntityItem['item.tile.sapling.oak'/20885, l='MpServer', x=230.16, y=83.13, z=140.78], EntitySkeleton['Skeleton'/22958, l='MpServer', x=225.44, y=28.00, z=208.91], EntityCreeper['Creeper'/22944, l='MpServer', x=248.50, y=44.00, z=235.50], EntityCreeper['Creeper'/22945, l='MpServer', x=248.50, y=44.00, z=237.50], EntityCreeper['Creeper'/22946, l='MpServer', x=248.50, y=44.00, z=236.50], EntityCreeper['Creeper'/25152, l='MpServer', x=297.50, y=43.00, z=195.34], EntityItem['item.tile.sapling.oak'/3169, l='MpServer', x=231.34, y=72.13, z=159.13], EntityItem['item.tile.sapling.oak'/7505, l='MpServer', x=246.22, y=87.13, z=166.22], EntityItem['item.tile.sapling.oak'/16467, l='MpServer', x=270.88, y=75.13, z=169.63], EntityCreeper['Creeper'/25149, l='MpServer', x=301.50, y=44.00, z=200.50], EntitySpider['Spider'/25151, l='MpServer', x=299.97, y=44.00, z=198.50], EntityCreeper['Creeper'/25150, l='MpServer', x=298.28, y=44.00, z=198.50], EntityItem['item.tile.sapling.oak'/16495, l='MpServer', x=253.97, y=70.13, z=145.31], EntityItem['item.tile.sapling.oak'/16829, l='MpServer', x=242.03, y=87.13, z=162.09], EntitySkeleton['Skeleton'/20623, l='MpServer', x=253.50, y=30.00, z=234.03], EntitySkeleton['Skeleton'/25556, l='MpServer', x=213.50, y=23.00, z=227.50], EntitySkeleton['Skeleton'/25555, l='MpServer', x=215.50, y=23.00, z=227.50], EntitySkeleton['Skeleton'/20625, l='MpServer', x=258.78, y=31.00, z=238.38], EntitySkeleton['Skeleton'/20627, l='MpServer', x=257.88, y=31.00, z=240.41], EntitySkeleton['Skeleton'/20626, l='MpServer', x=263.50, y=31.00, z=235.50], EntityBat['Bat'/20698, l='MpServer', x=226.51, y=22.87, z=264.46], EntityItem['item.item.seeds'/22712, l='MpServer', x=270.91, y=67.13, z=136.84], EntityCreeper['Creeper'/18845, l='MpServer', x=263.50, y=32.00, z=240.50], EntityCreeper['Creeper'/18859, l='MpServer', x=239.00, y=39.00, z=208.41], EntityBat['Bat'/22781, l='MpServer', x=189.53, y=28.51, z=167.91], EntityBat['Bat'/22780, l='MpServer', x=189.98, y=54.26, z=204.52], EntityBat['Bat'/22774, l='MpServer', x=254.41, y=34.60, z=199.59], EntityItem['item.tile.sapling.oak'/15938, l='MpServer', x=262.19, y=82.13, z=164.03], EntityItem['item.tile.sapling.oak'/16718, l='MpServer', x=247.75, y=84.13, z=162.22], EntityBat['Bat'/5261, l='MpServer', x=239.25, y=24.10, z=252.88], EntityItem['item.tile.sapling.oak'/24795, l='MpServer', x=248.38, y=89.13, z=179.13], EntityItem['item.item.seeds'/17120, l='MpServer', x=272.28, y=67.13, z=133.63], EntityItem['item.tile.sapling.oak'/17089, l='MpServer', x=253.81, y=77.13, z=136.09], EntitySkeleton['Skeleton'/21264, l='MpServer', x=288.50, y=12.00, z=230.50], EntitySkeleton['Skeleton'/21265, l='MpServer', x=286.88, y=12.00, z=230.44], EntitySkeleton['Skeleton'/21259, l='MpServer', x=297.50, y=40.00, z=173.50], EntityZombie['Zombie'/21258, l='MpServer', x=285.50, y=25.00, z=117.50], EntityZombie['Zombie'/21257, l='MpServer', x=283.50, y=25.00, z=117.50], EntityItem['item.tile.sapling.oak'/16905, l='MpServer', x=243.81, y=88.13, z=169.13], EntityCreeper['Creeper'/17013, l='MpServer', x=284.06, y=43.00, z=189.56], EntitySkeleton['Skeleton'/17012, l='MpServer', x=285.25, y=42.00, z=185.84], EntityItem['item.item.seeds'/19171, l='MpServer', x=248.59, y=68.13, z=140.66], EntityItem['item.tile.sapling.oak'/15703, l='MpServer', x=248.81, y=87.13, z=166.19], EntitySkeleton['Skeleton'/24635, l='MpServer', x=198.50, y=35.00, z=188.50], EntityItem['item.tile.sapling.oak'/21128, l='MpServer', x=274.88, y=76.13, z=169.88], EntityItem['item.item.apple'/25049, l='MpServer', x=248.19, y=86.13, z=175.72], EntityItem['item.tile.sapling.oak'/4064, l='MpServer', x=233.06, y=85.13, z=142.28], EntityItem['item.tile.sapling.oak'/4081, l='MpServer', x=283.75, y=74.13, z=138.13], EntitySkeleton['Skeleton'/21173, l='MpServer', x=254.41, y=23.00, z=205.97], EntityBat['Bat'/24915, l='MpServer', x=190.25, y=32.10, z=138.25], EntityBat['Bat'/24917, l='MpServer', x=226.41, y=27.39, z=225.63]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:440)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2310)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:861)
    at net.minecraft.client.main.Main.main(SourceFile:101)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:57)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:18)

-- System Details --
Details:
    Minecraft Version: 1.6.2
    Operating System: Mac OS X (x86_64) version 10.9
    Java Version: 1.6.0_65, Apple Inc.
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Apple Inc.
    Memory: 129332760 bytes (123 MB) / 324419584 bytes (309 MB) up to 1065025536 bytes (1015 MB)
    JVM Flags: 1 total; -Xmx1G
    AABB Pool Size: 2257 (126392 bytes; 0 MB) allocated, 2049 (114744 bytes; 0 MB) used
    Suspicious classes: FML and Forge are installed
    IntCache: cache: 0, tcache: 0, allocated: 3, tallocated: 63
    FML: MCP v8.04 FML v6.2.62.871 Minecraft Forge 9.10.1.871 16 mods loaded, 16 mods active
    mcp{8.04} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
    FML{6.2.62.871} [Forge Mod Loader](minecraftforge-9.10.1.871.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
    Forge{9.10.1.871} [Minecraft Forge](minecraftforge-9.10.1.871.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
    Micdoodlecore{} [Micdoodle8 Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
    PlayerAPI{1.2} [Player API](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
    TooManyItems{1.6.2} [TooManyItems](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
    DamageIndicatorsMod{2.9.0.1} [Damage Indicators](1.6.2 DamageIndicators v2.9.0.1.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
    mod_WheatPlanter{1.5} [mod_WheatPlanter](AutomaticWheatFarmer1.6.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
    GalacticraftCore{2.0.6} [Galacticraft Core](Galacticraft-1.6.2-2.0.6.893.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
    GalacticraftMars{2.0.6} [Galacticraft Mars](Galacticraft-Planets-1.6.2-2.0.6.893.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
    mod_Gammabright{by kymaster, v2.0 for MC 1.6.2} [mod_Gammabright](Gammabright v2.0 [MC 1.6.2].zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
    inventorytweaks{1.56} [Inventory Tweaks](InventoryTweaks-MC1.6.2-1.56-b77.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
    mod_SmartMoving{14.3} [Smart Moving](Smart Moving Universal for ModLoader or Minecraft Forge or MCPC+.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
    mod_SmartRender{1.1} [Smart Render](Smart Moving Universal for ModLoader or Minecraft Forge or MCPC+.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
    mod_ZanMinimap{0.9.4} [Zan's Minimap](Zans-Minimap-Mod-ML-Forge-1.6.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
    mod_Xray{MX for 1.6.2} [mod_Xray](modXray.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
    Launched Version: 1.6.2-Forge9.10.1.871
    LWJGL: 2.9.0
    OpenGL: Intel HD Graphics 4000 OpenGL Engine GL version 2.1 INTEL-8.18.26, Intel Inc.
    Is Modded: Definitely; Client brand changed to 'fml,forge'
    Type: Client (map_client.txt)
    Resource Pack: Default
    Current Language: English (US)
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 1927 (107912 bytes; 0 MB) allocated, 1638 (91728 bytes; 0 MB) used

So is it true that mod items cannot be added to the list for sorting?
Thank you.

**Comment by Kobata** [comment]
Looks like you probably broke the format and it failed to load the config files correctly.

That tends to cause the mod to break at random places later.

**Comment by phoebustam** [comment]
What am I supposed to do?  What is the format?

**Comment by makerimages** [comment]
delete the configs and let it regenerate them.

**Comment by AEnterprise** [comment]
and then try to modify it again, you probably accidently erased something
