### ISSUE TITLE
Callback for IsLargeChest

### ISSUE THREAD

**Issue by Aroma1997** [Inventory-Tweaks/inventory-tweaks#120]
I have a @ChestContainer with a variable size, so I use the @RowSizeCallback
Is there any way of having also a Callback of if the Buttons are located horizontally or vertically?(isLargeChest=?)

**Comment by Kobata** [comment]
Not currently, although I may add one next MC version.

For now just make them always vertical if you only need it some times -- the other mods with variable-sized chests handle it that way currently.

**Comment by Aroma1997** [comment]
ok thank you for your time.
Oh is there also a way to manually set the position of the buttons?

**Comment by Kobata** [comment]
I forgot about this initially, but there's a callback for the large chest behavior (it probably will not work if the GUI in question is currently open), as well as an API function to initiate a sort, allowing for custom buttons to be added.
