### ISSUE TITLE
Game freezes when sort button is pressed.

### ISSUE THREAD

**Issue by mr10movie** [Inventory-Tweaks/inventory-tweaks#121]
I use the sort key while in a chest, press it a few times, and then the game freezes, and the 'Memory connection overburdened' message appears. No idea what is causing it, or why it started. I updated a few mods, and this never happened before then. I didn't update Inventory Tweaks, so I have no idea why this is happening.

ForgeModLoader-client.log:
http://pastebin.com/dWV8HY8a
Output-server.log:
http://pastebin.com/RmiQ8Cui

Removing InvTweaks fixes the issue (well duh).

**Comment by Kobata** [comment]
7822d5817216f35473584f105f323e95767506a3 should avoid the condition that causes the loop, but may break other things.

Just something I'm going to have to test more carefully in 1.7
