### ISSUE TITLE
GUI Crash (New World)

### ISSUE THREAD

**Issue by Simon04090** [Inventory-Tweaks/inventory-tweaks#122]
When I select "Create New World", the Game crashes. Here's the Crashreport:

---- Minecraft Crash Report ----
// You're mean.

Time: 29.12.13 14:38
Description: Updating screen events

java.lang.NullPointerException
    at invtweaks.forge.InvTweaksMod.setTextboxModeStatic(InvTweaksMod.java:74)
    at net.minecraft.client.gui.GuiTextField.func_73796_b(SourceFile:437)
    at net.minecraft.client.gui.GuiCreateWorld.func_73866_w_(GuiCreateWorld.java:123)
    at net.minecraft.client.gui.GuiScreen.func_73872_a(SourceFile:94)
    at net.minecraft.client.Minecraft.func_71373_a(Minecraft.java:730)
    at net.minecraft.client.gui.GuiSelectWorld.func_73875_a(SourceFile:124)
    at net.minecraft.client.gui.GuiScreen.func_73864_a(SourceFile:69)
    at net.minecraft.client.gui.GuiScreen.func_73867_d(SourceFile:128)
    at net.minecraft.client.gui.GuiScreen.func_73862_m(SourceFile:107)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1564)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:908)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:836)
    at net.minecraft.client.main.Main.main(SourceFile:101)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:57)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:18)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at invtweaks.forge.InvTweaksMod.setTextboxModeStatic(InvTweaksMod.java:74)
    at net.minecraft.client.gui.GuiTextField.func_73796_b(SourceFile:437)
    at net.minecraft.client.gui.GuiCreateWorld.func_73866_w_(GuiCreateWorld.java:123)
    at net.minecraft.client.gui.GuiScreen.func_73872_a(SourceFile:94)
    at net.minecraft.client.Minecraft.func_71373_a(Minecraft.java:730)
    at net.minecraft.client.gui.GuiSelectWorld.func_73875_a(SourceFile:124)
    at net.minecraft.client.gui.GuiScreen.func_73864_a(SourceFile:69)
    at net.minecraft.client.gui.GuiScreen.func_73867_d(SourceFile:128)
    at net.minecraft.client.gui.GuiScreen.func_73862_m(SourceFile:107)

-- Affected screen --
Details:
    Screen name: net.minecraft.client.gui.GuiCreateWorld
Stacktrace:
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1564)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:908)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:836)
    at net.minecraft.client.main.Main.main(SourceFile:101)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:57)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:18)

-- System Details --
Details:
    Minecraft Version: 1.6.2
    Operating System: Windows 8 (amd64) version 6.2
    Java Version: 1.7.0_45, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 499527040 bytes (476 MB) / 1344274432 bytes (1282 MB) up to 2863661056 bytes (2731 MB)
    JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Suspicious classes: FML and Forge are installed
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v8.04 FML v6.2.62.871 Minecraft Forge 9.10.1.871 Optifine OptiFine_1.6.2_HD_U_C4 54 mods loaded, 54 mods active
    mcp{8.04} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    FML{6.2.62.871} [Forge Mod Loader](minecraftforge-9.10.1.871.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Forge{9.10.1.871} [Minecraft Forge](minecraftforge-9.10.1.871.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    CodeChickenCore{0.9.0.5} [CodeChicken Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    NotEnoughItems{1.6.1.4} [Not Enough Items](NotEnoughItems 1.6.1.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    jammyfurniture{4.5} [Jammy Furniture Mod](1.6.2_Jammy_Furniture_Mod_V4.5.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    EnhancedBooks{1.7.2} [Enhanced Books]([1.6.2] Enhanced Books v1.7.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    mod_ReiMinimap{v3.4_01 [1.6.2]} [mod_ReiMinimap]([1.6.2]ReiMinimap_v3.4_01.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    craftablespawners{2.0} [Craftable Spawners]([1.6.4] Craftable-Spawners-2.0.3-1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    mod_WheatPlanter{1.5} [mod_WheatPlanter](AutomaticWheatFarmer1.6.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Backpack{1.22.25} [Backpack](backpack-1.22.25-1.6.x.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    barrels{3.3.2} [The Barrels Mod](Barrels 3.3.2 - 1.6.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    BiblioCraft{1.5.4} [BiblioCraft](BiblioCraft[v1.5.4].zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    mod_Biosphere{1.6.2} [mod_Biosphere](Biosphere.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    BuildCraft|Core{4.1.2} [BuildCraft](buildcraft-A-1.6.2-4.1.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    BuildCraft|Builders{4.1.2} [BC Builders](buildcraft-A-1.6.2-4.1.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    BuildCraft|Energy{4.1.2} [BC Energy](buildcraft-A-1.6.2-4.1.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    BuildCraft|Factory{4.1.2} [BC Factory](buildcraft-A-1.6.2-4.1.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    BuildCraft|Transport{4.1.2} [BC Transport](buildcraft-A-1.6.2-4.1.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    BuildCraft|Silicon{4.1.2} [BC Silicon](buildcraft-A-1.6.2-4.1.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Additional-Buildcraft-Objects{1.0.6.182} [Additional Buildcraft Objects](buildcraft-Z-additional-buildcraft-objects-1.0.6.182.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    CarpentersBlocks{v1.9.8} [Carpenter's Blocks](Carpenters_Blocks_v1.9.8_MC_1.6+.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ChickenChunks{1.3.3.2} [ChickenChunks](ChickenChunks 1.3.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    IC2{2.0.305-experimental} [IndustrialCraft 2](industrialcraft-2_2.0.305-experimental.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    CompactSolars{4.4.11.114} [Compact Solar Arrays](compactsolars-universal-1.6.2-4.4.11.114.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    mraxzipcraftable{1.2} [Craftable Items & Blocks](CraftableItems&Blocks - 1.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    EnderStorage{1.4.3.3} [EnderStorage](EnderStorage 1.4.3.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ExtraUtilities{1.0.1} [Extra Utilities](extrautils-1.0.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Forestry{2.3.0.7} [Forestry for Minecraft](forestry-A-2.3.0.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    GraveStone{2.4.1} [GraveStone](GraveStone_2.4.1.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    GregsLighting{1.9.0} [Greg's Lighting](GregsLighting-1.9.0-mc1.6.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    IronChest{5.3.14.512} [Iron Chest](ironchest-universal-1.6.2-5.3.14.512.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    LavaBoat{2.0.0} [LavaBoat](LavaBoat_2.0.0.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    mod_MAtmos{r25 for 1.6.2} [mod_MAtmos](MAtmosClassesNDP_r25__1_6_2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    AdvancedSolarPanel{3.3.10} [Advanced Solar Panels](mod_AdvancedSolarPanels_3_3_10_IC_EXP.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    more-pistons{X.X.X for [1.6.2 Build By: Master801]} [More Pistons](More-Pistons_1.6.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MoreFurnaces{1.3.5} [More Furnaces](moreFurnaces-1.3.5-universal.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    NEIPlugins{1.1.0.6} [NEI Plugins](NEIPlugins-1.1.0.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ForgeMultipart{1.0.0.171} [Forge Multipart](ForgeMultipart-universal-1.6.2-1.0.0.171.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ProjRed|Core{4.0.1.4} [Project: Red-Core](ProjectRedBase-1.6.2-4.0.1.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ProjRed|Compatability{4.0.1.4} [ProjectRed-Compatability](ProjectRedCompat-1.6.2-4.0.1.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ProjRed|Integration{4.0.1.4} [ProjectRed-Integration](ProjectRedIntegration-1.6.2-4.0.1.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ProjRed|Transmission{4.0.1.4} [ProjectRed-Transmission](ProjectRedIntegration-1.6.2-4.0.1.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ProjRed|Exploration{4.0.1.4} [ProjectRed-Exploration](ProjectRedWorld-1.6.2-4.0.1.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ProjRed|Illumination{4.0.1.4} [ProjectRed-Illumination](ProjectRedWorld-1.6.2-4.0.1.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Railcraft{8.2.0.0} [Railcraft](Railcraft_1.6.2-8.2.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    mod_SpawnerGUI{1.6.2} [mod_SpawnerGUI](Spawner GUI.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    thorinmod{Version 1.0} [Thorin Mod](Thorin.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Waila{1.4.2} [Waila](Waila_1.4.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    WR-CBE|Core{1.4.0.5} [WR-CBE Core](WR-CBE 1.4.0.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    WR-CBE|Addons{1.4.0.5} [WR-CBE Addons](WR-CBE 1.4.0.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    WR-CBE|Logic{1.4.0.5} [WR-CBE Logic](WR-CBE 1.4.0.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    McMultipart{1.0.0.171} [Minecraft Multipart Plugin](ForgeMultipart-universal-1.6.2-1.0.0.171.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ForgeMicroblock{1.0.0.171} [Forge Microblocks](ForgeMultipart-universal-1.6.2-1.0.0.171.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Launched Version: 1.6.2-Forge9.10.1.871
    LWJGL: 2.9.0
    OpenGL: Intel(R) HD Graphics 4600 GL version 4.2.0 - Build 10.18.10.3379, Intel
    Is Modded: Definitely; Client brand changed to 'fml,forge'
    Type: Client (map_client.txt)
    Resource Pack: Soartex Fanver 1.6.x.zip
    Current Language: Deutsch (Deutschland)
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: ~~ERROR~~ NullPointerException: null

**Comment by Kobata** [comment]
The mod is installed incorrectly (or an old version), especially since it is not listed at all on the list of loaded mods.
