### ISSUE TITLE
Updating dev doc

### ISSUE THREAD

**Issue by bendem** [Inventory-Tweaks/inventory-tweaks#126]
I was reading https://github.com/Kobata/inventory-tweaks/wiki/Getting-started, but it seems that the build process has changed (using gradle instead of ant).
Maybe it would be time to update it...

I'm reporting that because when I try to build, I get this error : https://gist.github.com/9504fa0eaac33229db50

**Comment by Kobata** [comment]
Should be updated, but it's 'gradle build'

If you want an eclipse project made, 'gradle eclipse', for the full list of useful tasks ask the Forge people.

**Comment by bendem** [comment]
Thanks, I never use gradle before, it works just fin now :smile:
