### ISSUE TITLE
Crash upon trying to sort an inventory both single player and server

### ISSUE THREAD

**Issue by Ferlorn** [Inventory-Tweaks/inventory-tweaks#128]
---- Minecraft Crash Report ----
// Everything's going to plan. No, really, that was supposed to happen.

Time: 1/14/14 3:07 PM
Description: Unexpected error

java.lang.IllegalAccessError: tried to access class net.minecraft.client.gui.inventory.ContainerCreative from class invtweaks.containers.VanillaSlotMaps

This is from the error report generated when I try to use the mod, I have betterstorage and a few other mods installed, but it doesn't look like a compatibility problem. How could the illegal access issue be fixed?

**Comment by Ferlorn** [comment]
Also, it suggests that there is an anti-cheat plugin that is cancelling the operation, but there is none as far as I know. :-/ I'm running the modpack through the tekkit launcher if that changes anything.

**Comment by Kobata** [comment]
Forge and InventoryTweaks version please.

You're probably using an unsupported Forge version or a too-old InventoryTweaks version for that Forge version.

**Comment by Ferlorn** [comment]
Inventory Tweaks 1.56 and forge 1.6.4-9.11.1.953,

**Comment by Kobata** [comment]
Those versions should work (and do here) so you should probably double-check the versions and make sure everything is installed correctly.

Your error should never happen with any 1.6 version of Forge except for 160-164 which you can't download anymore because of that type of issue.
