### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Simon04090** [Inventory-Tweaks/inventory-tweaks#129]
I don't know why but it simply crashes. I didn't do anything (Minecraft was minimizied)
Here's the Crash Report:

---- Minecraft Crash Report ----
// Would you like a cupcake?

Time: 25.01.14 17:05
Description: Unexpected error

java.lang.NullPointerException
    at invtweaks.InvTweaks.isSortingShortcutDown(InvTweaks.java:901)
    at invtweaks.InvTweaks.onTick(InvTweaks.java:438)
    at invtweaks.InvTweaks.onTickInGUI(InvTweaks.java:133)
    at invtweaks.forge.ForgeClientTick.tickEnd(ForgeClientTick.java:43)
    at cpw.mods.fml.common.SingleIntervalHandler.tickEnd(SingleIntervalHandler.java:34)
    at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:141)
    at cpw.mods.fml.common.FMLCommonHandler.onRenderTickEnd(FMLCommonHandler.java:377)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:948)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:838)
    at net.minecraft.client.main.Main.main(SourceFile:101)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:27)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at invtweaks.InvTweaks.isSortingShortcutDown(InvTweaks.java:901)
    at invtweaks.InvTweaks.onTick(InvTweaks.java:438)
    at invtweaks.InvTweaks.onTickInGUI(InvTweaks.java:133)
    at invtweaks.forge.ForgeClientTick.tickEnd(ForgeClientTick.java:43)
    at cpw.mods.fml.common.SingleIntervalHandler.tickEnd(SingleIntervalHandler.java:34)
    at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:141)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityClientPlayerMP['Simon04090'/809159, l='MpServer', x=-14,34, y=65,62, z=259,01]]
    Chunk stats: MultiplayerChunkCache: 521
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: World: (-23,64,265), Chunk: (at 9,4,9 in -2,16; contains blocks -32,0,256 to -17,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
    Level time: 106099 game time, 126064 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
    Forced entities: 113 total; [EntityBat['Bat'/1096536, l='MpServer', x=-2,22, y=45,10, z=254,00], EntityBat['Bat'/1096535, l='MpServer', x=2,13, y=45,10, z=248,63], EntityCaveSpider['Cave Spider'/810124, l='MpServer', x=-6,50, y=-25,62, z=-4,50], EntityCreeper['Creeper'/2106038, l='MpServer', x=-7,22, y=44,00, z=255,13], EntityBat['Bat'/1484092, l='MpServer', x=2,13, y=45,10, z=265,75], EntitySkeleton['Skeleton'/1799157, l='MpServer', x=-2,31, y=44,00, z=268,69], EntityCreeper['Creeper'/1799162, l='MpServer', x=-22,38, y=44,00, z=264,00], EntitySkeleton['Skeleton'/1799160, l='MpServer', x=-1,50, y=44,00, z=255,91], EntityCreeper['Creeper'/1799161, l='MpServer', x=-11,37, y=44,00, z=263,98], EntityBat['Bat'/2101416, l='MpServer', x=-30,25, y=45,10, z=242,88], EntityBat['Bat'/2101417, l='MpServer', x=-29,72, y=46,10, z=258,75], EntityClientPlayerMP['Simon04090'/809159, l='MpServer', x=-78,30, y=70,62, z=250,70], EntitySkeleton['Skeleton'/867397, l='MpServer', x=-1,03, y=47,00, z=257,44], EntityMinecartChest['entity.MinecartChest.name'/809136, l='MpServer', x=-16,50, y=44,34, z=239,09], EntityMinecartChest['entity.MinecartChest.name'/809143, l='MpServer', x=31,50, y=28,50, z=185,50], EntityMinecartChest['entity.MinecartChest.name'/809141, l='MpServer', x=4,50, y=41,50, z=271,50], EntityMinecartChest['entity.MinecartChest.name'/809146, l='MpServer', x=35,50, y=23,50, z=233,50], EntityMinecartChest['entity.MinecartChest.name'/809144, l='MpServer', x=30,50, y=29,50, z=208,50], EntityMinecartChest['entity.MinecartChest.name'/809145, l='MpServer', x=27,50, y=36,50, z=221,50], EntityPig['Pig'/809123, l='MpServer', x=-73,50, y=74,00, z=287,31], EntityMinecartChest['entity.MinecartChest.name'/809127, l='MpServer', x=-25,50, y=43,50, z=231,50], EntityPig['Pig'/809126, l='MpServer', x=-68,13, y=72,00, z=296,72], EntityPig['Pig'/809125, l='MpServer', x=-77,50, y=70,00, z=286,81], EntityPig['Pig'/809124, l='MpServer', x=-77,50, y=70,00, z=285,22], EntityMinecartChest['entity.MinecartChest.name'/809128, l='MpServer', x=-11,50, y=41,50, z=223,50], EntityBat['Bat'/2016675, l='MpServer', x=-6,47, y=42,10, z=272,50], EntityBat['Bat'/2016677, l='MpServer', x=-11,50, y=42,10, z=273,13], EntityBat['Bat'/2016679, l='MpServer', x=-8,25, y=43,10, z=271,25], EntityEnderman['Enderman'/2099100, l='MpServer', x=-30,56, y=39,00, z=257,00], EntityCreeper['Creeper'/2098264, l='MpServer', x=-23,97, y=40,00, z=254,63], EntityCreeper['Creeper'/2098263, l='MpServer', x=-23,47, y=40,00, z=253,72], EntityCaveSpider['Cave Spider'/868314, l='MpServer', x=-11,66, y=-25,62, z=-5,01], EntitySkeleton['Skeleton'/2098423, l='MpServer', x=-27,53, y=40,00, z=252,80], EntitySkeleton['Skeleton'/2098424, l='MpServer', x=-38,38, y=41,00, z=265,78], EntityCaveSpider['Cave Spider'/868287, l='MpServer', x=11,34, y=-22,62, z=23,99], EntityClientPlayerMP['Simon04090'/809159, l='MpServer', x=-14,34, y=65,62, z=259,01], EntityChicken['Chicken'/821590, l='MpServer', x=-82,53, y=71,00, z=284,38], EntityChicken['Chicken'/821591, l='MpServer', x=-78,63, y=70,00, z=254,41], EntitySheep['Sheep'/821592, l='MpServer', x=-27,22, y=65,00, z=221,13], EntitySquid['Squid'/2107622, l='MpServer', x=18,75, y=54,00, z=228,50], EntityItem['item.item.wheat'/2107900, l='MpServer', x=-13,53, y=64,13, z=262,97], EntitySpider['Spider'/2104044, l='MpServer', x=-37,63, y=44,00, z=257,50], EntityBat['Bat'/2107765, l='MpServer', x=44,90, y=28,00, z=208,36], EntityBat['Bat'/2107769, l='MpServer', x=-9,47, y=41,10, z=242,88], EntitySquid['Squid'/2107683, l='MpServer', x=-73,25, y=52,13, z=207,59], EntitySquid['Squid'/2107704, l='MpServer', x=-59,47, y=50,38, z=206,63], EntitySquid['Squid'/2107707, l='MpServer', x=-65,19, y=50,38, z=208,56], EntitySpider['Spider'/2108124, l='MpServer', x=51,75, y=29,00, z=337,00], EntityCreeper['Creeper'/2108135, l='MpServer', x=-41,50, y=50,00, z=331,50], EntityCaveSpider['Cave Spider'/812153, l='MpServer', x=16,50, y=-22,62, z=24,50], EntityItem['item.item.seeds'/2108082, l='MpServer', x=-14,06, y=64,13, z=261,31], EntityItem['item.item.wheat'/2108081, l='MpServer', x=-13,88, y=64,13, z=260,88], EntityEnderman['Enderman'/2107976, l='MpServer', x=27,50, y=29,00, z=208,50], EntityCreeper['Creeper'/1666836, l='MpServer', x=-3,16, y=44,02, z=269,30], EntitySkeleton['Skeleton'/2108356, l='MpServer', x=-50,50, y=58,00, z=312,50], EntityZombie['Zombie'/2108373, l='MpServer', x=-91,50, y=19,00, z=313,50], EntityCreeper['Creeper'/2091961, l='MpServer', x=-7,06, y=44,00, z=251,59], EntityCreeper['Creeper'/2108405, l='MpServer', x=-6,63, y=40,00, z=253,00], EntityZombie['Zombie'/2108401, l='MpServer', x=-4,73, y=40,00, z=257,66], EntityZombie['Zombie'/2108402, l='MpServer', x=-5,63, y=40,00, z=253,88], EntityZombie['Zombie'/2108403, l='MpServer', x=-0,16, y=40,00, z=258,25], EntitySkeleton['Skeleton'/2108315, l='MpServer', x=45,50, y=28,00, z=208,50], EntityZombie['Zombie'/2095854, l='MpServer', x=40,34, y=-48,62, z=-0,01], EntitySkeleton['Skeleton'/2108328, l='MpServer', x=41,50, y=17,00, z=305,50], EntityZombie['Zombie'/2108275, l='MpServer', x=-75,50, y=55,00, z=317,50], EntityZombie['Zombie'/2108181, l='MpServer', x=-57,50, y=22,00, z=283,50], EntitySkeleton['Skeleton'/2108221, l='MpServer', x=23,50, y=33,00, z=204,50], EntityBat['Bat'/2108582, l='MpServer', x=-74,85, y=18,58, z=317,44], EntityBat['Bat'/2108580, l='MpServer', x=-75,24, y=14,82, z=319,57], EntityBat['Bat'/2108578, l='MpServer', x=-78,78, y=18,47, z=321,52], EntityBat['Bat'/2108577, l='MpServer', x=-84,69, y=19,88, z=324,91], EntitySkeleton['Skeleton'/2108560, l='MpServer', x=-58,50, y=16,00, z=294,50], EntityCreeper['Creeper'/2108572, l='MpServer', x=16,50, y=30,00, z=208,50], EntityZombie['Zombie'/2108570, l='MpServer', x=23,84, y=49,00, z=300,78], EntitySpider['Spider'/853644, l='MpServer', x=-19,70, y=-33,62, z=-8,70], EntityCreeper['Creeper'/2108559, l='MpServer', x=-9,50, y=29,00, z=202,50], EntitySkeleton['Skeleton'/2108658, l='MpServer', x=27,50, y=29,00, z=223,50], EntitySkeleton['Skeleton'/2108659, l='MpServer', x=23,50, y=29,00, z=222,50], EntitySpider['Spider'/2108647, l='MpServer', x=-84,50, y=19,00, z=326,50], EntityZombie['Zombie'/826479, l='MpServer', x=54,70, y=-31,55, z=-9,68], EntityCreeper['Creeper'/2108650, l='MpServer', x=-77,50, y=19,00, z=336,50], EntityCreeper['Creeper'/2108609, l='MpServer', x=-54,50, y=60,00, z=314,91], EntitySpider['Spider'/2108610, l='MpServer', x=-58,55, y=56,00, z=307,81], EntityCreeper['Creeper'/2108613, l='MpServer', x=38,50, y=22,00, z=315,50], EntityZombie['Zombie'/2108616, l='MpServer', x=-85,50, y=22,00, z=331,50], EntityZombie['Zombie'/2108478, l='MpServer', x=57,03, y=18,00, z=294,56], EntitySkeleton['Skeleton'/2108476, l='MpServer', x=-54,50, y=50,00, z=322,50], EntityZombie['Zombie'/2108475, l='MpServer', x=-64,50, y=50,00, z=311,50], EntityZombie['Zombie'/2108473, l='MpServer', x=-61,50, y=50,00, z=313,50], EntityZombie['Zombie'/2108472, l='MpServer', x=-61,50, y=50,00, z=315,50], EntityCreeper['Creeper'/2108470, l='MpServer', x=-55,50, y=60,00, z=320,50], EntityZombie['Zombie'/2108469, l='MpServer', x=-51,56, y=58,00, z=312,88], EntitySlime['Slime'/2096454, l='MpServer', x=-8,61, y=22,80, z=189,38], EntitySkeleton['Skeleton'/2108467, l='MpServer', x=51,69, y=43,00, z=265,91], EntitySkeleton['Skeleton'/2108466, l='MpServer', x=57,47, y=44,00, z=270,16], EntitySkeleton['Skeleton'/2108427, l='MpServer', x=65,50, y=20,00, z=301,13], EntityCreeper['Creeper'/2108543, l='MpServer', x=-79,44, y=16,00, z=321,00], EntitySkeleton['Skeleton'/2108542, l='MpServer', x=-74,50, y=18,00, z=316,50], EntitySkeleton['Skeleton'/2108541, l='MpServer', x=-53,50, y=36,00, z=336,50], EntityCreeper['Creeper'/2108528, l='MpServer', x=-23,31, y=25,00, z=308,69], EntityCreeper['Creeper'/2108527, l='MpServer', x=-20,59, y=26,00, z=307,00], EntitySkeleton['Skeleton'/2101134, l='MpServer', x=-44,94, y=48,00, z=269,47], EntitySkeleton['Skeleton'/2101136, l='MpServer', x=-30,63, y=48,00, z=264,13], EntityCaveSpider['Cave Spider'/811911, l='MpServer', x=16,50, y=-29,62, z=-33,50], EntityBat['Bat'/987548, l='MpServer', x=-5,25, y=45,10, z=252,09], EntityCaveSpider['Cave Spider'/868353, l='MpServer', x=11,34, y=-29,62, z=-34,01], EntityBat['Bat'/2097045, l='MpServer', x=-30,25, y=46,10, z=260,75], EntityBat['Bat'/2097046, l='MpServer', x=-18,25, y=46,10, z=239,50], EntityBat['Bat'/2097047, l='MpServer', x=-17,88, y=45,10, z=240,72], EntityBat['Bat'/2097048, l='MpServer', x=-32,34, y=46,10, z=255,75], EntitySpider['Spider'/2104564, l='MpServer', x=-6,28, y=44,00, z=249,56], EntitySkeleton['Skeleton'/2104559, l='MpServer', x=-1,63, y=44,00, z=253,16], EntityCreeper['Creeper'/868617, l='MpServer', x=-10,59, y=44,00, z=264,90]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:440)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2312)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:863)
    at net.minecraft.client.main.Main.main(SourceFile:101)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:27)

-- System Details --
Details:
    Minecraft Version: 1.6.4
    Operating System: Windows 8 (amd64) version 6.2
    Java Version: 1.7.0_45, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 320748656 bytes (305 MB) / 2138570752 bytes (2039 MB) up to 5726797824 bytes (5461 MB)
    JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6G
    AABB Pool Size: 4185 (234360 bytes; 0 MB) allocated, 2761 (154616 bytes; 0 MB) used
    Suspicious classes: FML and Forge are installed
    IntCache: cache: 0, tcache: 0, allocated: 6, tallocated: 62
    FML: MCP v8.11 FML v6.4.49.965 Minecraft Forge 9.11.1.965 Optifine OptiFine_1.6.4_HD_U_C8 67 mods loaded, 67 mods active
    mcp{8.09} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    FML{6.4.49.965} [Forge Mod Loader](minecraftforge-9.11.1.965.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    Forge{9.11.1.965} [Minecraft Forge](minecraftforge-9.11.1.965.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    CodeChickenCore{0.9.0.7} [CodeChicken Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    NotEnoughItems{1.6.1.8} [Not Enough Items](NotEnoughItems 1.6.1.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    shadersmod{2.2.1} [GLSL Shaders Mod](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    jammyfurniture{4.5} [Jammy Furniture Mod](1.6.2_Jammy_Furniture_Mod_V4.5.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    EnhancedBooks{1.7.2} [Enhanced Books]([1.6.4] Enhanced Books v1.7.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    bspkrsCore{v5.2(1.6.4)} [bspkrsCore]([1.6.4]bspkrsCorev5.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    TreeCapitator{Forge 1.6.4.r09} [Treecapitator]([1.6.4]TreeCapitator.Forge.1.6.4.r09.Universal.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    Autoutils{1.0.1} [Autoutils](autoutils-1.6.4-1.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    Backpack{1.26.29} [Backpack](backpack-1.26.29-1.6.x.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    barrels{3.3.2} [The Barrels Mod](Barrels 3.3.2 - 1.6.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    BiblioCraft{1.5.4} [BiblioCraft](BiblioCraft[v1.5.4].zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    BuildCraft|Core{4.2.2} [BuildCraft](buildcraft-A-1.6.4-4.2.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    BuildCraft|Builders{4.2.2} [BC Builders](buildcraft-A-1.6.4-4.2.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    BuildCraft|Energy{4.2.2} [BC Energy](buildcraft-A-1.6.4-4.2.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    BuildCraft|Factory{4.2.2} [BC Factory](buildcraft-A-1.6.4-4.2.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    BuildCraft|Transport{4.2.2} [BC Transport](buildcraft-A-1.6.4-4.2.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    BuildCraft|Silicon{4.2.2} [BC Silicon](buildcraft-A-1.6.4-4.2.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    Additional-Buildcraft-Objects{1.0.7.557} [Additional Buildcraft Objects](buildcraft-Z-additional-buildcraft-objects-1.0.7.557.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    CarpentersBlocks{v1.9.9} [Carpenter's Blocks](Carpenter's Blocks v1.9.9 - MC 1.6+.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    ChickenChunks{1.3.3.3} [ChickenChunks](ChickenChunks 1.3.3.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    CoFHCore{2.0.0.2} [CoFH Core](CoFHCore-2.0.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    CoFHLoot{2.0.0.2} [CoFH Loot](CoFHCore-2.0.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    CoFHMasquerade{2.0.0.2} [CoFH Masquerade](CoFHCore-2.0.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    CoFHSocial{2.0.0.2} [CoFH Social](CoFHCore-2.0.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    CoFHWorld{2.0.0.2} [CoFH World](CoFHCore-2.0.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    ForgeMultipart{1.0.0.227} [Forge Multipart](ForgeMultipart-universal-1.6.4-1.0.0.227.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    ThermalExpansion{3.0.0.2} [Thermal Expansion](ThermalExpansion-3.0.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    IC2{2.0.374-experimental} [IndustrialCraft 2](industrialcraft-2_2.0.374-experimental.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    CompactSolars{4.4.19.257} [Compact Solar Arrays](compactsolars-universal-1.6.4-4.4.19.257.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    eplus{1.16.5b} [Enchanting Plus](EnchantingPlus-1.16.5.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    EnderStorage{1.4.3.5} [EnderStorage](EnderStorage 1.4.3.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    ExtraUtilities{1.0.1} [Extra Utilities](extrautils-1.0.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    Forestry{2.3.1.1} [Forestry for Minecraft](forestry-A-2.3.1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    GregsLighting{1.9.1} [Greg's Lighting](GregsLighting-1.9.1-mc1.6.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    inventorytweaks{1.56} [Inventory Tweaks](InventoryTweaks-MC1.6.2-1.56-b77.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    IronChest{5.4.1.680} [Iron Chest](ironchest-universal-1.6.4-5.4.1.680.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    AdvancedSolarPanel{3.4.6} [Advanced Solar Panels](mod_AdvancedSolarPanels_3_4_6_IC_EXP.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    More Pistons{1.4.1 [Build Smeagol]} [More Pistons](More Pistons - 1.6.4 - 1.4.1 build Smeagol.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    MoreFurnaces{1.3.5} [More Furnaces](moreFurnaces-1.3.5-universal.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    NEIAddons{1.9.4.r51} [NEI Addons](neiaddons-1.6.2-1.9.4.r51.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    NEIAddons|AE{1.9.4.r51} [NEI Addons: Applied Energistics](neiaddons-1.6.2-1.9.4.r51.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    NEIAddons|CraftingTables{1.9.4.r51} [NEI Addons: Crafting Tables](neiaddons-1.6.2-1.9.4.r51.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    NEIAddons|ExtraBees{1.9.4.r51} [NEI Addons: Extra Bees](neiaddons-1.6.2-1.9.4.r51.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    NEIAddons|Forestry{1.9.4.r51} [NEI Addons: Forestry](neiaddons-1.6.2-1.9.4.r51.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    NEIAddons|MiscPeripherals{1.9.4.r51} [NEI Addons: Misc Peripherals](neiaddons-1.6.2-1.9.4.r51.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    NEIPlugins{1.1.0.6} [NEI Plugins](NEIPlugins-1.1.0.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    OpenBlocks{1.2.2} [OpenBlocks](OpenBlocks-1.2.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    ProjRed|Core{4.2.2.19} [ProjectRed](ProjectRedBase-1.6.4-4.2.2.19.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    ProjRed|Compatibility{1.0} [ProjRed|Compatibility](ProjectRedCompat-1.6.4-4.2.2.19.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    ProjRed|Integration{1.0} [ProjRed|Integration](ProjectRedIntegration-1.6.4-4.2.2.19.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    ProjRed|Transmission{1.0} [ProjRed|Transmission](ProjectRedIntegration-1.6.4-4.2.2.19.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    ProjRed|Illumination{1.0} [ProjRed|Illumination](ProjectRedLighting-1.6.4-4.2.2.19.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    ProjRed|Expansion{1.0} [ProjRed|Expansion](ProjectRedMechanical-1.6.4-4.2.2.19.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    ProjRed|Transportation{1.0} [ProjRed|Transportation](ProjectRedMechanical-1.6.4-4.2.2.19.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    ProjRed|Exploration{1.0} [ProjRed|Exploration](ProjectRedWorld-1.6.4-4.2.2.19.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    Railcraft{8.3.2.0} [Railcraft](Railcraft_1.6.4-8.3.2.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    mod_ReiMinimap{v3.4_01 [1.6.2]} [mod_ReiMinimap](Rei's Minimap 1.6.4.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    thorinmod{Version 1.0} [Thorin Mod](Thorin.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    Waila{1.4.4} [Waila](Waila_1.4.4b.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    WR-CBE|Core{1.4.0.6} [WR-CBE Core](WR-CBE 1.4.0.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    WR-CBE|Addons{1.4.0.6} [WR-CBE Addons](WR-CBE 1.4.0.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    WR-CBE|Logic{1.4.0.6} [WR-CBE Logic](WR-CBE 1.4.0.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    McMultipart{1.0.0.227} [Minecraft Multipart Plugin](ForgeMultipart-universal-1.6.4-1.0.0.227.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    ForgeMicroblock{1.0.0.227} [Forge Microblocks](ForgeMultipart-universal-1.6.4-1.0.0.227.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    Forestry : [Forestry] Warning: You have mods that change the behavior of Minecraft, ForgeModLoader, and/or Minecraft Forge to your client: 
Optifine
These may have caused this error, and may not be supported. Try reproducing the crash WITHOUT these mods, and report it then.
    Launched Version: 1.6.4-Forge9.11.1.965
    LWJGL: 2.9.0
    OpenGL: GeForce GT 750M/PCIe/SSE2 GL version 4.4.0, NVIDIA Corporation
    Is Modded: Definitely; Client brand changed to 'fml,forge'
    Type: Client (map_client.txt)
    Resource Pack: Soartex Fanver 1.6.x.zip
    Current Language: English (US)
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 3217 (180152 bytes; 0 MB) allocated, 1113 (62328 bytes; 0 MB) used

Please fix this!

**Comment by Kobata** [comment]
The mod is installed incorrectly or a configuration file is corrupt.

Try deleting your configuration files for InvTweaks.

**Comment by Spongman** [comment]
my client just started crashing with this exception. it was working fine before, and it started after i changed the key bindings.

https://paste.dimdev.org/tavibibado.mccrash

ok, this happens immediately if the client is connected to the server, and i re-bind the inventory sorting key to backslash. any other key is fine, backslash crashes it instantly.
