### ISSUE TITLE
Server/Client doesn't sync in 1.7

### ISSUE THREAD

**Issue by Cisien** [Inventory-Tweaks/inventory-tweaks#133]
Build 103
Minecraft 1.7
Forge 1024

When sorting a chest with the middle mouse button, the chest sorts on the client, however, the next update (moving an item/re-opening the chest) and the chest reverts back to it's pre-sorted state.

When a mining tool breaks (stone pick-axe), the tool is swapped out on the client, however, when using the tool, the block breaks and is immediately re-sync'd by the server. the tool also appears as a duplicate in the inventory. swapping the duplicate for the one inv. tweaks placed on the hot-bar returns the tool to functional. The tool remains in the inventory until it's thrown away, or until i relog.

**Comment by Kobata** [comment]
Try disabling the 'server assist' mode and see if that helps.

Forge might've broken part of that in between versions, I haven't been able to do much testing recently.
