### ISSUE TITLE
Newest Beta builds changes still compatible/safe for 1.6.4? 

### ISSUE THREAD

**Issue by Razorskills** [Inventory-Tweaks/inventory-tweaks#134]
Hello, I am just wondering which version you would use if you wanted to play 1.6.4? 
or is the 1.6.2 build 77 version the one to stick with?

I checked old issues and forum, didn't find anyone else with an answer.

**Comment by Kobata** [comment]
Not a bug.

Versions for each major MC verson (1.6, 1.7, etc.) are generally not compatible with other major minecraft versions.
