### ISSUE TITLE
"Invalid keywords found"

### ISSUE THREAD

**Issue by Boskosauce** [Inventory-Tweaks/inventory-tweaks#137]
Freshly generated single player world, freshly generated files for InventoryTweaks. Still does not work. Using the latest build of forge or even 1025. I did not add anything to the sorting rules file. I simply opened it and pressed ctrl s to save it, though nothing was added. Pressed R in-game, and that error pops up. No other mods were loaded at that time either.

![2014-02-17_19 37 26](https://f.cloud.github.com/assets/4279112/2213043/d8168a02-99ba-11e3-9b15-08246613af3e.png)

**Comment by Kobata** [comment]
Are you sure there's no message before that? There seems to be a strange case displaying that message when creating the default files fails, that matches the format in the picture better than the actual invalid keywords error.

**Comment by Boskosauce** [comment]
Yep. That's the only message that comes up. Pretty sure its also what is causing the sorting to not work properly.

Are there actually invalid keywords in the Tree file? I am unable to sort anything on my inventory as well, even when Rules are set. I'm not sure if that has anything to do with the Invalid Keywords error.

**Comment by Boskosauce** [comment]
Another problem. Opened up the Rules file, press ctrl S again, pressed R in-game. Gave that message. Opened up the Rules file again, pressed ctrl s again, press R in-game again, and it gave that message. This is with the 106 build. It's as if it thinks its missing, but it really isn't.
![2014-02-19_23 50 25](https://f.cloud.github.com/assets/4279112/2216148/d0a75884-9a03-11e3-9d1c-1b15694ef9c9.png)

**Comment by Kobata** [comment]
It's not having an issue with the rules file so messing with that shouldn't be doing anything.

Try deleting the InvTweaksTree.txt file and see if making it actually re-extract that helps.

**Comment by Boskosauce** [comment]
Deleted it. Let it regenerate a new one. Pressing R did not show the error at first, opened up the sorting file, did the usual ctrl s and pressed R again. Displayed the same error.

**Comment by Kobata** [comment]
Well, I have no idea then. Nothing you do to the other file should be changing that one. Try using a different text editor?

**Comment by Boskosauce** [comment]
Just wanted to let you know that I used another text editor, same problem.

**Comment by Kobata** [comment]
I found what was causing this there, it thought the tree file was out of date so kept trying to replace it.
