### ISSUE TITLE
1.7.2 dev build or sth?

### ISSUE THREAD

**Issue by Jacold** [Inventory-Tweaks/inventory-tweaks#139]
Hello. I use fan-made dev build for 1.7.2. Half of this mod works but keyboard shortcuts like space+click don't. I ask you Kobata for dev (may be unstable) build for 1.7.2 that works. I can't find any jenkins or sth like that. Build for 1.6.2 from your site don't work with 1.7.2 ofc. Can you help me? Minecraft without InvTweaks is horrible...

**Comment by Jacold** [comment]
Thank you.

**Comment by Kobata** [comment]
I know you're being sarcastic, but questions like that are more suited for the MCF thread, since it's easier for other people to help there and doesn't really require me specifically to look at.

Builds are at http://build.technicpack.net/job/Inventory-Tweaks/

**Comment by Jacold** [comment]
This is what I look for. Thanks a lot.
Yes, I'm being sarcastic, because thread were closed without any response. 

Regards, Jacold.
