### ISSUE TITLE
Tools break everytime

### ISSUE THREAD

**Issue by frmnch** [Inventory-Tweaks/inventory-tweaks#14]
Hey, i'm using Inventory Tweaks on a Server, that is running with McMMo.
There you can use e.g. "Super Breaker". With this skill, the tool gets damage very fast, but you can mine even faster for some seconds.
In this time my tools break everytime, even though i use "repair-friendly refill".
This refill is based on the file: InvTweaksConst, with the constant: AUTO_REFILL_DAMAGE_TRESHOLD = 5;

I would love it, if you could change this constant to a variable, so that everyone could decide when the tool will be moved out of the active position of the inventory.
(In my case i would choose a value between 10 and 20 i think..., others maybe use just 1 or something else)

**Comment by Kobata** [comment]
Seems simple enough, should be able to change it to a config thing quickly.

(Don't expect it to show up on the options screen though)

**Comment by ghost** [comment]
>(Don't expect it to show up on the options screen though)

Why not, @Kobata?
