### ISSUE TITLE
Pressing sort hotkey while renaming in anvil causes issues

### ISSUE THREAD

**Issue by 61352151511** [Inventory-Tweaks/inventory-tweaks#140]
When renaming something in the anvil and pressing the sort hotkey (Because what you're renaming it to has that letter in it) It puts the item right into your inventory and renames it to whatever is currently typed, which can be annoying because it takes your XP and only gets half named.

**Comment by Kobata** [comment]
This has not been an issue since MC 1.6, unless another mod is interfering the shortcut automatically disabled when a text box is focused.

See #15

**Comment by 61352151511** [comment]
Well I'm using the latest version of the mod 1.57-dev-106 on 1.7.2 with forge 1.7.2-Forge10.12.0.1031 Inventory Tweaks is the only mod I have installed and nothing else has the key set to "R" so you might want to check it out. This happens both on singleplayer and multiplayer for me, when the textbox is not focused in the anvil it does not take it out but when it is focused it does take it out so maybe it got reversed somehow?

I'll have a video to post when it's done uploading

**Comment by Kobata** [comment]
_sigh_ Of course the MCP guys screwed up the name along with half the other things. Just need to find out what the correct one is, these names shouldn't ever be changing.
