### ISSUE TITLE
Crashes with the two latest builds.

### ISSUE THREAD

**Issue by Boskosauce** [Inventory-Tweaks/inventory-tweaks#144]
Using Magic Launcher. Nothing else is loaded besides the InventoryTweaks-1.57-dev-108.jar file, using forge 1034.

http://pastebin.com/p3aD5buG Crash log.

Any idea?

**Comment by Kobata** [comment]
Don't use MagicLauncher or learn how to correctly install mods in it.

**Comment by Boskosauce** [comment]
Wow. You're very helpful. Heh. While disabling the Mod from the Mods list and adding the jar to the Mods folder, it seems to have worked. Previous builds worked fine without having to do that.
