### ISSUE TITLE
Server crashed on world load

### ISSUE THREAD

**Issue by viliml** [Inventory-Tweaks/inventory-tweaks#145]
It fails with [this log output](http://pastebin.com/DSg9N69L) in the dev console, and a message "A fatal error has occured, this connection is termianted" on the screen, and  then it takes me back to the server choosing screen.

**Comment by Kobata** [comment]
Try deleting your config files and ensuring the mod is correctly installed.

**Comment by AshZification** [comment]
I received the same failure to load with this log: http://pastebin.com/SGEHiHKP
Upon removing Inventory tweaks, this log: http://pastebin.com/6pV2eRiy

This is on loading from single player world selection, still sends me back to the server selection screen. 

Deleting the config/mod and replacing it did not work. 
Forge version: 10.12.0.1039
InventoryTweaks-1.57-dev-110

Edit: I am using 24 mods total in this instance. With just Forge and Inventory Tweaks, I can load the world and play on it. I will be adding each mod individually to pin point the conflict now.

Edit2: Results of individual mod rule-out test: http://pastebin.com/WZvR1Z3s
BoP is the conflict at present. 

Edit3: Hadn't realized there was a 112 build, same result (with all 24 mods loading): http://pastebin.com/aiaJcdGU

Edit4: reported it to BoP: http://www.minecraftforge.net/forum/index.php/topic,17204.0.html
I don't know what's actually causing the problem, so I wanted to make sure I told them too.
