### ISSUE TITLE
Move one item doesn't work on brewing stands

### ISSUE THREAD

**Issue by 61352151511** [Inventory-Tweaks/inventory-tweaks#149]
Basically the title, I can't control click items into a brewing stand, instead it just moves it from the inventory to the hotbar or from hotbar into the inventory.

**Comment by Kobata** [comment]
26b718333425e97e03b6730a1b7d957cf866f3f9 fixes one part of this, but the shortcuts only directly support automatically targeting to chests -- the same thing will happen on a furnace or crafting table, etc.

You can use the ctrl+up/down shortcuts to move to the section 'above/below' where the item currently is however.
