### ISSUE TITLE
Iron Chests not supported in 1.7.2

### ISSUE THREAD

**Issue by 61352151511** [Inventory-Tweaks/inventory-tweaks#151]
You can't sort iron chests anymore like you could in 1.6.4

**Comment by Kobata** [comment]
Since cpw isn't developing mods anymore, not something I'm likely to look at any time soon.

**Comment by 61352151511** [comment]
Well iron chests is a mod that's out for 1.7.2, I'm not sure if it's the same developer but it's the same page as the old versions and it's annoying not to be able to sort the chests

http://files.minecraftforge.net/IronChests2/

**Comment by eyamaz** [comment]
progwml6 has taken over ironchest

**Comment by progwml6** [comment]
i can get you any info if needed
