### ISSUE TITLE
[1.57] Crash while picking up a iron shovel

### ISSUE THREAD

**Issue by BrandonStaab** [Inventory-Tweaks/inventory-tweaks#152]
when i pick up a iron shovel it sometimes crashes the game

http://pastebin.com/a0Lshf6g
http://pastebin.com/fKpbdkJu
http://pastebin.com/vexZnsMM

**Comment by Kobata** [comment]
inventorytweaks{1.57-dev-110} 

Update your jar, that's not the release version.
