### ISSUE TITLE
Heavy and non-stop config file access upon picking up block in 1.6.4

### ISSUE THREAD

**Issue by Aedda** [Inventory-Tweaks/inventory-tweaks#158]
I noticed my hard drive going a bit nuts earlier and after closing most apps except for Minecraft I decided to start Process Monitor from Sysinternals to see what was going on and was surprised to find almost all of the disk activity coming from Java.exe, accessing the Inventory Tweaks config files.

After some testing I figured out that it is triggered when a block is picked up from the ground. Tested in Vanilla using only Forge 965 and Inventory Tweaks 1.56-b77.

Once triggered the disk will never stop being accessed, even when paused. Logging out stops the process until logging in again when it resumes. Restarting the client stops it until the next block is picked up.

This behavior was not triggered in creative using pick-block nor when moving items into the inventory from a chest.

I've attached a screen shot of Process Monitors output.

![invtweaksdiskaccess](https://f.cloud.github.com/assets/3745280/2492758/abc013b6-b250-11e3-9a3f-38d9a34f0612.png)

**Comment by Kobata** [comment]
Checking the modified times of files is expected behavior.

It looks like it's getting stuck thinking you always have a picked up item though (I can see a couple possibilities of why), but any fixes will be for MC 1.7 at this point.
