### ISSUE TITLE
Mod doesn't work on a multiplayer server. 

### ISSUE THREAD

**Issue by Matthewlt** [Inventory-Tweaks/inventory-tweaks#161]
Every time i try to sort my inventory with mouse3 or R, it tries to sort it but everything reverts after 0.5s and some items disappear, once i close my inventory i drop those disappeared items. Below are some pictures of what happens

Look from bottom.

This is how it looks after closing inventory, after i press R
![after closing inventory](https://cloud.githubusercontent.com/assets/7315732/2720737/867ca02a-c573-11e3-9646-2c22745232a4.png)
1s after pressing R
![1s after presing r](https://cloud.githubusercontent.com/assets/7315732/2720736/8679cde6-c573-11e3-8eb5-76c0a5c3b56c.png)
A moment after pressing R
![a moment after presing r](https://cloud.githubusercontent.com/assets/7315732/2720739/867fabc6-c573-11e3-90c6-61fd2b2d304e.png)
Before pressing R
![before pressing r](https://cloud.githubusercontent.com/assets/7315732/2720738/867f6418-c573-11e3-8d86-4c2af6930e1c.png)

**Comment by Kobata** [comment]
See #155, etc. Issues with servers cannot be resolved in the client-side mod portion.
