### ISSUE TITLE
Client crashes when sorting chests with certain items [bug]

### ISSUE THREAD

**Issue by antimuffin** [Inventory-Tweaks/inventory-tweaks#162]
Using Direwolf20 1.6.4 1.0.21 modpack, which Inventory Tweaks version 1.56.

This is likely a mod compatibility issue, but I've observed it with items from several different mods.

What happens is when sorting a chest containing lots of different TYPES of the same item (Thaumcraft mana beans, Mystcraft pages), the client will freeze and crash. This is reproducible for me with a chest containing 30+ types of those items. It has usually happened with an Obsidian Chest from the Iron Chest mod (version 5.4.1 build 702), but I remember in a previous version of the DW20 pack it happened with vanilla chests as well that were full of Mystcraft pages.

**Comment by Kobata** [comment]
This sounds a lot like #121 etc, please try to test the latest version for bug reports.
