### ISSUE TITLE
Game Crashes When Loading Game (Other Compatible Mods Installed)

### ISSUE THREAD

**Issue by xboxer214** [Inventory-Tweaks/inventory-tweaks#163]
So when i try to open minecraft it crashes right upon start, it is the newest version of Inventory Tweaks and the newest version of 1.6.4 forge, i know its not because the other mods i have installed, i tested it with a clean minecraft but it still crashes

**Comment by Kobata** [comment]
The newest version of Inventory Tweaks is for Minecraft 1.7

**Comment by xboxer214** [comment]
I mean the most resent version in 1.6.4
