### ISSUE TITLE
Crash with Inventory Tweaks

### ISSUE THREAD

**Issue by iamceph** [Inventory-Tweaks/inventory-tweaks#165]
Hello, i updated forge to forge-1.7.2-10.12.1.1073 and Inv. Tweaks to InventoryTweaks-1.58-dev-120 from build.technicpack.net
Here is the crash-report:
http://pastebin.com/R6HS77ip

**Comment by Kobata** [comment]
Please read your crash reports before posting them anywhere, it should be obvious where you should go with that one once you do.
