### ISSUE TITLE
Mod sorting

### ISSUE THREAD

**Issue by phoebustam** [Inventory-Tweaks/inventory-tweaks#167]
I'm playing with the advanced genetics mod and I would like to sort out some items exclusively in this mod.  After 1.7, I found that the item tree doesn't use numerical ID anymore, and I have no idea how to find the ID of the item I would like to sort in the mod, any help?

**Comment by Kobata** [comment]
Unless TMI/NEI work and have been updated to show it, I don't know of any way currently to get mod item/block Ids except asking the author of the mod. (They should probably be documenting these because they are the same ones you need for reference in commands now too)

**Comment by Lunatrius** [comment]
If it's not too much trouble you can install bspkrsCore. It will dump all IDs into UniqueNames.txt.

**Comment by phoebustam** [comment]
may I ask what is the point to use text IDs instead of numerical IDs?

**Comment by Kobata** [comment]
The numerical ones change to match a loaded word or joined server now so
they are not consistent.
