### ISSUE TITLE
Inventory Tweaks 1.56 Sorting problem with Direwolf20 Mod Pack

### ISSUE THREAD

**Issue by thefarq** [Inventory-Tweaks/inventory-tweaks#168]
This version of inventory tweaks is the only version that will work with the Direwolf20 Mod Pack. When sorting, it sorts, but in an awkward formation that doesn't match what I have previously seen with this mod.

Attached I have an image of what the sorting looks like in this chest.
![2014-05-20_01 11 28](https://cloud.githubusercontent.com/assets/7639654/3023437/d9dbd312-dfe5-11e3-81c3-03c01a4cc9f7.png)

I have tested other compatible versions of Inventory Tweaks, and they don't load.

Other mod packs, offered by the Feed the Beast launcher, that have Inventory Tweaks, sort chests properly, even in a larger sized chest.

Thank you!

Edit: I have found that if you add many different items, at a certain point the sorting function works correctly.

**Comment by Kobata** [comment]
Honestly, I can't say anything unless you've tried with the latest versions of every mod installed, because it may be something that has been fixed since whatever version was in the modpack.
