### ISSUE TITLE
1.6.4 Ticking memory connection [Crash after switching Dimension]

### ISSUE THREAD

**Issue by ghost** [Inventory-Tweaks/inventory-tweaks#172]
Crashlog: http://pastebin.com/8E6LqP5F

I don't know if you even wanna see this since its 1.6.4, i am sorry if so
I never encountered this problem before..so it may be a one time thing
I was going from the nether to the overworld, put some netherrack into a chest, sorted my inventory (via middle mouse button) and then crashed.

**Comment by Kobata** [comment]
There are a bunch of these on the OpenEye crash list, along with a bunch of the same thing triggered by other mods and even apparently just plain Minecraft. It seems to just be a somewhat uncommon general issue that's not specific to Inventory Tweaks.

**Comment by Kobata** [comment]
For example, http://openeye.openmods.info/crashes/214576daf7b3ca9d61d35dd94e5795a3 doesn't have Inventory Tweaks installed.

**Comment by ghost** [comment]
Ah, thanks. One thing less to worry about :)
