### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by rdellison** [Inventory-Tweaks/inventory-tweaks#174]
---- Minecraft Crash Report ----
// Quite honestly, I wouldn't worry myself about that.

Time: 5/29/14 8:42 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
    at invtweaks.InvTweaks.handleAutoRefill(InvTweaks.java:604)
    at invtweaks.InvTweaks.onTickInGame(InvTweaks.java:122)
    at invtweaks.forge.ForgeClientTick.onTick(ForgeClientTick.java:24)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_269_ForgeClientTick_onTick_ClientTickEvent.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:51)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:122)
    at cpw.mods.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:329)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2014)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:916)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:835)
    at net.minecraft.client.main.Main.main(SourceFile:103)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:134)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at invtweaks.InvTweaks.handleAutoRefill(InvTweaks.java:604)
    at invtweaks.InvTweaks.onTickInGame(InvTweaks.java:122)
    at invtweaks.forge.ForgeClientTick.onTick(ForgeClientTick.java:24)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_269_ForgeClientTick_onTick_ClientTickEvent.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:51)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:122)
    at cpw.mods.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:329)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityClientPlayerMP['rdellison'/233, l='MpServer', x=63.33, y=78.62, z=241.68]]
    Chunk stats: MultiplayerChunkCache: 317, 317
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: World: (72,64,-28), Chunk: (at 8,4,4 in 4,-2; contains blocks 64,0,-32 to 79,255,-17), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
    Level time: 2427323 game time, 103337 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
    Forced entities: 97 total; [EntityZombie['Zombie'/121352, l='MpServer', x=47.44, y=-24.62, z=-4.77], EntitySkeleton['Skeleton'/533221, l='MpServer', x=46.50, y=47.00, z=273.50], EntityPech['entity.Pech.1.name'/501583, l='MpServer', x=85.50, y=16.00, z=207.50], EntityZombie['Zombie'/521423, l='MpServer', x=11.50, y=58.00, z=283.50], EntityCreeper['Creeper'/528815, l='MpServer', x=51.50, y=35.00, z=241.50], EntityBat['Bat'/526387, l='MpServer', x=87.77, y=12.80, z=241.82], EntityChicken['Chicken'/452051, l='MpServer', x=124.53, y=70.00, z=320.56], EntityZombie['Zombie'/532337, l='MpServer', x=111.50, y=24.00, z=286.50], EntityCreeper['Creeper'/518411, l='MpServer', x=61.50, y=31.00, z=241.50], EntityZombie['Zombie'/532336, l='MpServer', x=112.50, y=24.00, z=286.50], EntityZombie['Zombie'/518410, l='MpServer', x=59.50, y=31.00, z=240.50], EntityZombie['Zombie'/532338, l='MpServer', x=113.50, y=24.00, z=285.50], EntityCreeper['Creeper'/518412, l='MpServer', x=55.00, y=34.00, z=236.59], EntityZombie['Zombie'/518407, l='MpServer', x=61.50, y=31.00, z=240.50], EntityBat['Bat'/524490, l='MpServer', x=121.38, y=36.78, z=302.53], EntitySkeleton['Skeleton'/531285, l='MpServer', x=-7.50, y=48.00, z=222.50], EntityBat['Bat'/527912, l='MpServer', x=31.97, y=48.00, z=255.50], EntityCreeper['Creeper'/527889, l='MpServer', x=123.00, y=37.00, z=303.47], EntityZombie['Zombie'/527890, l='MpServer', x=121.97, y=29.00, z=294.47], EntityWaypointContainer['unknown'/584, l='MpServer', x=0.00, y=0.00, z=0.00], EntityChicken['Chicken'/127, l='MpServer', x=36.53, y=71.00, z=173.38], EntitySquid['Squid'/518583, l='MpServer', x=7.50, y=57.00, z=234.50], EntitySquid['Squid'/518582, l='MpServer', x=-2.53, y=56.28, z=235.28], EntitySquid['Squid'/518589, l='MpServer', x=-1.03, y=57.19, z=237.06], EntityItem['item.tile.blockCustomPlant.0'/508279, l='MpServer', x=71.28, y=77.13, z=177.81], EntityItem['item.item.barley.seed'/454636, l='MpServer', x=77.34, y=77.13, z=194.31], EntityCreeper['Creeper'/525895, l='MpServer', x=10.50, y=58.00, z=283.50], EntitySheep['Sheep'/162, l='MpServer', x=116.09, y=66.00, z=161.09], EntitySlime['Slime'/455169, l='MpServer', x=36.34, y=34.68, z=235.31], EntityZombie['Zombie'/534036, l='MpServer', x=140.50, y=25.00, z=296.50], EntityZombie['Zombie'/24017, l='MpServer', x=9.72, y=-45.62, z=11.36], EntityZombie['Zombie'/534034, l='MpServer', x=141.50, y=25.00, z=296.50], EntityZombie['Zombie'/534035, l='MpServer', x=140.50, y=25.00, z=297.50], EntityCreeper['Creeper'/496331, l='MpServer', x=112.50, y=27.00, z=320.50], EntitySlime['Slime'/511367, l='MpServer', x=64.38, y=25.00, z=289.63], EntityCreeper['Creeper'/528057, l='MpServer', x=139.50, y=16.00, z=272.50], EntityCreeper['Creeper'/526546, l='MpServer', x=133.50, y=21.00, z=273.50], EntitySkeleton['Skeleton'/528054, l='MpServer', x=129.50, y=45.04, z=198.66], EntitySkeleton['Skeleton'/528053, l='MpServer', x=128.47, y=46.00, z=197.94], EntitySkeleton['Skeleton'/512567, l='MpServer', x=118.50, y=38.00, z=300.50], EntitySkeleton['Skeleton'/533024, l='MpServer', x=64.50, y=16.00, z=239.50], EntityZombie['Zombie'/524372, l='MpServer', x=57.50, y=22.00, z=203.50], EntityItem['item.item.egg'/487084, l='MpServer', x=3.47, y=71.13, z=207.81], EntitySkeleton['Skeleton'/533023, l='MpServer', x=63.50, y=16.00, z=238.50], EntitySquid['Squid'/518599, l='MpServer', x=5.78, y=57.31, z=237.84], EntitySquid['Squid'/518595, l='MpServer', x=20.31, y=59.25, z=230.78], EntitySquid['Squid'/518593, l='MpServer', x=14.34, y=58.97, z=230.38], EntitySkeleton['Skeleton'/524400, l='MpServer', x=128.50, y=19.00, z=251.50], EntitySkeleton['Skeleton'/524401, l='MpServer', x=127.50, y=19.00, z=251.50], EntityChicken['Chicken'/278, l='MpServer', x=-13.56, y=68.00, z=196.47], EntityChicken['Chicken'/283, l='MpServer', x=-11.84, y=76.49, z=310.56], EntityChicken['Chicken'/282, l='MpServer', x=-11.44, y=68.00, z=274.38], EntitySheep['Sheep'/281, l='MpServer', x=-9.91, y=68.00, z=265.06], EntityBat['Bat'/523612, l='MpServer', x=119.72, y=26.85, z=283.69], EntitySheep['Sheep'/286, l='MpServer', x=15.03, y=69.00, z=197.09], EntityChicken['Chicken'/271, l='MpServer', x=-16.56, y=70.00, z=288.53], EntityArrow['arrow'/306, l='MpServer', x=50.09, y=23.98, z=276.66], EntitySheep['Sheep'/308, l='MpServer', x=88.84, y=72.00, z=177.47], EntitySheep['Sheep'/317, l='MpServer', x=105.66, y=64.00, z=171.38], EntitySpider['Spider'/512976, l='MpServer', x=57.22, y=32.00, z=236.72], EntityChicken['Chicken'/288, l='MpServer', x=3.59, y=71.00, z=205.66], EntitySheep['Sheep'/291, l='MpServer', x=33.06, y=70.00, z=179.97], EntityBat['Bat'/521105, l='MpServer', x=49.34, y=39.10, z=251.28], EntityWisp['Wisp'/388647, l='MpServer', x=66.03, y=33.97, z=250.72], EntityChicken['Chicken'/340, l='MpServer', x=133.41, y=69.00, z=298.44], EntityCreeper['Creeper'/522153, l='MpServer', x=137.00, y=18.00, z=255.50], EntityChicken['Chicken'/339, l='MpServer', x=129.63, y=65.00, z=298.44], EntityCreeper['Creeper'/522152, l='MpServer', x=128.50, y=17.00, z=255.50], EntityChicken['Chicken'/337, l='MpServer', x=138.41, y=64.00, z=272.56], EntityZombie['Zombie'/522149, l='MpServer', x=127.50, y=17.00, z=253.50], EntityZombie['Zombie'/522150, l='MpServer', x=129.50, y=17.00, z=253.50], EntitySkeleton['Skeleton'/525308, l='MpServer', x=12.50, y=53.00, z=220.50], EntityChicken['Chicken'/322, l='MpServer', x=121.56, y=75.00, z=187.38], EntityChicken['Chicken'/323, l='MpServer', x=118.53, y=80.39, z=312.84], EntityBat['Bat'/490101, l='MpServer', x=17.61, y=52.84, z=220.58], EntityClientPlayerMP['rdellison'/233, l='MpServer', x=63.33, y=78.62, z=241.68], EntityChicken['Chicken'/335, l='MpServer', x=138.53, y=64.00, z=269.47], EntityChicken['Chicken'/332, l='MpServer', x=138.53, y=64.00, z=253.53], EntityChicken['Chicken'/330, l='MpServer', x=129.47, y=70.00, z=237.53], EntityChicken['Chicken'/331, l='MpServer', x=141.44, y=69.00, z=235.44], EntityCreeper['Creeper'/523572, l='MpServer', x=1.50, y=59.00, z=206.97], EntityBat['Bat'/522619, l='MpServer', x=13.76, y=52.88, z=216.97], EntityZombie['Zombie'/505128, l='MpServer', x=95.50, y=43.00, z=305.50], EntityCreeper['Creeper'/521658, l='MpServer', x=128.50, y=54.00, z=273.50], EntitySpider['Spider'/520463, l='MpServer', x=-5.91, y=51.00, z=232.50], EntitySpider['Spider'/528417, l='MpServer', x=49.50, y=35.00, z=241.50], EntityBat['Bat'/529996, l='MpServer', x=47.28, y=38.89, z=245.53], EntityEnderman['Enderman'/528898, l='MpServer', x=117.50, y=24.00, z=202.50], EntityItem['item.item.barley.seed'/453870, l='MpServer', x=71.53, y=77.13, z=194.75], EntityZombie['Zombie'/528379, l='MpServer', x=-6.50, y=48.00, z=219.50], EntityZombie['Zombie'/520466, l='MpServer', x=-7.25, y=51.00, z=226.88], EntityZombie['Zombie'/520465, l='MpServer', x=-4.50, y=51.00, z=234.50], EntityCreeper['Creeper'/516660, l='MpServer', x=4.06, y=62.00, z=206.41], EntityCreeper['Creeper'/526765, l='MpServer', x=0.97, y=56.00, z=211.66], EntityZombie['Zombie'/520991, l='MpServer', x=55.50, y=21.00, z=201.78], EntityCreeper['Creeper'/502370, l='MpServer', x=18.66, y=58.00, z=200.50], EntitySkeleton['Skeleton'/495225, l='MpServer', x=-8.50, y=48.00, z=221.50]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:368)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2382)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:864)
    at net.minecraft.client.main.Main.main(SourceFile:103)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:134)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.7.2
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.7.0_11, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 673917616 bytes (642 MB) / 2132344832 bytes (2033 MB) up to 3817799680 bytes (3640 MB)
    JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms2048M -Xmx4096M -XX:MaxPermSize=256m
    AABB Pool Size: 1922 (107632 bytes; 0 MB) allocated, 1588 (88928 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 98
    FML: MCP v9.03 FML v7.2.196.1082 Minecraft Forge 10.12.1.1082 42 mods loaded, 42 mods active
    mcp{9.03} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    FML{7.2.196.1082} [Forge Mod Loader](forge-1.7.2-10.12.1.1082.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Forge{10.12.1.1082} [Minecraft Forge](forge-1.7.2-10.12.1.1082.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    AppliedEnergistics2-Core{rv0-beta-4} [AppliedEnergistics2 Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CodeChickenCore{1.0.0} [CodeChicken Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    NotEnoughItems{1.0.1} [Not Enough Items](NotEnoughItems-1.7.2-1.0.1-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    TConstruct-Preloader{0.1.1} [Tinkers Corestruct](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    battlegear2{1.0.5.5} [Mine & Blade Battlegear 2 - Bullseye](1.7.2-MB_Battlegear2-Bullseye-1.0.5.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Core{6.0.15} [BuildCraft](buildcraft-6.0.15.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    appliedenergistics2{rv0-beta-4} [Applied Energistics 2](appliedenergistics2-rv0-beta-4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Backpack{2.0.0-pre1} [Backpack](backpack-2.0.0-pre1-1.7.x.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BiblioCraft{1.7.0} [BiblioCraft](BiblioCraft[1.7.0][MC1.7.2].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Mantle{1.7.2-132.45b0b50} [Mantle](Mantle-1.7.2-0.2.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Natura{2.2.0} [Natura](natura-1.7.2-2.2.0a3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BiomesOPlenty{2.0.0} [Biomes O' Plenty](BiomesOPlenty-1.7.2-2.0.0.840-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Builders{6.0.15} [BC Builders](buildcraft-6.0.15.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Energy{6.0.15} [BC Energy](buildcraft-6.0.15.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Factory{6.0.15} [BC Factory](buildcraft-6.0.15.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Transport{6.0.15} [BC Transport](buildcraft-6.0.15.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Silicon{6.0.15} [BC Silicon](buildcraft-6.0.15.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    DLDungeonsJBG{1.2.10} [Doomlike Dungeons](DoomlikeDungeons-1.2.10-MC1.7.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Enchiridion{1.0a} [Enchiridion](Enchiridion-1.7.2-1.0b.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Waila{1.5.2_1.7.2} [Waila](Waila-1.5.2a_1.7.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    extracells{2.0.3} [ExtraCells](ExtraCells-2.0.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ForgeMultipart{1.1.0.276} [Forge Multipart](ForgeMultipart-1.7.2-1.1.0.276-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Baubles{1.0.0.14} [Baubles](Baubles-1.7.2-1.0.0.14.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ExtraUtilities{1.1.0-prerelease-6} [Extra Utilities](extrautilities-1.1.0-prerelease-6.jar.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    McMultipart{1.1.0.276} [Minecraft Multipart Plugin](ForgeMultipart-1.7.2-1.1.0.276-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    HopperDuctMod{1.3} [Hopper Ducts](hopperductmod-1.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    inventorytweaks{1.57-116} [Inventory Tweaks](InventoryTweaks-1.57-116.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    IronChest{6.0.14.719} [Iron Chest](ironchest-1.7.2-6.0.14.719-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    JABBA{1.1.3} [Jabba](Jabba_1.1.3_1.7.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Mystcraft{@VERSION@} [Mystcraft](mystcraft-1.7.2-0.10.14.00.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    harvestcraft{1.7.2c} [Pam's HarvestCraft](Pam's HarvestCraft 1.7.2c.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Thaumcraft{4.1.1.12} [Thaumcraft](Thaumcraft-1.7.2-4.1.1.12.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Railcraft{9.0.0.0} [Railcraft](Railcraft_1.7.2-9.0.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    TConstruct{1.7.2-1.6.0.jenkins478} [Tinkers' Construct](TConstruct-1.7.2-1.6.0.a14.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    TMechworks{1.7.2-60.0ab3ef0} [Tinkers' Mechworks](TMechworks-1.7.2-0.2.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    TwilightForest{2.0.3} [The Twilight Forest](twilightforest-1.7.2-2.0.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    taverns{2.2.1-0} [Village Taverns](VillageTaverns-2.2.1-0.23.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    voxelmap{1.7.2} [VoxelMap](voxelmap-1.7.2-1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ForgeMicroblock{1.1.0.276} [Forge Microblocks](ForgeMultipart-1.7.2-1.1.0.276-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    AE2 Version: beta rv0-beta-4 for Forge 10.12.0.1024
    Mantle Environment: Environment healthy.
    TConstruct Environment: Environment healthy.
    AE2 Integration: RotaryCraft:OFF, IC2:OFF, RC:ON, BC:ON, MJ5:ON, MJ6:OFF, RF:ON, InvTweaks:OFF, MFR:OFF, DSU:ON, FZ:OFF, Waila:ON, CLApi:OFF, RB:OFF, InvTweaks:OFF, NEI:ON, CraftGuide:OFF, FMP:ON
    Launched Version: 1.7.2-Forge10.12.1.1082
    LWJGL: 2.9.0
    OpenGL: ATI Radeon HD 5570 GL version 4.2.12002 Compatibility Profile Context 9.12.0.0, ATI Technologies Inc.
    Is Modded: Definitely; Client brand changed to 'fml,forge'
    Type: Client (map_client.txt)
    Resource Packs: []
    Current Language: English (US)
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 1865 (104440 bytes; 0 MB) allocated, 882 (49392 bytes; 0 MB) used
    Anisotropic Filtering: Off (1)

**Comment by Kobata** [comment]
c64e1b8c632edffc4bcc689ccb03c18eba4efb95 ?

**Comment by rdellison** [comment]
quite likely ­ I did have bowls and Natura berry medley, can¹t remember
exactly what I was doing when the crash happened.

From:  Kobata notifications@github.com
Reply-To:  Kobata/inventory-tweaks
<reply+i-34607647-7bfaa04e6017636dd4a7c0c26819dce52c5aa848-3753284@reply.git
hub.com>
Date:  Thursday, May 29, 2014 at 11:53 PM
To:  Kobata/inventory-tweaks inventory-tweaks@noreply.github.com
Cc:  Rich Ellison rdellison.01754@gmail.com
Subject:  Re: [inventory-tweaks] NullPointerException (#174)

c64e1b8 
<https://github.com/Kobata/inventory-tweaks/commit/c64e1b8c632edffc4bcc689cc
b03c18eba4efb95>  ?

‹
Reply to this email directly or view it on GitHub
<https://github.com/Kobata/inventory-tweaks/issues/174#issuecomment-44612773

> .
