### ISSUE TITLE
InvTweaks NPE on World Load

### ISSUE THREAD

**Issue by RoundTab1er** [Inventory-Tweaks/inventory-tweaks#175]
Using Forge 1.6.4-Forge9.11.0.883, Minecraft 1.6.4, and  InventoryTweaks-MC1.6.2-1.56-b77, I get an NPE on world load. 
Pastebin here: http://pastebin.com/HyefCMvs. 

Also got the NPE using forge 1.6.4-forge.9.11.0.965.

**Comment by Kobata** [comment]
Either your configuration files are messed up and failed to load, or see #153

1.6.4 versions don't handle this situation very well
