### ISSUE TITLE
[Solved] No sorting buttons in BetterStorage's reinforced chests

### ISSUE THREAD

**Issue by Jofkos** [Inventory-Tweaks/inventory-tweaks#176]
Is it possible to add these buttons? (or can i add them manually?)
I'm playing with InventoryTweaks-MC1.6.2-1.56-b77, in the Attack of the B-Team Technic-Modpack. The BetterStorage version is 1.6.4-0.8.0.45.

**Comment by Kobata** [comment]
http://inventory-tweaks.readthedocs.org/en/latest/#adding-configured-compatibility-info

**Comment by Jofkos** [comment]
Sorry, i didn't see that yet.
Thank you ;)

**Comment by Jofkos** [comment]
If someone has the same issue, here's my InvTweaksCompatibility.xml:
http://pastebin.com/yDX3PyvV

**Comment by Ruleofnine** [comment]
I made the file and pasted that in and it still didn't work. I've been trying to get this to work all day now, is there something i'm doing wrong? if you can help i would very much appreciate it.

**Comment by Jofkos** [comment]
@Ruleofnine do you pasted it in an plain-text-xml-file in the config Folder inside your minecraft folder? Is there a stacktrace or is it just not working?

**Comment by Ruleofnine** [comment]
There is no issue loading the game or anything, I downloaded the txt file on your pastebin and put it in the minecraft config folder. could it be the wrong type of text? and is the file name "config/invtweakscompatabilty.xml" or is it "invtweakscompatabilty.xm" and the /config on the front means the location? thanks for your response I wasn't expecting one.
"

**Comment by Jofkos** [comment]
The exact name is important. It must be 'InvTweaksCompatibility.xml' (case-sensitive, without .txt). config is the folder, yes. Just name it to InvTweaksCompatibility.xml and it should work ;)

**Comment by Ruleofnine** [comment]
So I re-got it from your thing, i renamed it  InvTweaksCompatibility.xml and put it in the configs section. It didn't work, then i redid it and took off the  top part of the document above the <root> and still nothing, could it be the the type of minecraft im playing? im playing magic world 2 on the FTB launcher.

**Comment by Ruleofnine** [comment]
here are some screen shots, idk if they will help. maybe im doing something wrong.
![screenshot 2](https://cloud.githubusercontent.com/assets/8292229/3727239/ec44e5c4-169b-11e4-8cd3-9e4b0d6334fc.png)
that is the file.
![screenshot 3](https://cloud.githubusercontent.com/assets/8292229/3727254/0d1926c0-169c-11e4-90f2-3a58ae14657c.png)
there is the file, and next to it you can see it is in the config folder.
![screenshot 6](https://cloud.githubusercontent.com/assets/8292229/3727379/e8a69966-169c-11e4-9a9d-1f85c76e546c.png)
Lastly i just reloaded it to check and this is what i get.

**Comment by Jofkos** [comment]
Send me a screen of the file properties (Rightclick properties)

**Comment by Ruleofnine** [comment]
![screenshot 7](https://cloud.githubusercontent.com/assets/8292229/3727477/1e16c8e0-169e-11e4-9169-e353faa89242.png)
![screenshot 8](https://cloud.githubusercontent.com/assets/8292229/3727490/43a58d62-169e-11e4-8549-ef2fef9b11e7.png)
on the second one it says .txt next to it. Not sure if thats the issue.

**Comment by Jofkos** [comment]
The name of your file ends with .txt, but the ending is hidden. Follow this tutorial: http://www.mediacollege.com/microsoft/windows/extension-change.html and remove the .txt thing.

**Comment by Ruleofnine** [comment]
okay i got it to work,thanks a lot that is really helpful!

**Comment by Jofkos** [comment]
You're welcome ;)
