### ISSUE TITLE
Missing sort buttons on normal chests

### ISSUE THREAD

**Issue by Dlorii** [Inventory-Tweaks/inventory-tweaks#180]
Noticed that the sort buttons dont show up on normal chests.
They work fine on ironchests but are completly missing on vanilla chests.

Running build 1.58-dev-132 & Forge 10.12.2.1133

A new change or just a bug?

![bug1](https://cloud.githubusercontent.com/assets/5676674/3370883/6385c222-fb97-11e3-8728-a49ddc5dd0c5.png)

**Comment by Kobata** [comment]
Probably just something overlooked, but right now I'm trying to see if anything major needs fixed with the 1.7.10-pre4 testing versions. (If I can get them to even work)
