### ISSUE TITLE
Not obeying "enableShortcuts" setting.

### ISSUE THREAD

**Issue by ghost** [Inventory-Tweaks/inventory-tweaks#181]
Even when you disable shortcuts it still sorts the inventory when you press "R". Only seems to be bugged in version 1.58-dev-132.

1.58-dev-132
Forge: 1133

*Edit: spelling

**Comment by Kobata** [comment]
That setting disables the on-click shortcuts (space+click, ctrl+click, up+click, etc), not the sorting hotkey
