### ISSUE TITLE
Shortcut for moving all items of same type does not work

### ISSUE THREAD

**Issue by azatoth** [Inventory-Tweaks/inventory-tweaks#190]
using 1.57-116, trying to issue Ctrl-Shift click to move all items of the same type does not work. Other shortcuts seems to work, so it could be the "+" part that is the issue.

**Comment by Kobata** [comment]
It looks like the multi-key checks work fine.

Right now I'm thinking it's the shift part that's an issue -- it looks like MC moves the item via its normal things before the shortcuts can check.
