### ISSUE TITLE
New F3+H Name ID's are really annoying to look at

### ISSUE THREAD

**Issue by 61352151511** [Inventory-Tweaks/inventory-tweaks#191]
Having the name ID's show in the same spot as the durability isn't the best idea, F3+H is used to show stats like durability of a pickaxe/sword and modded items such as a sapphire pickaxe from project red take up your whole screen with
"Sapphire Pickaxe (#4770) [ProjRed:Exploration:projectred.exploration.pickaxesapphire] 4770"
A config option for this would be nice if possible because I like seeing the durability of my tools but not an entire unlocalized name

**Comment by Kobata** [comment]
Mojang's doing a very similar thing for 1.8, so blame Project Red for choosing such unnecessarily long names. (From the looks of it their names are likely to confuse the hell out of other mods anyway -- there should only be one : in them, and most of the stuff in MC that deals with similarly formatted things splits at the first one)
