### ISSUE TITLE
Sorting in Thermal Expansion 4 strongboxes

### ISSUE THREAD

**Issue by bochen415** [Inventory-Tweaks/inventory-tweaks#195]
Sorting on TE4 strongbox sorts the players inventory instead of the stored items.
https://github.com/CoFH/ThermalExpansion/issues/95

InventoryTweaks-1.58-147
ThermalExpansion-[1.7.10]4.0.0B3-11 with dependencies
Forge 1197

**Comment by Kobata** [comment]
See reply in linked thread.

**Comment by cragrim** [comment]
I still have this issue, was it ever resolved? Or is the bug on Thermal Expansions side?
Best Regards

**Comment by bochen415** [comment]
This is fixed already in new TE version (not released yet). Keep a lookout for it.
