### ISSUE TITLE
Factorization IndexOutOfBoundsException

### ISSUE THREAD

**Issue by Nihiliss** [Inventory-Tweaks/inventory-tweaks#200]
1. Item is placed in Factorization's 3x3 pocket crafting window.  
2. Number key is pressed to move the item to hotbar.  
3. IndexOutOfBoundsException

crash report: http://pastebin.com/JkV8Chtc

**Comment by Kobata** [comment]
I have no built-in support for Factorization, so either whoever did your config files messed up, or the Factorization devs messed up.
