### ISSUE TITLE
Modsource modpack

### ISSUE THREAD

**Issue by OmgImAlexis** [Inventory-Tweaks/inventory-tweaks#203]
I'm using [this](http://hermitcraft.com/modsauce) mod pack with the ATLauncher and neither 1.5.8 nor 1.5.9 will work, it causes a crash just as the game loads the jar.

[Here's my log file](http://paste.atlauncher.com/view/5c0cb860).

**Comment by Kobata** [comment]
Something is either interfering with the mod or it is installed incorrectly -- the access transformer isn't running.
