### ISSUE TITLE
Feature Request: match numblock with crafting grid

### ISSUE THREAD

**Issue by MalkContent** [Inventory-Tweaks/inventory-tweaks#204]
I would love the ability to place itemstacks I mouse over into the 3x3 crafting grid by pressing the according key on the numpad. Numpad keys are unused by vanilla mc and the layout is a perfect match.

This would work analogous to the regular number keys switching the itemstack from the n-th hotbar slot with the moused over itemstack (which may be none) by pressing number n. This method also allows putting hotbar items into the crafting grid by hovering over the target crafting grid slot. 

A virtually identical method could be used, binding the numblock keys to the crafting grid instead of the hotbar, swapping the item stacks on key.

**Comment by Kobata** [comment]
See #26
