### ISSUE TITLE
Supposedly incompatible with the mod Baubles

### ISSUE THREAD

**Issue by Olegrock** [Inventory-Tweaks/inventory-tweaks#206]
Hello!

An error occurred while trying to lift dropped out ring from mods Botanica and Baubles
http://pastebin.com/NCpBTF2Z

**Comment by Kobata** [comment]
Huh, that is a strange error.

Try disabling auto refill, but this is probably caused by baubles changing things in a bad manner.

**Comment by Olegrock** [comment]
Thanks for the answer. I will try to kill Baubles :)
