### ISSUE TITLE
Cannot remove certain features of Inventory Tweaks

### ISSUE THREAD

**Issue by MRPolo** [Inventory-Tweaks/inventory-tweaks#207]
I have installed Inventory Tweaks today, but was annoyed by automatic removal of almost-broken tools from my hand.  So I tried to disable that from happening in the options, but that didn't work. Instead, I decided to uninstall Inventory Tweaks. However, after I uninstalled it, the automatic torch placement with right click and automatic removal of tools (the two features that annoyed me...) remained, even though the mod was nowhere.

I tried reinstalling Forge and Minecraft as a whole (removed the whole .minecraft folder), but nothing worked. I still place torches when I right click and still have tools that are almost broken taken out of my hand and put into my inventory, which is annoying to say the least.

**Comment by Kobata** [comment]
The mod can't do anything if it isn't installed, those must be functions from a different mod.

Torch placing in particular is not a feature of Inventory Tweaks.
