### ISSUE TITLE
Sorting bug w/ Thermal Expansion 

### ISSUE THREAD

**Issue by jefrbunn** [Inventory-Tweaks/inventory-tweaks#208]
Using: Thermal expansion v4.0.0B5-13, Thermal Foundation v1.0.0B3-8
MCversion:1.7.10
Forge#1280
Inv Tweaks v1.58-147

BUG: When accessing a Strongbox and sort button is clicked the players inventory is automatically pulled into inventory off hotbar and sorted there. It seems it treats entire inventory (player+hotbar) as one large inventory and sorts at top (which clears the hotbar). 

Not sure which side the bug is on, just an FYI.

Before: 
![image](https://cloud.githubusercontent.com/assets/3003516/4483432/71820ff8-49b1-11e4-9124-51c0b28c2464.png)

After: 
![image](https://cloud.githubusercontent.com/assets/3003516/4483408/33776e1a-49b1-11e4-9dff-237d1b4168ed.png)

**Comment by Kobata** [comment]
See #195
