### ISSUE TITLE
Failing to locate Forge

### ISSUE THREAD

**Issue by FishontheRun** [Inventory-Tweaks/inventory-tweaks#21]
I'm using Magic Launcher, its recognizing Forge, and in status is saying no mods found.  I have Inventory Tweaks in my mods folder but its saying in status "no Forge" (see Picture)
![InvTweaks problem](https://f.cloud.github.com/assets/3964801/298102/7e4a9ce2-9552-11e2-899f-d4607118c6c4.jpg)

I have two versions in the folder testing to see if either of them worked.  I'm not sure of what the problem is here as to why it isn't working.  Looking for some suggestions as to what too do.  I love this mod so glad that its being updated again.

**Comment by Kobata** [comment]
Install forge universal, not the source code version.
