### ISSUE TITLE
Drop all of one kind of item

### ISSUE THREAD

**Issue by MalkContent** [Inventory-Tweaks/inventory-tweaks#211]
Found myself wanting this during mining trips to get rid of all cobble in one click. Maybe alt+ctrl, just like shift+ctrl moves all items of the kind, this would drop all.

**Comment by Kobata** [comment]
Try alt+shift+ctrl

**Comment by MalkContent** [comment]
damn. and there even is alt+shift+space, nice :)
but why is shift required?
