### ISSUE TITLE
Allow reducing of log spam from onTickInGUI

### ISSUE THREAD

**Issue by JLBShecky** [Inventory-Tweaks/inventory-tweaks#212]
I was wondering if being able to turn off the logging of GUI's would be something that would be considered as a possible feature change?

It is really causing log file bloat if one is searching through chest/open GUI's and having the option to turn it of when someone knows that Inventory tweaks is not having issues would be somewhat helpful, so that the log file is easier to read.

(https://github.com/Kobata/inventory-tweaks/blob/develop/src/main/java/invtweaks/InvTweaks.java#L164-L166)

**Comment by Kobata** [comment]
I keep forgetting to just remove that line, I'll try to remember for 1.8 update

**Comment by Kobata** [comment]
af3bc6858378a466248ac141144318bca665ddac
