### ISSUE TITLE
Not working right with Aroma's Better Chests. 

### ISSUE THREAD

**Issue by Chefbarbie** [Inventory-Tweaks/inventory-tweaks#213]
Middle click / "R" doesn't properly sort (only stacks, doesn't move anything around).
Pressing any of the sort buttons in a better chests GUI tosses this into chat:
"InvTweaks: [ERROR] [3] Failed to sort container: Section not available (l36 in ContainerSectionManager,java)"

This happens with chests fully upgraded with storage upgrades (never tried with a basic starter chest. 

Vanilla chests work fine. 

Do not have iron chests installed.

**Comment by BakermanLP** [comment]
Same error as above. Here are some additional information:
- Minecraft 1.7.10
- forge:1.7.10-10.13.2.1231
- Aroma1997Core-1.7.10-1.0.2.11.jar
- BetterChests-1.7.10-1.1.1.7.jar  
- InventoryTweaks-1.59-dev-152.jar

**Comment by Kobata** [comment]
That error means the mod can't find the part of the container it is looking for, which is most likely an issue with the mod in question's implementation of the Inventory Tweaks API.
