### ISSUE TITLE
Error 4 Failed to trigger auto-refill

### ISSUE THREAD

**Issue by Orientalus** [Inventory-Tweaks/inventory-tweaks#214]
I am using the new Direwolf20 modpack for 1.7.10 and I got the Error [4] Failed to trigger auto-refill: null(I69 in SourceFile) message when minecraft was attempting to replace a nearly broken wooden pickaxe with another one I didnt have and the nearly broken one was placed in my inventory.  I hope this gives you enough information, if not I will see what I can do to get more.

**Comment by Kobata** [comment]
There should be a more detailed message in the fml log files, since the short message is refusing to say what file it crashed in.

**Comment by Orientalus** [comment]
Where would I find the fml log file that is needed and how would I get it to whomever needs it?
