### ISSUE TITLE
Missing Chest Buttons

### ISSUE THREAD

**Issue by Kittychanley** [Inventory-Tweaks/inventory-tweaks#215]
I'm having a bit of an issue updating our InvTweaksCompatibility.xml file now that TerraFirmaCraft has updated to MC 1.7.10. I'm currently using InvTweaks 1.58-147. The problem that I noticed is that if I add a container to the file using the chest class flag, no buttons appear on the actual inventory in-game. Pressing the sort button does switch between all of the modes, and I've tried setting large_chest to both true and false (since that moved the buttons in the past). I double checked with a vanilla chest, and the buttons are in that inventory as expected. If I add something using the inventory class flag, the single button does show up.. so it seems to only be an issue with chests.

Here's a copy of the xml file I'm currently using: http://pastebin.com/2dRk3s0A

**Comment by Kobata** [comment]
5dbbb1489ddecfd914f23dc80de9b3323082a121 -- That's a known issue with 1.58, after I added support to the API for specifying buttons on chests but didn't add it to the xml at the same time.
