### ISSUE TITLE
IndexOutOfBoundsException with Dual Hotbars

### ISSUE THREAD

**Issue by StarkRG** [Inventory-Tweaks/inventory-tweaks#216]
While using Dual Hotbars if Inventory Tweaks tries to refill a used item from the second hotbar we get an IndexOutOfBoundsException.
[Crash Log with 1.59-dev-152](http://pb.lzy.li/view/367b065f)
[Crash Log with 1.59-dev-156](http://pb.lzy.li/view/e92a963a)

Dual Hotbars dev, RebelKeith, has [apparently tried to contact you](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2178797-dual-hotbars?comment=65) about this issue.

**Comment by Kobata** [comment]
I can't fix mods doing stupid things that break the way the inventory is laid out.

**Comment by StarkRG** [comment]
It doesn't change anything about the way inventory is laid out. The extra hotbar is simply the first row of the inventory.

**Comment by Kobata** [comment]
The refill code is very particular about how it handles the hotbar, it _must_ be at the end of the (player) inventory starting from where the vanilla one is. Trying to put them in different places will confuse the hell out of it.
