### ISSUE TITLE
Ghost and missing inventory

### ISSUE THREAD

**Issue by icsmouse** [Inventory-Tweaks/inventory-tweaks#217]
I keep checking back to make sure I have the most recent & recommended mods so I'm curious. Is there a reason I keep getting ghost inventory images that seem infinite in supply Then I click on something that I have harvested, ie, Pam's foods or harvested trees let's say & I check my inventory & they are gone. Lots of room in inventory, but said items are not there. Is it me or is there a problem here? Thanks for your time. I know looking into these things takes away from you doing what you love. Have a great day.

**Comment by Kobata** [comment]
Usually these are caused by your client thinking something happened when the server didn't. Attempting to access it makes the server go 'what are you trying to do?' and updates your inventory with the correct information.

**Comment by icsmouse** [comment]
Hmm my computer is my server. Is there anything I can do to remedy this, or is this just one of those "learn to live with it?" things? I can do that if that's the case ;)

**Comment by Kobata** [comment]
It's usually not very common unless a mod is interfering somewhere, but I doubt it's anything to do with Inventory Tweaks. I can't really say anything about what exactly might be causing it with just the information you've given so far though.
