### ISSUE TITLE
Shift+click ? on ME Covered Cable crashes SSP

### ISSUE THREAD

**Issue by Rithenar** [Inventory-Tweaks/inventory-tweaks#219]
I have tried several crafting tables and all with same result. If I shift+click ? on any recipe (even if I do not have materials) nothing happens. If I do with ME Covered Cable I always crash. Here is crash report
http://paste.feed-the-beast.com/view/894079ad

**Comment by Kobata** [comment]
Uhh.. I don't know what's going on there other than something triggering autorefill. The behavior of the ? thing is entirely NEI.

Perhaps your inventory was entirely full?

**Comment by Rithenar** [comment]
Nope, the inventory was not full; and that is what I thought (about NEI), but for some reason the error seems to call inventory tweaks as the trouble..?
