### ISSUE TITLE
[Feature Request] Config to enable/disable in-game chat greeter

### ISSUE THREAD

**Issue by SethWilliamson** [Inventory-Tweaks/inventory-tweaks#220]
**Example:**
`# Display message when InvTweaks loads [Default:True]`
`enableGreeter=true`

**Reasoning**
When the game is heavily modded (I run 196 mods for example) the chat gets awfully spammy on login. I think it would be nice to provide a configurable option to disable non-actionable join messages such as "InvTweaks: Configuration Loaded."

**Comment by Kobata** [comment]
It's not really a 'greeter' -- it can happen midgame if you change a config file. It just happens at the start because any messages during loading (such as when it gets initially loaded) get saved until there's a game to display them in.

**Comment by SethWilliamson** [comment]
Fair enough. It would still be really nice to have a config option to help with the signal-to-noise ratio. I prefer to only get messages that require some sort of action from me in response. Others prefer a lot of status and informational messages. A config option would allow everyone to be happy.

**Comment by Kobata** [comment]
See 1a10a8f6192b8f66ed3a4fb723ba23134d691b99

**Comment by Zaflis** [comment]
I don't know what to look at in the file. I tried adding this into config file but it was ignored and removed when config was loaded:
enableConfigLoadedMesssage=false
...then noticed 3rd 's' and also tried this but it didn't help:
enableConfigLoadedMessage=false

**Comment by midorlo** [comment]
Any further help on this? I am currently unable to filter this message and I want to

**Comment by Kobata** [comment]
See c385de0fef32d529239f954ceed49c5803a6a3f9 / #258 

Not in a release yet, but latest dev (for MC 1.8 only) has that change in it.

**Comment by midorlo** [comment]
So there's no chance to get that changed in the 1.7.10 branch? That version is modded minecraft for most users I guess

**Comment by 1n5aN1aC** [comment]
@netzgeist I agree.

I was just about to make a issue requesting this when I found this existing issue, and was excited to see that it's been aded, but incredibly bummed to learn it was 1.8-only.

Really tempted to see if it's even practical to cherry pick just that update, back into the 1.7.10 branch, and build a version myself....

**Comment by 1n5aN1aC** [comment]
@netzgeist (and maybe @SethWilliamson or @Zaflis) I have done a bit of a hackjob and made a 1.7.10 version with this configuration option.

you can find it here:  https://github.com/1337-Tacos/inventory-tweaks  (compile it using gradle, or download the ready-to-go jar)

I have tested it myself thoroughly, but as I have cherry-picked specific changes from upstream, I cannot guarantee that I did not screw something up.

**Comment by LegendLength** [comment]
Is this in 1.10.2 ?  The enableConfigLoadedMesssage setting seems to be ignored and the message shows in chat even when set to false (which is default i believe).
