### ISSUE TITLE
1.59 Dev 159 Crashing server

### ISSUE THREAD

**Issue by Gunner76th** [Inventory-Tweaks/inventory-tweaks#221]
Tried to update our server to the 1.59-Dev-159 relase from Jenkins and this hapens: http://pastebin.com/73kbk5Ef

We are able to run 1.59-dev-152 with no issues. 

MC: 1.7.10
Forge: 1236/1240
Java 1.7_u71
OS: Windows 7 64-bit
Mods installed: http://pastebin.com/dhK5p9hw

**Comment by Kobata** [comment]
The latest builds run on MC 1.8, not 1.7.10.
