### ISSUE TITLE
[Bug] Dual Hotbar sorting crash

### ISSUE THREAD

**Issue by shadowfacts** [Inventory-Tweaks/inventory-tweaks#222]
[Crash log](http://pastebin.ubuntu.com/9507421/)

When using the [Dual Hotbars mod](http://minecraft.curseforge.com/mc-mods/223272-dual-hotbar) and Inventory Tweaks tries to replace a tool that has just broken, but is in one of the extra 9 hotbar slots, it crashes because it tries to access a slot which is not part of the default 9 hotbar slots, so it crashes with the error:

```
java.lang.IndexOutOfBoundsException: Index: 39, Size: 36
```

Just a side note, the way the extra 9 hotbar slots from Dual Hotbars works it that it just displays the top 9 normal inventory slots as hotbars slots and allows tools/blocks/items to work the same way as if they were in a normal hotbar slot.

**Comment by Kobata** [comment]
See #216 
Don't use replace with mods that mess with hotbars in that specific way, it won't work.
