### ISSUE TITLE
Enhancement request: Ability to sub-sort items in inventory by damage value

### ISSUE THREAD

**Issue by Cal-A** [Inventory-Tweaks/inventory-tweaks#224]
I would love to have the option to put my most-damaged tool in a row D slot so that it gets used up and breaks before it's replaced with a new one, please. By sub-sort, I mean after items which match the rule in InvTweaksRules.txt have been found, only those items would be sorted.

Say I have a wooden pickaxe with 20 damage. I've just mined my first stone and crafted a stone pickaxe. The rule:
    D1-A1 pickaxe
currently seems to favour putting the undamaged pickaxe in the D1 slot. I suggest the rule:
    D1-A1d pickaxe
could be used to favour the pickaxe with higher damage value, regardless of its item ID.

**Comment by Kobata** [comment]
The default order (which determines damage order for specifications that don't include a damage or allow any damage) is global so it can't be changed for specific slots.

It would be potentially possible to invert damage ordering on all tools however.

**Comment by Cal-A** [comment]
That would definitely do the trick. If you'd be willing to please put that option in, it would be very much appreciated, at least by me!
