### ISSUE TITLE
Finish update to 1.8

### ISSUE THREAD

**Issue by Kobata** [Inventory-Tweaks/inventory-tweaks#225]
- [x] Update ItemTree.xml for new items/blocks
- [x] Make sure nothing was skipped in the tree update
- [x] Do a bunch of testing to make sure all major features of the mod still work correctly

**Comment by adracamas** [comment]
Thank you for working on this.

**Comment by Kobata** [comment]
Apparently almost 2,500 people have downloaded the latest dev build since i set up curse uploading, so I guess there must not be very many huge issues with it.
