### ISSUE TITLE
Add item tree support for Ironchest and Backpacks mods

### ISSUE THREAD

**Issue by SirSmurfalot** [Inventory-Tweaks/inventory-tweaks#227]
Please add support for these two mods
Both of these mods are currently being maintained and are updated for 1.8.x
Links:
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1286124-1-6-x-1-7-x-backpacks-v-2-0-1

http://files.minecraftforge.net/IronChests2/

**Comment by Kobata** [comment]
The default item tree is for vanilla items, and very common alterante ores via the forge Ore dictionary.
Mod items should be added by the user or creator of a modpack to their configuration copy of the item tree.

**Comment by SirSmurfalot** [comment]
Can you show me what to add to my Tree then?
