### ISSUE TITLE
Crash while building

### ISSUE THREAD

**Issue by Polyana-Fontes** [Inventory-Tweaks/inventory-tweaks#228]
I was building a house using blocks from Chisels Mod when this crash happened:
java.lang.IndexOutOfBoundsException: Index: 37, Size: 36
http://pastebin.com/HUymCDmg

The blocks were in slot 12 of my hotbar, I have the dual hotbar mod configured to display 18 itens in the hotbar
Dual Hotbar: http://www.curse.com/mc-mods/minecraft/223272-dual-hotbar

**Comment by Kobata** [comment]
See #216 
Dual hotbars and auto refill do not work together.

**Comment by Polyana-Fontes** [comment]
I saw #216 and found that the dual hotbar dev [tried to contact you](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2178797-dual-hotbars?comment=65)

The bug is in inventory tweaks side and apparently it's fixed changing a single line.

**Comment by slawr34** [comment]
Bit late to this party.

I was talking with the dual hotbars dev and yeah its on inv tweaks side.

In the meantime you can download ZyinHUD and use his refill feature whilst disabling inv tweaks refill feature.

@Kobata I've read your responses to similar issues and its very poor form to blame dual hotbars for this issue without even considering it might be your code that could be fixed.

I mean seriously, "I can't fix mods doing stupid things that break the way the inventory is laid out."

...
