### ISSUE TITLE
Feature Request - Baubles support

### ISSUE THREAD

**Issue by T4ge** [Inventory-Tweaks/inventory-tweaks#232]
Would it be possible to let Inventory Tweaks sort in the baubles tab or is that on Azanor's side? The keybind that I use for sorting is not working in the baubles inventory (Which I open by default), but is working fine in vanilla inventory.

**Comment by Kobata** [comment]
https://github.com/Kobata/inventory-tweaks/tree/develop/src/main/java/invtweaks/api/container

Due to not being able to reliably determine what the structure of an arbitrary inventory is, only known or marked inventories allow most functions of the mod to work.
