### ISSUE TITLE
After 'auto replace tool' is triggered can no longer move items in inventory - they just get tossed out of inventory

### ISSUE THREAD

**Issue by wildefires** [Inventory-Tweaks/inventory-tweaks#236]
I've been doing some afk mining using InventoryTweaks to replace my pickaxes. After a pickaxe has been replaced (might be just one, or it might be after a certain number) any time I open my inventory and try to move blocks around the blocks are instead ejected from my inventory instead of "picked up" by my mouse. After closing/reopening minecraft the issue seems to go away - but not upon logout from the server.

Details:

OS: Linux Mint
Java -version: java version "1.7.0_72"
Java(TM) SE Runtime Environment (build 1.7.0_72-b14)
Java HotSpot(TM) 64-Bit Server VM (build 24.72-b04, mixed mode)
Forge version: 1289, 1285 (saw it on both)
Using latest build (1.59) from Jenkins download site.

**Comment by Kobata** [comment]
Try pressing alt/ctrl/shift (on both sides), it might think that the shortcut for drop item is stuck down.

**Comment by wildefires** [comment]
Yep, looks like that fixed it. Hitting 'alt' was the solution - I'm gonna guess it's related to alt-tabbing out. However, the interesting thing is that when I actually hold alt nothing happens (i.e. when I hold alt + click items don't get tossed out of inventory)
