### ISSUE TITLE
Repair-Friendly Option

### ISSUE THREAD

**Issue by keomate88** [Inventory-Tweaks/inventory-tweaks#237]
Repair-Friendly refill OFF still replace the tools

MC 1.8 dev vers 1.59-168
.....

**Comment by Kobata** [comment]
It should be replacing tools, but just waiting until they have actually broken instead of replacing them with a small amount of durability left.

**Comment by keomate88** [comment]
Try to play with Repair-Friendly refill OFF and Auto-Refill Tools ON and just one tool in your inventory ... When the tool is almost broken You will see replace the same tool into an infinite LOOP !!!!!

EDIT:
My fails, it's a mod conflict with ZyinsHUD-(1.8)-v.1.4.0 mod. Just disable Zyins auto-refill function.
