### ISSUE TITLE
Mod Distribution Request

### ISSUE THREAD

**Issue by GrahamCampbell** [Inventory-Tweaks/inventory-tweaks#24]
Please read the PDF at https://dl.dropbox.com/u/48335821/Modders/Kobata.pdf regarding permission to use your mod(s).
Any issues opening the document, drop me a note.

Thanks!
Graham Campbell,
Lead Developer At MineUK,
Part Of The MineEU Network.

**Comment by Kobata** [comment]
Read the MCF post or LICENSE.md more thoroughly.

**Comment by GrahamCampbell** [comment]
I can read, but I was just trying to be polite, and let you know what we plan to do with your mod.

**Comment by Fostenel** [comment]
For future reference, I think just dropping him a note letting him know what you were going to use the mod for would have been sufficient and polite.  You asked him to read a lengthy form letter asking for unnecessary permission. Also, an issue tracker isn't really the place for either of these things.

**Comment by GrahamCampbell** [comment]
Thanks @Fostenel
