### ISSUE TITLE
InvTweaks: Configuration loaded.

### ISSUE THREAD

**Issue by Zaflis** [Inventory-Tweaks/inventory-tweaks#240]
This text "InvTweaks: Configuration loaded." always shows in chat when player logs into the game. I would say it is redundant, but i can't remove it (imagine if all mods told in chat that their configs are loaded?). Went through the config file and can't see where it could be disabled.

**Comment by Kobata** [comment]
Duplicate #220

**Comment by 1n5aN1aC** [comment]
@Zaflis I have done a bit of a hackjob and made a 1.7.10 version with this configuration option, if you are still playing on 1.7.10.

you can find it here:  https://github.com/1337-Tacos/inventory-tweaks  (compile it using gradle, or download the ready-to-go jar)

I have tested it myself thoroughly, but as I have cherry-picked specific changes from upstream, I cannot guarantee that I did not screw something up.
