### ISSUE TITLE
[Enhancement] Option to leave items inside crafting table

### ISSUE THREAD

**Issue by mikeloeven** [Inventory-Tweaks/inventory-tweaks#241]
Just wondering if you could add an option to address one of the more annoying aspects of minecraft inventory. the fact that materials are ejected from the crafting table every time you close the interface. I am thinking that the implementation could be a option in the menu that when you toggle the feature items are left inside the crafting table for example when using cooking mods that require water you will be able to leave stacks of ingredients in the table while cycling the limited amounts of buckets

**Comment by Kobata** [comment]
There is no server-side storage for items in (normal) crafting slots after their gui has been closed, so this is outside the normal scope of this mod providing things that can be done with only changes on the client.
