### ISSUE TITLE
Crash on stack refill

### ISSUE THREAD

**Issue by SephirothWS** [Inventory-Tweaks/inventory-tweaks#242]
I'm not sure if this is a cross-mod issue, or what, but I'm playing the FTB Infinity pack v. 1.2.0 with Fastcraft 1.9, and it's really random on if/when it crashes when Inventory Tweaks refills an item stack from my inventory to my hotbar as I am building.

Not sure if this is an inventory tweaks issue, but it happens when Inventory Tweaks kicks in. Can't really read the crash report all that well.

http://pastebin.com/sLKMF9z3

**Comment by Kobata** [comment]
I can't really tell much of anything about the crash from that log, because of the type of crash it is the issue happened some time before the actual crash.

I did play with the last 1.7.10 build for a while without any crash issues (even with fastcraft for a time), so I'm not sure what's happening here.

**Comment by SephirothWS** [comment]
I did some research on the crash, and according to LexManos, http://www.minecraftforge.net/forum/index.php?topic=28126.0 ... One or more of the mods I'm running is playing a sound incorrectly, which is causing this crash. ... Though I posted it here because this crash only has been occurring when Inventory Tweaks kicks in and refills my hotbar. ... I've found an option in Inventory Tweaks itself to disable the sounds, and I'm going to see if I get any further crashes with that option, and if not. ... well you might want to consider looking into how you play the sound effects in Inventory Tweaks.

**Comment by Kobata** [comment]
Looking at what I changed it's entirely possible that specific version was doing sounds in a bad way -- a bit after it was released I messed a good bit with how auto-refill works. If it _is_ inventory tweaks the most recent code most likely won't be causing a sound crash.
