### ISSUE TITLE
Invtweaks injection brokes other's mod's usage

### ISSUE THREAD

**Issue by liach** [Inventory-Tweaks/inventory-tweaks#244]
https://gist.github.com/liach/625b27f9c2c28388c14f
I think there may be someway to prevent the crash. Could Kobata help?

**Comment by Kobata** [comment]
Finder mod has no business trying to set up a GUI before the game has even loaded.

**Comment by liach** [comment]
As the GUI is static, it needs to show a bar at the top of the game. So thank you, I will do it. Original code for 1.7.2: https://github.com/freethemice/Findermod

**Comment by Kobata** [comment]
It still does not need to exist before the main menu even appears, and
before other mods are started
