### ISSUE TITLE
Index Out of Bounds

### ISSUE THREAD

**Issue by kreezxil** [Inventory-Tweaks/inventory-tweaks#245]
client crash report: http://paste.ee/p/Phhrp
fml client latest: https://paste.ee/p/hVF0O

happens reliably when picking up placing items from securitycraft next to each others.

**Comment by Kobata** [comment]
> java.lang.IndexOutOfBoundsException: Index: 31, Size: 0

Something is really messing with inventories that isn't me, because it should never be possible to have an inventory with nothing in it in vanilla.

**Comment by kreezxil** [comment]
Haven't been able to reproduce it since your last update. I'm gonna call it closed for now.
