### ISSUE TITLE
Cannot load minecraft with latest InvTweaks dev build

### ISSUE THREAD

**Issue by cocopuffs99** [Inventory-Tweaks/inventory-tweaks#246]
java.lang.NoClassDefFoundError: net/minecraftforge/fml/relauncher/IFMLLoadingPlugin

Updating from INVENTORYTWEAKS-1.59-DEV-156
to InventoryTweaks-1.59-beta-174.jar

causes FML to throw a bunch of errors and cannot load the game (no crash log) using ATLauncher and the latest version of RR3. 

crash log: http://pastebin.com/8vWvjakT

**Comment by Kobata** [comment]
Maybe read the change notes for a while back, or the mc version on curse forge?

**Comment by cocopuffs99** [comment]
Ok, thanks!  Sorry

**Comment by cocopuffs99** [comment]
Ok thanks! Got it. 1.7.10.

Sorry.
