### ISSUE TITLE
Forge 1339 loading with error

### ISSUE THREAD

**Issue by RepoDraghon** [Inventory-Tweaks/inventory-tweaks#254]
FML : minimum version required is 8.0.42

without your InventoryTweaks 1.5.9 mod on 1.8, the game starts fine...

**Comment by Kobata** [comment]
Read the message.
Read it again.
Do the thing it's implying you should do.

**Comment by RepoDraghon** [comment]
I have no idea what the message is saying, I don't know what 8.0.42 is...
