### ISSUE TITLE
java.lang.NoClassDefFoundError: net/minecraftforge/fml/relauncher/IFMLLoadingPlugin

### ISSUE THREAD

**Issue by dillmo** [Inventory-Tweaks/inventory-tweaks#256]
Minecraft throws the above error when I run InventoryTweaks and Forge 10.13.3.1355-1.7.10. The error is not thrown when only Forge is installed. I get this same error with Aroma1337Core, but not with all mods. Here is my [full log](http://paste.ee/p/FCdOW).

**Comment by Kobata** [comment]
Check versions more carefully.
