### ISSUE TITLE
Error on launch "FML : minimum version required is 8.0.42"

### ISSUE THREAD

**Issue by jpcguy89** [Inventory-Tweaks/inventory-tweaks#257]
Can't launch minecraft after installing Inventory Tweaks. I've update Forge, Forge Mod Loader, (which doesn't have the version specified). I downloaded the most recent, non-developer version on Inventory-Tweaks from your website. It should also be noted that the version of FML specified in the error message doesn't appear to have been released yet.
![fml](https://cloud.githubusercontent.com/assets/1883268/7011447/cfe0021c-dc6e-11e4-8f71-e5082c24044c.png)

I've heard nothing but good things about Inventory-Tweaks and am very disappointed I haven't been able to get it to run yet.

**Comment by Kobata** [comment]
Try the latest version of Forge. Their version numbers are a bit confusing.
