### ISSUE TITLE
Autorefill/inventory derps

### ISSUE THREAD

**Issue by SephirothWS** [Inventory-Tweaks/inventory-tweaks#259]
Using the latest 1.7.10 version, (Cannot use 1.8 due to modpack and not all mods updated yet) I get the following problems:
- I will randomly just throw items onto the ground if I try to shift-doubleclick an item stack into an inventory.
- If the inventory is full and I'm trying to craft with something or move things around in my inventory, I left-click an item to pick it up, then left-click it to "swap" with another item in the inventory. ... It doesn't work that way. Instead the item is thrown out into the world in front of me.
- Auto-refill desyncs quite a bit, sometimes it works properly, other times it leaves items attached to my mouse cursor.

Are there any plans to fix these on 1.7.10? Or is that version a dead horse and I should be putting my whip away?

**Comment by Kobata** [comment]
1.7.10 is getting no further updates. Go bother the people refusing to update to 1.8.

**Comment by SephirothWS** [comment]
So you're going to ignore a broken mod because you refuse to fix it before moving on to 1.8? That's glorious, man. Thanks.

**Comment by Timeslice42** [comment]
If you don't want to continue to develop for 1.7.10 that's certainly your business, but there are a significant number of mods that are just going to skip 1.8, and for good reason. Although I wonder how many of them realize that 1.9 is going to be just as bad...

**Comment by SephirothWS** [comment]
He doesn't care, Timeslice42. No amount of requests will change this
stubborn mule's mind.
