### ISSUE TITLE
Crash when used with DualHotbars

### ISSUE THREAD

**Issue by Mustang351c** [Inventory-Tweaks/inventory-tweaks#263]
When replacing an item on the second hotbar created by the mod DualHobar it crashes the game. The creator of the mod (RebelKeith) said they have private messaged you (not sure on what site. Curse? minecraft forums?) about how to fix it. But in the latest version of your mod available on curse i still seem to be experiencing the crash. I am playing minecraft 1.7.10

**Comment by Kobata** [comment]
DulaHotbars is not supported with auto-refill.
