### ISSUE TITLE
Incompatible with new Forge.

### ISSUE THREAD

**Issue by Thiana** [Inventory-Tweaks/inventory-tweaks#264]
Inventory Tweaks 1.59-176 (from Curse) is incompatible with the newer forges. Tested on 1395 and 1401. The log is at http://pastebin.com/vVL6zDkJ. Thanks.

Reproduce: Create Forge 1395+ instance, add Inventory Tweaks, crash :)

**Comment by Kobata** [comment]
Read the compatibilty info on curse better.

**Comment by Thiana** [comment]
Ok, apparently that is a bug in the Curse Voice launcher then. Installing from the launcher gives no indication that its for 1.8 not 1.7.10 even though its installing into a 1.7.10 instance :/
