### ISSUE TITLE
creative+ full inventory crash, not checking for room? 

### ISSUE THREAD

**Issue by plaguewolf** [Inventory-Tweaks/inventory-tweaks#265]
oops, well as the title says, in creative+(through NEI) when i cheat in a stack of items if there isnt room for the stack i get a client crash, not sure if this is related to inv tweaks, or NEI but im doing my rounds of bug reporting.

another one that im sure is realted is here https://github.com/rwtema/extrautilities/issues/605

that was fun. gave me a scare though watching my cpu temp go up. 

im fairly certain its on extra utilities side though, perhaps the way he handles checking if the bag gets picked up

**Comment by Kobata** [comment]
Can't tell anything without a crash log.

**Comment by plaguewolf** [comment]
welp. there was no log, as it locked up my whole computer. easy enough to reproduce though.

forge 1291, NEI, Inv tweaks, extra utilities. give golden bag of holding, put in hotbar with other item(s) and space + left click on any item in hotbar to dump into bag. it tries to dump whole hotbar into bag, thus putting the bag inside itself, which is normally impossible, because it cant be picked up when its open.

just made a instance in MultiMC with that setup to test. the instant i space click stuff in hotbar with bag open it maxes out my cpu(amd 8 core @ 4.8Ghz) and begins leaking memory(from 1.5GB to 7Gb in about a minute. no logs though cause it doesnt hang, just freezes.

**Comment by plaguewolf** [comment]
same thing happens with forge 1355, 1373, and the now recomended 1448. did you ever attempt to reproduce like i showed above?

it simply doesnt give a log, the whole client hangs and nothing responds until i manually terminate the java instance.

maybe just a blacklist option for extraUtil golden bag?

**Comment by Kobata** [comment]
At this point all the 1.7.10 versions are so far behind it's probably an even chance whatever is causing this has been fixed since, if it's something in inventory tweaks. In any case, there are no plans for further updates to 1.7.10.

**Comment by plaguewolf** [comment]
this makes me so sad...

maybe i could have a poke at the source? would that be ok?
