### ISSUE TITLE
How do you stop an item from being auto-refilled? 

### ISSUE THREAD

**Issue by GlenTiki** [Inventory-Tweaks/inventory-tweaks#268]
E.G. on my server, inv-tweaks is banned because you can auto-refill a sword that broke, a throw able health pot... etc. I want to disable refill pots, swords and armor, for pvp, if possible. I tried messing with the code, but the sorting hurts my head :(

**Comment by Kobata** [comment]
There are no server-side controls. For the most part, the mod appears to the server exactly as if the player had done things themselves, just faster.

**Comment by GlenTiki** [comment]
I know there are none, I'm a mod on the server and trying to catch people using it is _hard_. So, I want to try put together a custom inv-tweaks that I can distribute for the server, if possible. I know many people on pvp servers where this mod is banned that would much appreciate it.
