### ISSUE TITLE
incompatibility or solution ?

### ISSUE THREAD

**Issue by Xeikos76** [Inventory-Tweaks/inventory-tweaks#269]
Good evening

When I run minecraft in 1.8 with Liteloader and Forge version recommended as well as your 'Inventory Tweaks' mod, he wants me to have the version of FML in 8.0.42 and when I run minecraft with FML it asks me the 11.14.1.1334 forge version. Is there an incompatibility between LiteLoader and InventoryTweaks or a solution?

**Comment by Kobata** [comment]
FML is part of forge, and inventory tweaks requires both. Because of strange reasons, the version numbers are different, but for either you should use a new version of _forge_

**Comment by Xeikos76** [comment]
Hi, I found version of forge compatible with your mod, it's the 11.14.1.1404 version.
