### ISSUE TITLE
"strange crash on dedicated forge server"

### ISSUE THREAD

**Issue by kreezxil** [Inventory-Tweaks/inventory-tweaks#272]
"strange crash on dedicated forge server"
server crash report: http://pastebin.com/B9VM1B6r
server fml latest: http://pastebin.com/E353FskP
I'm currently using b1419

Lexmanos said to contact coremod authors, you are one of them.

**Comment by Kobata** [comment]
Don't do anything there. In fact, the coremod part does nearly nothing practical on dedicated server (It's just not really easy to separate it)

**Comment by kreezxil** [comment]
Was this something with your mod or one of the others?

-----Original Message-----
