### ISSUE TITLE
inventory tweaks menu button sends click event to container

### ISSUE THREAD

**Issue by wjrogers** [Inventory-Tweaks/inventory-tweaks#274]
Clicking the inventory tweaks "..." menu button sends a click event to the open container, which can lead to unexpected interactions. For example, on a BetterStorage Crafting Station, clicking the inventory tweaks menu button triggers the Crafting Station's "April Fools" event handler (because it does not check to see which button the event came from), de-syncing the client with a client-side explosion.

Reference:
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/1442380-betterstorage-0-13-1-126-wip?comment=1874

**Comment by Kobata** [comment]
They're standard buttons added into the list of buttons on the container, so I don't really have a choice -- the gui's click handler is what tells the buttons they're clicked.
