### ISSUE TITLE
Crash: change damaged tool while no place in Inventory

### ISSUE THREAD

**Issue by frmnch** [Inventory-Tweaks/inventory-tweaks#276]
When InventoryTweaks wants to change the Damaged Tool (Damage Threshold) but there is no free space in the players Inventory, the game crashes.
crash-report: http://pastebin.com/BrD92XQ3

**Comment by Kobata** [comment]
This was fixed back in march in 4f89189ab96e16a6f8cc2dde12083473dc55cc3b.

Always test with the latest version before reporting.
