### ISSUE TITLE
[Suggestion] Minecraft version to filename

### ISSUE THREAD

**Issue by Zaflis** [Inventory-Tweaks/inventory-tweaks#278]
I was updating my slightly outdated modpack and then had hard crash from forge on startup. After an hour of searching with google for solutions to "An error occurred trying to configure the minecraft home", i only found the culprit after going through core mods 1 by 1 and seeing they are all good 1.7.10 versions.. Turned out my InventoryTweaks was for 1.8, since it was top most link in curse. But from the logs i couldn't possibly tell that it was for 1.8, nor that it was this mods fault that it crashed.

**Comment by Kobata** [comment]
![curse](https://cloud.githubusercontent.com/assets/2323933/8753288/5fef8ba2-2c88-11e5-96a6-c3d89245eb33.png)

Don't use the non-curseforge site, it's horrible.

**Comment by Zaflis** [comment]
I know there is 1.8 marked on other curse too, but it's only afterwisdom. When you are updating 50 mods you just sometimes lose focus. 99% of the other mods filenames include word 1.7.10 in them, so it's kind of a standard. But in the end up to you.
