### ISSUE TITLE
some items have sorting incompatibility

### ISSUE THREAD

**Issue by jkuball** [Inventory-Tweaks/inventory-tweaks#279]
When you have some specific items in your inventory you're unable to sort it. When you do it, the sorting fails and you end up with the item grabbed by your mouse. That's extremely annoying and dangerous: you could accidentally drop an important item in lava.

I assume it has to do with some strange NBT data.

This bug is perfectly reproducable with a mana tablet from botania. (It also happens sometimes with some rotarycraft machines)

(You can workaround this with placing the item in the hotbar, but this is not a reliable solution since you have to sacrifice a hotbar slot)

Versions used: InventoryTweaks-1.59-dev-156, Botania r1.6-193

**Comment by Kobata** [comment]
Make sure the server (if you're playing on one) has inventory tweaks installed, and your client is set to use the server-side helper in the invtweaks settings.

**Comment by jkuball** [comment]
I didn't know that InvTweaks is not only a client-side mod. Yeah, that fixed it. Thanks!

**Comment by Eufranio** [comment]
@Kobata Some way to do this without putting the mod on the server?

**Comment by Kobata** [comment]
If the sorting is messing up in this specific way, most of the time it's caused by the server rejecting the movement, so most likely not.
