### ISSUE TITLE
Sorting using NBT data

### ISSUE THREAD

**Issue by zclimber** [Inventory-Tweaks/inventory-tweaks#280]
The exact reason is that I use TConstruct and want to, for example, put best Throwing Knife into D1 slot. Using #261 solution helps partially: all of knives have same item ID, and all info is stored in NBT tag of an item. So, sorting just cycles the knives preferring ones with higher damage, which is not really good("worse" damaging knives with ammo are better than "stronger" ones without ammo, and so forth).
Thus, even better I think would be making user able to implement custom sorting algorithm for items that have NBT data: such as list of important tags, and then put "sorter=" into sorting tree, like "id="

**Comment by Kobata** [comment]
See #4 and the comments in #261 you linked. 1.8's NBT-JSON can help a bit, but there's still not a good solution for discoverability of the properties of an item.

**Comment by Shados** [comment]
Why would NBT tags need to be discoverable? Surely you can just let the user define what tag to sort on and how to compare the tags for a given item ID?
