### ISSUE TITLE
InventiryTweaks - InfinityInvo issue

### ISSUE THREAD

**Issue by GozzyCraft** [Inventory-Tweaks/inventory-tweaks#285]
Hi, I playing Skyfactory2 modpack on the ATLauncher and have inventoryTweaks and InfiniteInvo-1.0.36 installed. I dont know what mod is the issue but i already contacted the guy from the other mod and he thinks it is an issue with Inventory Tweaks.
The issue is if i have both mods activated the autor-refill function from InventoryTweaks is not working.
Same the are some issues with the sorting of items "R-Key". The items in the hotbar get pulled into the inventory as well. Could you look this up if you can fix this and if its not only an issue with your mod alone could you contact the guy from the other mod and find a solution?

**Comment by Kobata** [comment]
Things that change the inventory will not automatically work, and need to be using the provided API functions to tell inventory tweaks where things actually are.

**Comment by GozzyCraft** [comment]
what?

**Comment by Zer0t3ch** [comment]
@GozzyCraft Basically, the other mod author is wrong. He effectively breaks anything else that touches inventory because of how he does things.

**Comment by GozzyCraft** [comment]
Thanks for the reply, even if it is very later but thanks. I don't use the other mod anymore anyway because i didn't believe it would be your fold. Your mod is out so long and makes such good things, like i said, don't worry. Keep the good work up :dancer:
