### ISSUE TITLE
InvTweaks: [ERROR] [4] Failed to trigger auto-refill: null (l69 in SourceFile)

### ISSUE THREAD

**Issue by Rasmun** [Inventory-Tweaks/inventory-tweaks#287]
Hi,

I receive the following error when picking up an empty Mana Tablet after the tablet is emptied into a mana pool (Mana Tablet is from the Botania mod).  This also sometimes causes Minecraft to crash.

Since the error says InvTweaks, I figured I should report it here, but if this is not the right place, please let me know.

> **InvTweaks: [ERROR] [4] Failed to trigger auto-refill: null (l69 in SourceFile)**

Versions:
Direwolf20 1.6.1
Minecraft 1.7.10
InventoryTweaks-1.59-dev-152.jar (_same problem in InventoryTweaks-1.58-147.jar_)
Botania r1.7-221.jar

**Comment by Kobata** [comment]
1.7.10 bugs aren't very useful at this point, since there have been a variety of changes since the last 1.7.10 release, particularly in the area of auto-refill handling.
