### ISSUE TITLE
Shift + click with stack on cursor is unreliable at best.

### ISSUE THREAD

**Issue by NolanSyKinsley** [Inventory-Tweaks/inventory-tweaks#289]
I believe this is inventory tweak's realm, but I am not sure. The feature I am talking about is picking up a stack and moving it to another inventory and holding shift when you place the stack down. It moves all of the same item into the inventory.

I love this feature but it is really really unreliable, no matter how much I make sure my cursor is perfectly centered in the inventory slot 50% of the time it throws all of the items on the ground instead of transferring them. Whenever I attempt this the inventory slot I am moving to is always highlighted under my cursor and the item stackk yet it still tosses all of the items on the ground randomly instead of moving them.

**Comment by Kobata** [comment]
Not inventory tweaks -- no plain shift shortcut, and none of them trigger while clicking an empty slot.

The 'move all of an item' shortcut is either ctrl+shift or space by default, and works when you click that item type in the source area, not while trying to place it.
