### ISSUE TITLE
Mushroom stew doesn't auto-refill

### ISSUE THREAD

**Issue by Aeroxia** [Inventory-Tweaks/inventory-tweaks#292]
I'm in 1.7.10, using "InventoryTweaks-1.59-dev-152"

When I eat a mushroom stew, it changes into an empty bowl instead of being replaced with another in inventory.  It happens without any other mods (except forge).  With biomes o plenty, their variation "[Shroom Salad](http://biomesoplenty.wikia.com/wiki/Shroom_Salad)" works as you would expect (it's replaced with a new one).

**Comment by Kobata** [comment]
I think I see why, although I'm surprised a different version works if it does the same thing as mushroom stew with leaving a bowl behind in the slot.
