### ISSUE TITLE
BetterStorage buttons in wrong place

### ISSUE THREAD

**Issue by Idealess** [Inventory-Tweaks/inventory-tweaks#296]
![screenshot 12](https://cloud.githubusercontent.com/assets/15607379/10877042/6c148a30-81a7-11e5-8ebb-a26055445bb3.png)

This happens in BetterStorage's Reinforced Chests, Lockers, Reinforced Lockers and Crates.

**Comment by Kobata** [comment]
The button locations are based on the size of the GUI, and in this case, intentionally placed in a slightly awkward spot because the normal location for the vertical (large GUI) buttons would be off to the right, overlapping the first set of NEI items.
