### ISSUE TITLE
JABBA Barrel Clash

### ISSUE THREAD

**Issue by PlayOnly** [Inventory-Tweaks/inventory-tweaks#297]
Crash upon inserting cobble (right click) into Barrel...
Crash Report! http://pastebin.com/rRAJCAXg

forge-1.7.10-v10.13.4.1448
Jabba-v1.2.1a_1.7.10
InventoryTweaks-1.59-dev-152

**Comment by Kobata** [comment]
1.7.10 versions are very far behind (particularly on autorefill), so unless you can reproduce on a 1.8 version, this is not helpful.
