### ISSUE TITLE
Inventory-tweaks causes WR-CBE frequency names to disappear after reload

### ISSUE THREAD

**Issue by ssotangkur** [Inventory-Tweaks/inventory-tweaks#299]
[Update] Sorry looks like its not related to inventory tweaks, its just inconsistently missing.

Verified with the latest WR-CBE (WR-CBE-1.7.10-1.4.1.9-universal.jar)

The wireless redstone mod's advanced gui will lose its frequency names after the client restarts. The issue goes away after inventory tweaks is disabled.

In the minecraft log there's a conspicuous msg:

```
[20:05:18] [Client thread/INFO] [inventorytweaks]: codechicken.wirelessredstone.core.GuiRedstoneWireless
```

**Comment by Kobata** [comment]
The log entries are just old debug text when the open screen changes.

Invtweaks 1.7.10 is no longer supported, so please try to see if any issues can be reproduced in 1.8.
