### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by AhmiDarrow** [Inventory-Tweaks/inventory-tweaks#300]
Yea I have a nasty memory leak caused by an interaction between Inventory tweaks and thaumic expansion. I've made The Temporalist aware this and am helping test a build to see if he has fixed it on his side but I wanted to make you aware of this as well. 
https://www.dropbox.com/s/g5m75tn5vuoyxym/fml-client-latest.log?dl=0
If you look all the way at the bottom of this log you'll see some spam caused by inventory tweaks in reference to thaumic expansion. That will continue until all the ram on the client is gone and you have to end minecraft from the task manager. That being said this is only affecting the client, NOT the server. Our modpack is extensive but has not had any issue until we added the combination of Thaumic expansion and Inventory Tweaks. Which we LOVE both mods but it's becoming a pain to play since the memory leak has appeared.

**Comment by Kobata** [comment]
The log entries are just old debug text when the open screen changes.

Invtweaks 1.7.10 is no longer supported, so please try to see if any issues can be reproduced in 1.8.
