### ISSUE TITLE
Autorefill leaving an item 'in hand'

### ISSUE THREAD

**Issue by GunArm** [Inventory-Tweaks/inventory-tweaks#302]
Another autorefill issue, I don't think this is a duplicate but I could be wrong.

Start with a pick in your hotbar and 2 extra picks in your inventory.
Wear down (break) the first pick, so that autorefill occurs.  
The next time you open your inventory, the remaining extra pick will be 'in your hand'/'under your cursor', rather than in a slot in your inventory.

This can be a detriment if you aren't expecting it and you click outside the inv box it will throw down the item.  I've accidentally thrown down important items into lava, and I'm pretty sure it's happened without me realizing it and I jetpacked away and lost items.

I think it's something to do with inv tweaks is moving things around faster than the game can keep up with and the last 'place-selection-in-slot' command is not registering so you have the item still selected but you don't see it until you finally open your inventory.  Which could be 20 minutes later and take you totally by surprise.

**Comment by GunArm** [comment]
In the past, the issue combined with another issue to create a the illusion of item duplication.  That seems to be fixed now but I'm still seeing whats described above.  Also, I forgot to say i'm on version 1.59-DEV-156 which is included in RR3.

**Comment by Kobata** [comment]
Invtweaks 1.7.10 is no longer supported, so please try to see if any issues can be reproduced in 1.8.

In particular for this issue, autorefill has enough changes that it is likely to work much better in 1.8.
