### ISSUE TITLE
Rules not working & Item 'in hand'

### ISSUE THREAD

**Issue by 2ndParty** [Inventory-Tweaks/inventory-tweaks#308]
I play on Hypixel, their skywars are very fun and I wanted to get Inventory-Tweaks to help me excel at the game. However, I wrote my rules as follows ;

D1 sword
D2 bow
D3 edibleFood
D4 enderPearl
D5 bottleOEnchanting
D6 potion
D7 positivePotion
D8 stone
D9 pickaxe

~~ 95% of the time, this does not work properly, I'll have a pick in slot D5, a snowball in slot D8, for example.. Or even an axe in D1, not only that, but if I have an item in hand (such as my D1, with my hand holding that item) and i hit that 'R' button; that item will either, not move, OR it'll be under my cursor when I open my inventory.

My settings for the tweak are as follows.
Repair-Friendly Refill: Off
Shortcuts: On
Auto-Refill: On
Middle Click: On
{MORE OPTIONS}
Enable sound: On
Auto-Equip Armour: On
Sort On Pickup: On
Chest buttons: On
Server Item Movement: On

~~ Thank you for taking the time to read my issue, have a wonderful day <3

**Comment by Kobata** [comment]
Almost all the time these are issues with the server being told to disallow movements that appear to be automated.
