### ISSUE TITLE
can't see picked-up items in my inventory

### ISSUE THREAD

**Issue by carniafolk** [Inventory-Tweaks/inventory-tweaks#309]
a month ago I created a modpack with my friend but, when we started playing it, we discover items that we picked-up (like cobblestone or oak wood) didn't apper in our inventories.
My questions are: Is this bug caused by inventory tweaks? if it is, how we can fix it?
Thanks for answers and sorry if my english is not so good (I'm not english)

**Comment by Kobata** [comment]
It's probably possible that the inventory isn't being sent over properly in some cases, but I haven't seen anything of the sort happen myself.

Do the items reappear after reconnecting or when clicking around random spots in the inventory?

**Comment by carniafolk** [comment]
they reappear when I click the inventory sorting button (by default the middle button of the mouse) or when I right-clicking with something that has a durability in the hand.

**Comment by carniafolk** [comment]
i solved: the bug was caused by optifine...

**Comment by Kobata** [comment]
Optifine does some strange things, but I can't say I've heard of it doing that before.
