### ISSUE TITLE
Sorting by and id and damage range

### ISSUE THREAD

**Issue by Gerren** [Inventory-Tweaks/inventory-tweaks#31]
Since id range is already implemented, sorting by damage value range might be a nice idea :) 

why: some mods (like RedPower2) use one block id and whole range of damage values, like covers: damage value 0 through 67 or so.

**Comment by Kobata** [comment]
InvTweaksTree: &lt;name id="1234" dmin="0" dmax="67"/&gt;
For sorting rules: A1 name

**Comment by Gerren** [comment]
Oh thanks, kind sir :) I didn't find it in the documentation or any guide. :)

And thank you for doing good job with the mod :)
