### ISSUE TITLE
Items with different names, and maybe special NBTs, don't work well with this mod.

### ISSUE THREAD

**Issue by deuceman2008** [Inventory-Tweaks/inventory-tweaks#312]
On the server I play on, Lord of the Craft, items with special names, which are COMMON on this server, don't work correctly with this mod. It seems anything with a special name that is sorted is sorted back to it's original location in the inventory menu or on the mouse inventory space. It's not server side because it works just fine with vanilla items, but renamed objects seem to be the only affected items with this glitch. If possible, I'd love it if this glitch was fixed. Thank you.

**Comment by Kobata** [comment]
The mod doesn't really know anything about special additions, so items with display names cannot be sorted separately from their base versions.

**Comment by Derpford** [comment]
Perhaps you could add wildcards to the item tree/search rules?
That way, you could just make a rule:
`D1 * sword`
and any item that matches "___ sword" is placed in slot 1 of the hotbar.
