### ISSUE TITLE
Anvil Chat Spam 1.60-dev-27 for MineCraft 1.8.9

### ISSUE THREAD

**Issue by PokeMaserJ** [Inventory-Tweaks/inventory-tweaks#313]
When moving items inside an Anvil this get this put into chat
InvTweaks: [ERROR] [6] Failed to trigger shortcut:  toIndux = 45 (l1004 in ArrayList.java)

**Comment by GirafiStudios** [comment]
Can confirm this issue. Happens with the latest beta version too.

**Comment by Kobata** [comment]
I haven't looked into this yet, but it would be helpful to get a full stack trace out of the logs instead of the very basic information in the chat messages,

**Comment by GirafiStudios** [comment]
@Kobata, there ya go: https://gist.github.com/GirafiStudios/02457952e424c2b61c07

**Comment by Kobata** [comment]
Huh, interesting, I think there's been a bug in the anvil slot assignments for a while, it just wasn't easily noticeable before.

**Comment by Kobata** [comment]
That should fix it -- as a note the input slots on the anvil will be emptied by inventory sort like vanilla crafting tables as they are temporary slots.
