### ISSUE TITLE
Inventorytweaks for 1.8 wants minecraft 1.8

### ISSUE THREAD

**Issue by KarelPeeters** [Inventory-Tweaks/inventory-tweaks#314]
I just downloaded the newest InventoryTweaks version on this site: https://inventory-tweaks.readthedocs.org/en/latest/, it's the first one called "1.8", the file is called "InventoryTweaks-1.59-176.jar".

I tried installing on a fresh instance of Forge, version "1.8.8-forge1.8.8-11.15.0.1655". It gives me the following error and corresponding log:
http://imgur.com/wQhWkRY
http://pastebin.com/aKzXbx7A

Does somebody know what the problem is?

**Comment by Kobata** [comment]
1.8.8 is not 1.8 itself.

Use the latest alpha on curseforge (http://minecraft.curseforge.com/projects/inventory-tweaks/files) for 1.8.8/1.8.9
