### ISSUE TITLE
When trying to load Minecraft Tweaks, and Forge installed with Magic Launcher

### ISSUE THREAD

**Issue by ghost** [Inventory-Tweaks/inventory-tweaks#32]
![Teaks](https://f.cloud.github.com/assets/4111207/360477/312adbb6-a196-11e2-9f56-31abc8830d9d.png)

I honestly don't know what's my problem cause I usually Download the latest forge.

**Comment by Kobata** [comment]
This type of error is an installation error in minecraft.jar, and has nothing to do with Inventory Tweaks, so it really doesn't belong on this tracker.
