### ISSUE TITLE
InvTweaksRules, sorting by ID is not working v1.59dev153

### ISSUE THREAD

**Issue by maxiride** [Inventory-Tweaks/inventory-tweaks#321]
I'm on modded minecraft and I tried to sort some items like a satchel from Thermal Expansion and few items from TInkers' Construct.

If I add a rule into InvTweakesRules like D1 6341 (a TiC pickaxed) it doesn't get sorted.
I've also tried to manually add an entry into the tree file without success.

**Comment by Kobata** [comment]
Since 1.7 you need the 'id name' of the item, not the numerical ID. Press F3+H to display those, they should be something like 'amod:someitem'

**Comment by Kobata** [comment]
Ah, addition: They probably need to be added to the tree file (and then use the name you assigned there) because it's somewhat ambiguous in the rules file now.
