### ISSUE TITLE
InvTweaks: [ERROR] [4] Failed to trigger auto-refill:

### ISSUE THREAD

**Issue by ghost** [Inventory-Tweaks/inventory-tweaks#325]
It might be a easy to solve problem but I have no clue how to fix it. I get this error whenever something should be auto replaced:

`InvTweaks: [ERROR] [4] Failed to trigger auto-refill:
java.lang.String cannot be cast to net.minecraft.util.ResourceLocation (l29 in FMLControlledNamespacedRegistry.java)`

Versions:
Minecraft 1.8.8
InvTweaks 1.59-dev-162-9aad63b
Forge Mod Loader 8.0.99.99
Minecraft Forge 11.15.0.1636

**Comment by Kobata** [comment]
Try a newer version, that is really old and designed for 1.8, not 1.8.8
