### ISSUE TITLE
All items disappearing from inventory.

### ISSUE THREAD

**Issue by abrachoo** [Inventory-Tweaks/inventory-tweaks#329]
When I use the sort button or even click on an item in my inventory, everything disappears. It all comes back when I open up a chest or other block's inventory. 
I'm using Minecraft 1.8.9 with the mod version 1.60-beta-38, although I was having the same problem with the mod a few versions back (1.60-beta-30).
It was working fine for a while before the problem arose.

**Comment by Kobata** [comment]
Please include the mod version, minecraft version, and any additional information that could be relevant.

**Comment by abrachoo** [comment]
Added more information.

**Comment by abrachoo** [comment]
After more testing, I've decided that this mod is not the cause of the bug, but merely made it more apparent.
