### ISSUE TITLE
Inv. Tweaks & OptiFine. Bug.

### ISSUE THREAD

**Issue by Pesdec** [Inventory-Tweaks/inventory-tweaks#33]
Hello, I found some bug with this 2 mods. If "Custom Fonts" in OptiFine options is "ON", Inv. Tweaks doesn't work properly (hotkeys does not work). If u turn it off, Inv. Tweaks work at full capacity. Sorry, if I repeating. Thank u.

**Comment by Kobata** [comment]
I... can't even begin to imagine what OptiFine could be doing with that option to break something totally unrelated to fonts. I'll have to look into it at some point since I don't usually install Optifine, especially with recent FML/Forge fixing the biggest issue with 1.5's performance themselves.

**Comment by Kobata** [comment]
Cannot reproduce with OptiFine_1.5.2_HD_U_D3 and Forge 7.8.0.707, using default or a 32x texture pack with a custom font.
