### ISSUE TITLE
Advertisement removal Options

### ISSUE THREAD

**Issue by StoneLegion** [Inventory-Tweaks/inventory-tweaks#331]
**Minecraft Version:** 1.7.10
**Inventory Tweaks Version:** 1.59-dev-152

Issue:
InvTweaks: Configuration loaded.

This displays in chat everytime you go into the game. I think it would be proper to have a option to turn it off or at least have a forced option to have the same spam from my other 250 mods installed <3

**Comment by Kobata** [comment]
There was an option added a long time ago for this, but it may not have suppressed that specifc message until more recently.

1.7.10 will not get any updates.
