### ISSUE TITLE
IndexOutOfBoundsException at InvTweaksContainerManager.getSlot (line 344)

### ISSUE THREAD

**Issue by Robijnvogel** [Inventory-Tweaks/inventory-tweaks#335]
**Minecraft Version: 1.7.10**
**Inventory Tweaks Version: 1.59-dev-156**

[This](http://pastebin.com/bbUFZyWv) happens to one of my players. I have no background information.
I am using that version of InvTweaks, because it solves another, possibly related issue with auto-refilling one's tinkers' tool with a full inventory that causes an ArrayOutOfBounds (not -1, but too high) as well.

**Comment by Kobata** [comment]
Try 1.8.9.

**Comment by Robijnvogel** [comment]
Nice act of passive aggression...
Let me return the favour: "1.8.9 mods don't work on MC 1.7.10"

I know that 1.7.10 is not supported anymore and I don't really think I care if this issue gets solved or not. I am just letting you know that this happens and whatever you do with that information is up to you.
