### ISSUE TITLE
version 1.9 not working in game but shows in mod list

### ISSUE THREAD

**Issue by scalda** [Inventory-Tweaks/inventory-tweaks#337]
I just downloaded the 1.9 version of Inventory Tweaks mod and installed it in my instance with forge version 12.16.0.1802 and for some reason it's not working. 

The mod is in the mod list, but it's not working in game.

any ideas

regards

scalda

**Comment by Kobata** [comment]
This used to be a fairly common error from people installing it incorrectly and causing one part to not work, so I have a decent idea where to start looking.

**Comment by scalda** [comment]
That's great thanks for the response. I'm happy to test any new builds for you
