### ISSUE TITLE
Minor 1.9 issues

### ISSUE THREAD

**Issue by Kobata** [Inventory-Tweaks/inventory-tweaks#339]
- [x] Auto-refill triggers when swapping an item into the offhand slot
- [x] Sorting completely ignored the offhand slot (This is likely to stay as-is, since fixing it would involve touching things I'd rather not at the moment)
- [x] Default item tree file still needs all the new items added

**Comment by Sailren** [comment]
the game crashes as soon as you change the button which is assigned to sort inventory, it also crashes when u reload the client with the changed button as soon the game ticks for the first time

**Comment by Sailren** [comment]
at.invtweaks.InvTweaks.isSortingShortcutDown (InvTweaks.java:960)
at.invtweaks.InvTweaks.onTick(InvTweaks.java:503)
at.invtweaks.InvTweaks.onTickInGui(InvTweaks.java:203)

i have to do it like this because my net is broken right now and my phone is the only way for now

**Comment by Kobata** [comment]
@Sailren Please make a separate issue. I just tested and didn't crash when changing the keybinding myself though.
