### ISSUE TITLE
Crash upon hitting a block

### ISSUE THREAD

**Issue by Scubadog2000** [Inventory-Tweaks/inventory-tweaks#340]
Minecraft 1.9
Inventory Tweaks 1.61-dev-45

I'm aware that this is a very, very unstable version, but I figured a stray crash report might help. The game seems to crash whenever hitting any block at all, as I tried mining with a pickaxe, hand etc. I only have InvTweaks installed with forge. Apologies if this is not the right place to post this.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  FMLPlugin (InventoryTweaks-1.61-dev-45.jar)
Contact their authors BEFORE contacting forge

// Oh - I know what I did wrong!

Time: 16.24.3 17:33
Description: Unexpected error

java.lang.ArrayIndexOutOfBoundsException: 30
    at net.minecraft.client.renderer.block.model.BakedQuadRetextured.func_178217_e(BakedQuadRetextured.java:26)
    at net.minecraft.client.renderer.block.model.BakedQuadRetextured.<init>(BakedQuadRetextured.java:17)
    at net.minecraft.client.renderer.block.model.SimpleBakedModel$Builder.func_188644_a(SourceFile:114)
    at net.minecraft.client.renderer.block.model.SimpleBakedModel$Builder.<init>(SourceFile:100)
    at net.minecraftforge.client.ForgeHooksClient.getDamageModel(ForgeHooksClient.java:620)
    at net.minecraft.client.renderer.BlockRendererDispatcher.func_175020_a(BlockRendererDispatcher.java:47)
    at net.minecraft.client.renderer.RenderGlobal.func_174981_a(RenderGlobal.java:1903)
    at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1338)
    at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1229)
    at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1038)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1072)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:366)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at net.minecraft.client.renderer.block.model.BakedQuadRetextured.func_178217_e(BakedQuadRetextured.java:26)
    at net.minecraft.client.renderer.block.model.BakedQuadRetextured.<init>(BakedQuadRetextured.java:17)
    at net.minecraft.client.renderer.block.model.SimpleBakedModel$Builder.func_188644_a(SourceFile:114)
    at net.minecraft.client.renderer.block.model.SimpleBakedModel$Builder.<init>(SourceFile:100)
    at net.minecraftforge.client.ForgeHooksClient.getDamageModel(ForgeHooksClient.java:620)
    at net.minecraft.client.renderer.BlockRendererDispatcher.func_175020_a(BlockRendererDispatcher.java:47)
    at net.minecraft.client.renderer.RenderGlobal.func_174981_a(RenderGlobal.java:1903)
    at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1338)
    at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1229)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityPlayerSP['Scubadog_'/420, l='MpServer', x=-64,01, y=87,00, z=262,57]]
    Chunk stats: MultiplayerChunkCache: 625, 625
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: World: (-68,64,252), Chunk: (at 12,4,12 in -5,15; contains blocks -80,0,240 to -65,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
    Level time: 198247 game time, 202266 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
    Forced entities: 104 total; [EntityChicken['Chicken'/256, l='MpServer', x=-42,89, y=72,00, z=189,31], EntityChicken['Chicken'/258, l='MpServer', x=-37,99, y=71,00, z=191,68], EntitySquid['Squid'/260, l='MpServer', x=-44,60, y=61,32, z=209,33], EntityChicken['Chicken'/261, l='MpServer', x=-47,20, y=63,00, z=292,80], EntityChicken['Chicken'/272, l='MpServer', x=-18,17, y=72,00, z=266,78], EntityChicken['Chicken'/273, l='MpServer', x=-30,51, y=76,00, z=268,16], EntityChicken['Chicken'/274, l='MpServer', x=-22,50, y=72,00, z=267,31], EntityChicken['Chicken'/275, l='MpServer', x=-28,11, y=77,00, z=280,20], EntityChicken['Chicken'/276, l='MpServer', x=-24,51, y=72,00, z=282,57], EntityChicken['Chicken'/277, l='MpServer', x=-15,70, y=70,00, z=277,06], EntityChicken['Chicken'/278, l='MpServer', x=-30,44, y=72,00, z=286,19], EntityItem['item.item.egg'/279, l='MpServer', x=-22,03, y=72,00, z=278,97], EntityItem['item.item.egg'/280, l='MpServer', x=-21,13, y=74,00, z=272,45], EntityCreeper['Creeper'/290, l='MpServer', x=-6,50, y=16,00, z=193,50], EntityCreeper['Creeper'/291, l='MpServer', x=-12,50, y=47,00, z=226,50], EntitySkeleton['Skeleton'/292, l='MpServer', x=-9,50, y=48,00, z=224,50], EntityChicken['Chicken'/293, l='MpServer', x=-2,34, y=71,00, z=238,16], EntityItem['item.item.egg'/294, l='MpServer', x=-2,93, y=71,00, z=237,33], EntitySkeleton['Skeleton'/298, l='MpServer', x=14,73, y=28,00, z=222,50], EntityBat['Bat'/299, l='MpServer', x=4,96, y=35,10, z=212,61], EntityBat['Bat'/300, l='MpServer', x=-3,53, y=49,05, z=228,19], EntityZombie['Zombie'/301, l='MpServer', x=4,73, y=21,76, z=239,68], EntityCreeper['Creeper'/302, l='MpServer', x=7,50, y=35,00, z=228,50], EntityCreeper['Creeper'/303, l='MpServer', x=3,07, y=46,00, z=221,68], EntityCreeper['Creeper'/304, l='MpServer', x=3,50, y=38,00, z=230,50], EntityChicken['Chicken'/305, l='MpServer', x=3,58, y=70,00, z=264,78], EntityChicken['Chicken'/306, l='MpServer', x=3,48, y=69,00, z=273,13], EntityBat['Bat'/322, l='MpServer', x=15,86, y=31,10, z=243,87], EntityChicken['Chicken'/92, l='MpServer', x=-132,11, y=67,00, z=188,69], EntitySkeleton['Skeleton'/94, l='MpServer', x=-130,50, y=31,00, z=198,50], EntityChicken['Chicken'/95, l='MpServer', x=-132,23, y=67,61, z=208,68], EntitySpider['Spider'/96, l='MpServer', x=-135,50, y=17,00, z=217,50], EntitySkeleton['Skeleton'/97, l='MpServer', x=-138,50, y=23,00, z=238,50], EntityCreeper['Creeper'/98, l='MpServer', x=-133,50, y=21,00, z=234,50], EntitySkeleton['Skeleton'/99, l='MpServer', x=-141,50, y=42,00, z=238,50], EntityCreeper['Creeper'/100, l='MpServer', x=-138,50, y=44,00, z=225,50], EntityZombie['Zombie'/101, l='MpServer', x=-138,47, y=39,00, z=244,28], EntitySkeleton['Skeleton'/116, l='MpServer', x=-123,50, y=22,00, z=190,50], EntityZombie['Zombie'/117, l='MpServer', x=-121,50, y=20,00, z=187,50], EntityCow['Cow'/118, l='MpServer', x=-127,12, y=67,00, z=189,13], EntityCreeper['Creeper'/119, l='MpServer', x=-125,50, y=19,00, z=206,50], EntityCreeper['Creeper'/120, l='MpServer', x=-120,50, y=32,00, z=193,50], EntityChicken['Chicken'/121, l='MpServer', x=-126,42, y=63,00, z=204,82], EntityItem['item.item.egg'/122, l='MpServer', x=-126,98, y=63,00, z=203,36], EntityZombie['Zombie'/123, l='MpServer', x=-122,50, y=18,00, z=223,50], EntityBat['Bat'/124, l='MpServer', x=-122,55, y=35,27, z=223,16], EntityZombie['Zombie'/125, l='MpServer', x=-126,63, y=55,00, z=211,50], EntityCreeper['Creeper'/126, l='MpServer', x=-118,50, y=51,00, z=213,50], EntityZombie['Zombie'/127, l='MpServer', x=-119,25, y=23,00, z=232,56], EntityBat['Bat'/128, l='MpServer', x=-114,18, y=32,21, z=237,45], EntityZombie['Zombie'/129, l='MpServer', x=-121,51, y=52,00, z=230,30], EntityWitch['Witch'/130, l='MpServer', x=-112,50, y=43,00, z=242,50], EntityZombie['Zombie'/131, l='MpServer', x=-116,50, y=27,00, z=259,50], EntityChicken['Chicken'/132, l='MpServer', x=-113,83, y=74,00, z=299,49], EntityItem['item.item.egg'/133, l='MpServer', x=-113,29, y=74,00, z=298,87], EntityChicken['Chicken'/134, l='MpServer', x=-127,88, y=70,00, z=291,10], EntityChicken['Chicken'/151, l='MpServer', x=-105,77, y=68,00, z=187,50], EntityCreeper['Creeper'/152, l='MpServer', x=-104,33, y=19,00, z=200,81], EntityCreeper['Creeper'/153, l='MpServer', x=-101,50, y=33,00, z=193,50], EntitySpider['Spider'/154, l='MpServer', x=-107,50, y=37,00, z=197,50], EntityCreeper['Creeper'/155, l='MpServer', x=-96,50, y=39,00, z=209,50], EntityZombie['Zombie'/156, l='MpServer', x=-100,50, y=22,00, z=230,50], EntityCreeper['Creeper'/157, l='MpServer', x=-104,50, y=18,00, z=239,50], EntityBat['Bat'/158, l='MpServer', x=-99,48, y=21,28, z=236,78], EntitySkeleton['Skeleton'/159, l='MpServer', x=-107,50, y=43,00, z=241,50], EntitySkeleton['Skeleton'/160, l='MpServer', x=-96,50, y=40,00, z=240,50], EntityBat['Bat'/161, l='MpServer', x=-109,75, y=36,46, z=242,76], EntityZombie['Zombie'/162, l='MpServer', x=-106,50, y=25,00, z=256,50], EntityCreeper['Creeper'/163, l='MpServer', x=-107,51, y=28,00, z=251,80], EntityCreeper['Creeper'/164, l='MpServer', x=-105,50, y=24,00, z=258,50], EntityChicken['Chicken'/165, l='MpServer', x=-102,50, y=69,00, z=284,81], EntityItem['item.item.egg'/166, l='MpServer', x=-101,56, y=69,00, z=284,80], EntityChicken['Chicken'/167, l='MpServer', x=-108,49, y=66,00, z=318,77], EntityItem['item.item.egg'/168, l='MpServer', x=-107,93, y=66,00, z=318,45], EntityChicken['Chicken'/169, l='MpServer', x=-115,16, y=77,00, z=332,61], EntityPlayerSP['Scubadog_'/420, l='MpServer', x=-64,01, y=87,00, z=262,57], EntityCreeper['Creeper'/199, l='MpServer', x=-87,50, y=14,00, z=183,50], EntityBat['Bat'/201, l='MpServer', x=-90,53, y=32,62, z=197,49], EntityChicken['Chicken'/202, l='MpServer', x=-90,16, y=67,00, z=200,50], EntityItem['item.item.egg'/203, l='MpServer', x=-90,79, y=67,00, z=199,63], EntityChicken['Chicken'/204, l='MpServer', x=-89,31, y=70,55, z=217,50], EntityCreeper['Creeper'/205, l='MpServer', x=-89,50, y=23,00, z=241,50], EntityBat['Bat'/206, l='MpServer', x=-85,56, y=19,77, z=253,84], EntityBat['Bat'/207, l='MpServer', x=-92,28, y=27,12, z=253,26], EntityBat['Bat'/208, l='MpServer', x=-104,16, y=18,25, z=252,35], EntityEnderman['Enderman'/209, l='MpServer', x=-91,52, y=40,00, z=252,44], EntityCreeper['Creeper'/210, l='MpServer', x=-92,50, y=32,00, z=258,50], EntityBat['Bat'/211, l='MpServer', x=-86,63, y=41,74, z=270,07], EntitySpider['Spider'/212, l='MpServer', x=-85,50, y=40,00, z=275,50], EntityChicken['Chicken'/213, l='MpServer', x=-82,49, y=73,00, z=302,77], EntityChicken['Chicken'/214, l='MpServer', x=-84,25, y=72,00, z=303,98], EntityItem['item.item.egg'/215, l='MpServer', x=-82,32, y=73,00, z=302,50], EntityItem['item.item.egg'/216, l='MpServer', x=-84,01, y=72,00, z=303,28], EntityItem['item.item.egg'/217, l='MpServer', x=-80,58, y=73,00, z=300,13], EntityChicken['Chicken'/218, l='MpServer', x=-86,63, y=70,63, z=312,74], EntityChicken['Chicken'/221, l='MpServer', x=-84,66, y=67,26, z=341,83], EntityChicken['Chicken'/238, l='MpServer', x=-76,84, y=74,00, z=300,50], EntityChicken['Chicken'/239, l='MpServer', x=-70,76, y=79,00, z=330,45], EntityChicken['Chicken'/240, l='MpServer', x=-79,76, y=74,00, z=332,52], EntityChicken['Chicken'/242, l='MpServer', x=-77,50, y=64,00, z=340,50], EntityItem['item.item.egg'/249, l='MpServer', x=-51,21, y=80,00, z=268,13], EntityZombie['Zombie'/250, l='MpServer', x=-57,50, y=36,00, z=290,50], EntityZombie['Zombie'/251, l='MpServer', x=-67,71, y=70,84, z=302,49], EntityItem['item.item.egg'/252, l='MpServer', x=-50,75, y=64,00, z=288,39]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:409)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2647)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:395)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.9
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 422266752 bytes (402 MB) / 774803456 bytes (738 MB) up to 1060372480 bytes (1011 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
    FML: MCP 9.23 Powered by Forge 12.16.0.1766 4 mods loaded, 4 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAA   FML{8.0.99.99} [Forge Mod Loader](forge-1.9-12.16.0.1766-1.9.jar) 
    UCHIJAAAA   Forge{12.16.0.1766} [Minecraft Forge](forge-1.9-12.16.0.1766-1.9.jar) 
    UCHIJAAAA   inventorytweaks{1.61-dev-45-29e0ed5} [Inventory Tweaks](InventoryTweaks-1.61-dev-45.jar) 
    Loaded coremods (and transformers): 
FMLPlugin (InventoryTweaks-1.61-dev-45.jar)
  invtweaks.forge.asm.ContainerTransformer
    GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 353.30' Renderer: 'GeForce GTX 960M/PCIe/SSE2'
    Launched Version: 1.9-forge1.9-12.16.0.1766-1.9
    LWJGL: 2.9.4
    OpenGL: GeForce GTX 960M/PCIe/SSE2 GL version 4.5.0 NVIDIA 353.30, NVIDIA Corporation
    GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

```
Using VBOs: No
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: 
Current Language: English (US)
Profiler Position: N/A (disabled)
CPU: 8x Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz
```

**Comment by Kobata** [comment]
Try without Inventory Tweaks, because I don't see anything that seems likely to be my fault.
