### ISSUE TITLE
[1.9b1811] inventorytweaks{1.61-dev-45-29e0ed5} crashes client on startup

### ISSUE THREAD

**Issue by kreezxil** [Inventory-Tweaks/inventory-tweaks#342]
fml latest: http://paste.ee/p/Sk940

crash report: http://paste.ee/p/du8wR

**Comment by Kobata** [comment]
Forge messed with stuff, don't expect it to be fixed until 1.9.1.

Use older versions of Forge if you really want to play 1.9 _right now_

**Comment by Sailren** [comment]
why are people uploading whole launcher logs instead of the crash report itself? do i have to scroll 5 minutes down just to read a few lines of text?

**Comment by tiarnia** [comment]
yeah but you cant use half the new mods if you use older forge

**Comment by modmuss50** [comment]
Is there any update on this now that a rb version of forge is out. I could work on a PR to allow it to fix this major issue. It's preventing my mod from working with yours.

**Comment by Kobata** [comment]
I'm still not planning on doing anything about forge breaking things until they do an MC version update (which, at this point, is probably going to be 1.6.3)

If you could somehow manage to get forge to accept a change to not actually deny access to the variables, it could be resolved that way for the moment, or a separate mod can use reflection to make the needed variables accessible.

**Comment by hron84** [comment]
Is there any way to for example disable the affected feature? I agree you do not want to mess up with broken Forge stuffs but we, players want to use your mod because it is still awesome and essential for many people. I do not know so much about programming, but if we can find a solution for this problem, it would be good. Even if we have to miss some features.

**Comment by JCMais** [comment]
This fork has it working: https://github.com/TehNut/inventory-tweaks

You just need to recompile the mod, follow the wiki, there is a tutorial there. I'm using it right now.

**Comment by TehNut** [comment]
@JCMais There is a [pre-compiled build](https://github.com/TehNut/inventory-tweaks/releases/tag/1.61-1.9Fix) in the releases tab.

**Comment by hron84** [comment]
@TehNut Thanks for your hard work, I really appreciate it.
