### ISSUE TITLE
Crash on shield break

### ISSUE THREAD

**Issue by SViking** [Inventory-Tweaks/inventory-tweaks#345]
*_Minecraft Version:1.9
*_Inventory Tweaks Version: 1.61-dev-45-29e0ed45

When a shield in use breaks, Inventory Tweaks causes MC to crash.

**Comment by Kobata** [comment]
Log file?

**Comment by SViking** [comment]
[crash-2016-04-07_14.58.42-server.txt](https://github.com/Inventory-Tweaks/inventory-tweaks/files/209611/crash-2016-04-07_14.58.42-server.txt)

Re-created the issue to make sure I was giving you the applicable crash report.

**Comment by Kobata** [comment]
I can't see anything directly related to inventory tweaks there.
