### ISSUE TITLE
new 1.9 crash -

### ISSUE THREAD

**Issue by seannyyx** [Inventory-Tweaks/inventory-tweaks#349]
**Minecraft Version:** 1.9
**Inventory Tweaks Version:** 1.61 dev 45
**

pastee of bug crash report *\* https://paste.ee/p/rRRUL

**Comment by NaiyasFury** [comment]
Can confirm. I'm getting the same crash as well.

**Comment by TehNut** [comment]
This should be fixed when/if #347 gets merged. I built and uploaded a fixed version [here](https://github.com/TehNut/inventory-tweaks/releases/tag/1.61-1.9Fix) if you wish to temporarily use it.

**Comment by ProsperCraft** [comment]
http://pastebin.com/fLpQGvJA

I am getting it as well.

**Comment by Kobata** [comment]
#342
