### ISSUE TITLE
Invalid Keywords

### ISSUE THREAD

**Issue by Simantic** [Inventory-Tweaks/inventory-tweaks#352]
*_Minecraft Version: release 1.9-LiteLoader1.9-1.9-forge1.9-12.16.0.1867-1.9 *_
*_Inventory Tweaks Version: 1.61-dev-44-8aeffff *_

I can't seem to get Inventory Tweaks to recognize the mining resources iron ore, gold ore, and lapis lazuli.  I've tried several different keywords, but I keep getting this:

"InvTweaks: Invalid keywords found: ironOre goldOre dyeBlue"

From what I can tell, the correct keywords should be: ironOre, goldOre, and dyeBlue.  I also tried their id's: iron_ore, gold_ore, and lapis_lazuli, but those didn't work either.  I do have some other mods, but none that have replaced those items as far as I know.  I can still manually use the "give" command with all of their regular id's.

Also, possibly related, I keep an extra pickaxe and shovel with me when I'm mining.  They're set to go to slots C2 and C3, but keep sorting to A1 and A2, where iron ore and gold ore are supposed to go.

If it helps, I've attached my rules config, and a screenshot of what I get when I try to sort.

[InvTweaksRules.txt](https://github.com/Inventory-Tweaks/inventory-tweaks/files/245990/InvTweaksRules.txt)

![2016-05-02_17 55 55](https://cloud.githubusercontent.com/assets/19157384/14969214/36559dd6-108f-11e6-822a-be422ee7f2f9.png)

**Comment by Kobata** [comment]
See the item tree file for the names it is looking for, ex. https://github.com/Inventory-Tweaks/inventory-tweaks/blob/develop/src/main/resources/assets/inventorytweaks/ItemTree.xml#L516

**Comment by Simantic** [comment]
Thanks for the reply.  I did do that, but I see now that I was reading the wrong side of the line.  For iron ore, I thought it was looking for "ironOre", but it was actually "ironOreBlock".  Confusing (I'm not a programmer, so I don't always understand code), but I get it now.

That cleared up that part, but I still don't understand the tools going to the wrong place.  It is trying to sort properly now, but it still wants to put my extra tools into A1, A2, and A3 for some reason, even though I have them set to go to C1, C2, and C3, and other things going to A1-A3.  Is there something else I'm just not understanding?  Sorry if I seem a bit foolish here.  I am trying to understand it.

Thanks
