### ISSUE TITLE
Tabbychat incompatibility

### ISSUE THREAD

**Issue by mattmess1221** [Inventory-Tweaks/inventory-tweaks#353]
**Minecraft Version:1.8.9**
**Inventory Tweaks Version: IDK**

This was discovered by @Xiaminou, so he has more version info.

killjoy1221/TabbyChat-2#51

During init, tabbychat creates the chat gui, and that involves calling a method which you have injected an event into: `GuiTextField.setFocused'. Unfortunately, this happened before your init (Liteloader only has 1 init call), so it ends up calling on a null instance.

**Comment by Kobata** [comment]
There is really no reason to create Minecraft GUI instances (particularly in-game ones) during initialization phases.

**Comment by mattmess1221** [comment]
I think I found a fix on my end anyway. I forgot about the `InitCompleteListener`
