### ISSUE TITLE
Startup crash with Power Advantage mods

### ISSUE THREAD

**Issue by zlyfire** [Inventory-Tweaks/inventory-tweaks#354]
**Minecraft Version: 1.9**  
**Inventory Tweaks Version: 1.61-dev-49-c5b6395**  
Without Cyanobacterium's Power/Steam/Electric Advantage mods, it works perfectly fine. However, installing one of those gives me a startup crash, with [this error log.](http://pastebin.com/h44W4s4U)  
As seen, I have an environment with just those mods installed. This line in Power Advantage that the log calls out is a simple oredict call, nothing more.  
To replicate, simply install the newest Forge, Inventory Tweaks, Base Metals (required by Power Advantage) and Power Advantage. Start the game, and during either init or post-init, it will crash.

**Comment by Kobata** [comment]
#342
