### ISSUE TITLE
[1.9.4] Crash on startup

### ISSUE THREAD

**Issue by GirafiStudios** [Inventory-Tweaks/inventory-tweaks#358]
Inventory Tweaks is crashing on latest version for 1.9.4 (Version 1.61-dev-52) on startup.

Crash report: https://gist.github.com/GirafiStudios/ec33acff669a90242170fc4b5bc85fdd

**Comment by Kobata** [comment]
...well, that's strange.

Workaround: manually extract the tree file, it seems like java is messing it up when extracting it?

**Comment by GirafiStudios** [comment]
I think this is realted to your latest commit, with the potion stuff.

"Caused by: org.xml.sax.SAXParseException; systemId: file:/D:/Minecraft%20Launchers/MultiMC/instances/1.9.4/minecraft/config/InvTweaksTree.txt; lineNumber: 974; columnNumber: 104; An invalid XML character (Unicode: 0x0) was found in the value of attribute "data" and element is "splashPotionWaterBreathingEx"." - In case you didn't notice that :)

**Comment by Kobata** [comment]
Like I said, the file in the jar is fine... it's just getting mangled by the copy out for some reason.

**Comment by Kobata** [comment]
Got a basic fix, it seems like the file got big enough it needed multiple steps to fully read.

**Comment by Luckyfanisaac** [comment]
[crash-2016-06-08_14.10.21-client.txt](https://github.com/Inventory-Tweaks/inventory-tweaks/files/305565/crash-2016-06-08_14.10.21-client.txt)

I tried getting the latest version of the resourcepacks but they didn't show up. ANy help?

**Comment by GirafiStudios** [comment]
That have nothing to do with Inventory Tweaks? It is Journey Map it seems.

**Comment by Luckyfanisaac** [comment]
I can't use any mods now since I tried to install mcpatcher so I'm using a
default account and since I couldn't get the latest texture packs working
I'm using 1.8 ones.
