### ISSUE TITLE
Missing server side component instructions

### ISSUE THREAD

**Issue by maciekish** [Inventory-Tweaks/inventory-tweaks#359]
**Minecraft Version: 1.9.4**
**Inventory Tweaks Version: 1.61-dev53**

I struggle to find the server side sorting component. Am i supposed to install the same .jar as for the client? It's not picked up by bukkit/mcmyadmin.

**Comment by Kobata** [comment]
It's the same jar, and is still a Forge mod, not a bukkit plugin.

A bukkit plugin is theoretically possible -- you just need to have a network channel handler that's compatible and does the 'right thing', but I don't have much familiarity with it, and bukkit's legality is still a rather gray area so it's never been a priority.
