### ISSUE TITLE
crash opn startup

### ISSUE THREAD

**Issue by audenga** [Inventory-Tweaks/inventory-tweaks#361]
**Minecraft Version:** 1.9.4
**Inventory Tweaks Version:** 1.59 dev 152

crash on startup

full log
http://paste.ee/p/oMoq3

i know the instance folder says 1.9.0 but on line 75 it has 1.9.4 and i only have this mod installed

**Comment by Kobata** [comment]
Wrong inventory tweaks version for the MC version.
