### ISSUE TITLE
1.9 Crash on startup

### ISSUE THREAD

**Issue by partment** [Inventory-Tweaks/inventory-tweaks#362]
*_Minecraft Version: 1.9-forge1.9-12.16.1.1887
*_Inventory Tweaks Version: 1.61-dev-49
[crash-2016-06-07_18.49.49-client.txt](https://github.com/Inventory-Tweaks/inventory-tweaks/files/302372/crash-2016-06-07_18.49.49-client.txt)

**Comment by Kobata** [comment]
Wrong file, you got the development version of the jar.
