### ISSUE TITLE
ProjectE inventories don't sort

### ISSUE THREAD

**Issue by damianon** [Inventory-Tweaks/inventory-tweaks#364]
**Minecraft Version: 1.9.4**
**Inventory Tweaks Version: beta-54**

sorting any inventory from project E does not work properly. on the 1st (middle mouse) click, it alings all items continuously. So when there are gaps, they will be filled. But it doesn't sort the items. They stay in random order. On the second click i get the message "Error Failed to sort container: null (l101 in HandlerSorting.java)".

Applies to Alchemical Chests and Bags from Project E. IronChests mod works fine, so it might be an issue from Project E.

**Comment by Kobata** [comment]
Non-vanilla inventories are not directly supported, as inventory tweaks has to rely on information from those mod's authors to know what parts of the inventory have what purpose.
