### ISSUE TITLE
Strange bug with Inv Tweaks

### ISSUE THREAD

**Issue by Vaolin** [Inventory-Tweaks/inventory-tweaks#366]
**Minecraft Version: 1.7.10**
**Inventory Tweaks Version: 1.59-dev-152**

Doesn't matter how i change setting always same slots are locked (red marks)
eaven when setting were clear:
http://screenshooter.net/100299497/coygolf

**Comment by Kobata** [comment]
That looks like TerraFirmaCraft, and the offset is just enough for the extra slots from a larger crafting space, so that's probably because they don't have a custom handler to tell invtweaks what's actuallly the inventory.
