### ISSUE TITLE
Error with Obsidian Chest Sorting

### ISSUE THREAD

**Issue by dirthsj** [Inventory-Tweaks/inventory-tweaks#368]
**Minecraft Version:** Minecraft 1.8.9 (1.8.9-11.15.1.1890-1.8.9/fml,forge)
**Inventory Tweaks Version:** 1.60-40-e06e29a (1.60-40-e06e29a)

When attempting to sort an obsidian chest from Iron Chests (6.0.125 build 770) on a [server](http://www.technicpack.net/modpack/officialswitchcraft.863735)*, I get an error message in chat and the chest does not sort.
`InvTweaks: [ERROR] [3] Failed to sort container: null (l101 in HandlerSorting..java)`

Strangely, the owner of the server (BTC) was able to sort the exact chest which I attempted to sort without problems.  I have not tested with other players, yet.

All other chests (including those from Iron Chests) are sortable with no issue, both for me and other players (at least, nobody has said anything about being unable to sort chests).

*the modpack includes the server IP

**Edit: Moar Informations!**
Default Sorting button (the one that looks like a Z) works just fine

**Comment by Kobata** [comment]
Sounds like #343
