### ISSUE TITLE
Sorting not working in some modded inventories

### ISSUE THREAD

**Issue by TheWhiteWolves** [Inventory-Tweaks/inventory-tweaks#369]
**Minecraft Version: 1.10.2**
**Forge Version: 12.18.0.2009**
**Inventory Tweaks Version: 1.61-58**

I have noticed that Inventory tweaks is having issues sorting items inside the inventories of containers from other mods, an example is the Extra Utilities 2 Bag of Holding and the Global Ender Chests from Ender Things.

It does seem to work fine in the inventories of the Iron Chests mod though.

Thought I should let you know, in case you didn't already.

**Comment by Hund** [comment]
EnderBags doesn't work either. It's a pain in the but to sort it manually. :D

**Comment by Kobata** [comment]
I'm not doing any special for mods, it's their job to make sure inventory tweaks has the correct information to be able to sort.

**Comment by Syndaryl** [comment]
Where's the documentation on what the correct information is and how to send it? If they aren't doing it now, it's most likely because they don't know they're doing something wrong, so when I submit bugs with them I'm going to get a lot of blank stares and shrugs.
