### ISSUE TITLE
Suggestion to add to the config file.

### ISSUE THREAD

**Issue by megamanzteam** [Inventory-Tweaks/inventory-tweaks#37]
Adding a config option to have the chest buttons on the left or right GUI. This should help with NEI items blocking the right side buttons.

**Comment by Kobata** [comment]
Anything big enough that NEI causes issues should already have its buttons move onto the border of the GUI, where there would be bigger issues if it was getting covered by items.

**Comment by megamanzteam** [comment]
![Capture](https://f.cloud.github.com/assets/4212359/405760/a4038d8a-aa07-11e2-8764-3d085d0e918e.PNG)
![Capture2](https://f.cloud.github.com/assets/4212359/405761/a4199fee-aa07-11e2-8c06-499de863285f.PNG)
Here is a screenshot of what I mean that the buttons get blocked. I use the Large UI setting, not auto. That might be causing the issue. Thus the suggestion I had earlier.

**Comment by Kobata** [comment]
From the looks of your screenshots you're using a 1.4.7 version which has NEI detection horribly broken, current 1.5 versions correctly detect NEI being active and move the buttons closer to the chest GUI.
