### ISSUE TITLE
Adding mod Items

### ISSUE THREAD

**Issue by Vintorez96** [Inventory-Tweaks/inventory-tweaks#371]
**Minecraft Version:1.7.10 Feed the beast Evolved**
*_Inventory Tweaks Version: InventoryTweaks-1.59-dev-152 *_

Not managing to sort mod items, and have tried to add the mod items with both item id and item name from "to meny item". i have manage to do this when i used this mod a few years back. i have also tried to add the mod items i want to sort in the "item tree file".

and if this is not a mod issue, may i have some examples on how to sort my mod items and add theme in my "tree file" ?

**Comment by Kobata** [comment]
http://inventory-tweaks.readthedocs.io/en/latest/#tweaking-the-item-tree
