### ISSUE TITLE
Bug with Actually Additions Storage Crate Sorting

### ISSUE THREAD

**Issue by Ellpeck** [Inventory-Tweaks/inventory-tweaks#373]
Minecraft Version: 1.10.2
InvTweaks Version: Apparently any

I keep having the same issue that I have no idea how to fix myself. 
I have the Actually Additions Storage crate with [this ](https://github.com/Ellpeck/ActuallyAdditions/blob/master/src/main/resources/assets/actuallyadditions/textures/gui/guiGiantChest.png) sort of GUI and slot amount and layout.

To make the crate InvTweaks compatible, I just added 

`@ChestContainer(rowSize = 13, isLargeChest = true)`

to the top of the Container class.
And whenever sorting with any but the Z-button mode, this error is printed into the chat.

> InvTweaks: [ERROR] [3] Failed to sort container: null (l101 in HandlerSorting.java)

I have no idea how I could fix this. :v

**Comment by Kobata** [comment]
See #343 alternate sorting modes do not currently work if rowSize is greater than 9.

**Comment by GeneralAtrox** [comment]
Does this error also remove items? Ive noticed items disappearing but I have no clue where to.

**Comment by Twisted-Code** [comment]
Okay good, I'm not the only person having trouble with AA's crates... hmm, given it's (from what I understand without inspecting the code) a simple matter of an array being too big, I don't suppose this is fixed or will be fixed in the near future?
