### ISSUE TITLE
Sorting not working correctly

### ISSUE THREAD

**Issue by Nuinethir** [Inventory-Tweaks/inventory-tweaks#374]
**Minecraft Version:** 1.10.2-forge1.10.2-12.18.1.2011
**Inventory Tweaks Version:** InventoryTweaks-1.61-58

The image below shows what's happening...

http://i.imgur.com/rkZWazC.png

It works right up until it gets past dirt, where minecraft:log (17) is being placed before minecraft:gravel (13). Then, you can see minecraft:plank (5) ahead of minecraft:wool (35). It keeps groups together, but they are incorrectly sorted.

There are probably other sorting errors, but I just noticed this since jumping from MC1.7.10 to MC1.10.2. It used to sort just fine. I only noticed this because I used to be a server admin and know most of the IDs by heart.

Thanks for reading.

**Comment by Kobata** [comment]
Items are not ordered by numerical ID, but rather the order in the tree file, followed by lexical comparison of their string IDs for items that are not in the predefined set.

**Comment by Nuinethir** [comment]
Got it. Thanks for the info. :+1:
