### ISSUE TITLE
Reliquary/IT crash

### ISSUE THREAD

**Issue by the-creamster** [Inventory-Tweaks/inventory-tweaks#377]
Minecraft: 1.10.2
forge: build 2042
Inventory Tweaks :1.61-58
Reliquary: 1.3.3.455

https://gist.github.com/the-creamster/109ea4f4d178c202a58a703ed3e3ac0f
I got this while testing out a Reliquary item(Destruction Catalyst) and it occurred approx 5min after starting to use it. Going to link this to the Reliquary github.

**Comment by Kobata** [comment]
The farthest it gets in invtweaks is `hotbarClone[i] = mainInventory[i].copy();` so it seems like something Reliquary is trying to do while copying an item stack is failing?
