### ISSUE TITLE
Enhancement array of items per slot added

### ISSUE THREAD

**Issue by JFMillerUSA** [Inventory-Tweaks/inventory-tweaks#379]
Would it be possible to have an array added to the slot rules i.e.

D1 woodSword, ironSword, diamondSword
D2 woodPickaxe, ironPickaxe, diamondPickaxe
D3 woodShovel, ironShovel, diamondShovel
D4 woodAxe, ironAxe, diamondAxe
D5 regenerationPotion, healingPotion
D6 stones
D7 negativePotion, negativeSplashPotion
D8 edibleFood
D9 lighting

When you have certain items they'll fill the slots first when you run out the next fills the slot if you have it in your inventory and so on.

**Comment by Kobata** [comment]
This feels like the use case for the categories in the tree file?

For instance 'sword', 'pickaxe' etc.

The default ordering prefers to give you the 'best' one, but that's easy to change with your own edits to the order in that file.
