### ISSUE TITLE
Chests on Multiplayer bug.

### ISSUE THREAD

**Issue by Researcher123** [Inventory-Tweaks/inventory-tweaks#38]
When I use the sorting button on chests on multiplayer. It automatically picks up and item and it resets the chest. I dont know if this is because an plug-in or something else. What do I do to make the chest sorting work?

**Comment by ChrisLane** [comment]
This only ever happens with certain items for me, what mods are you running and which item does it pick up?
You'll likely find if you empty the chest of that item it will sort normally, not sure why this happens.

**Comment by Kobata** [comment]
Make sure there's no nocheat plugin on the server, and if it's running mods (and is 1.5 -- I can't help for 1.4.7 servers) make sure Inventory Tweaks is installed on the server as well.

**Comment by ChrisLane** [comment]
InvTweaks can be installed on the server? Well I'll be damned.
I have NoCheatPlus installed on the server however the fast move inventory check is disabled so it works normally for everything except one item.

I've seen this happen before on ftb packs on servers without nocheat and with invtweaks installed on the server.

What does invtweaks being installed on the server do by the way? O_o

**Comment by Kobata** [comment]
The server module lets the mod bypass some validation checks in the vanilla click-handler code that cause issues moving certain mod items (Mystcraft books, occasionally some IC2/forestry items, probably various things from other mods I can't remember quickly). For vanilla/non-MCPC-bukkit servers it doesn't matter very much, as only mod items trigger that particular issue repeatedly.
