### ISSUE TITLE
Middle click does not optimize crafting input

### ISSUE THREAD

**Issue by scanstone** [Inventory-Tweaks/inventory-tweaks#383]
**Minecraft Version: 1.10.2**
**Inventory Tweaks Version: 1.61-58**
**Forge Version: 12.18.1.2011**
**Java Runtime: OpenJDK JRE 8.u102-1**
**OS: Linux**
Using default launcher and ingame settings, music turned off.

Steps to reproduce:
1. Open inventory
2. Add items to crafting area in non-optimal configuration (e.g. 3 planks above, 1 below, output sticks)
3. Middle click anywhere in crafting area
The result is items returning to a stack in top left corner of crafting area.

Video: https://youtu.be/edvituRR6Ms

**Comment by Programie** [comment]
Same here with 1.12.2. How did you fix it?
