### ISSUE TITLE
Compatibility: Bagginses-1.10-3.0+

### ISSUE THREAD

**Issue by Syndaryl** [Inventory-Tweaks/inventory-tweaks#384]
**Minecraft Version:** 1.10.2
**Inventory Tweaks Version:** InventoryTweaks-1.61-58
**Forge Version:** 12.18.1.2065

Inventory Tweaks isn't working with [Bagginses bags](https://minecraft.curseforge.com/projects/bagginses?gameCategorySlug=mc-mods&projectID=223005) - No middle-click sorting of the bag contents nor of my inventory, no inventory buttons, etc.

**Comment by Kobata** [comment]
See #369
