### ISSUE TITLE
Crash while connecting

### ISSUE THREAD

**Issue by utoc** [Inventory-Tweaks/inventory-tweaks#385]
Running MC 1.10.2, FML 2073 and InvTweaks 1.61-58

Every now and again, my users and I are running into this crash: http://pastebin.com/eMH1WSiM

It happens while connecting and results in a client crash.  I can't make it happen on command, however, it does happen more frequently if the client was on SMP, disconnected and went into SSP (to test something in creative) and then attempts to reconnect to the server.

**Comment by Kobata** [comment]
https://github.com/Inventory-Tweaks/inventory-tweaks/blob/develop/src/main/java/invtweaks/InvTweaksObfuscation.java#L282

Looks like maybe it's starting client ticks before the player properly exists for... some weird reason? That probably shouldn't be happening to begin with.

**Comment by utoc** [comment]
Something else to add to this issue: It almost always follows the player timing out during the connection phase where they stayed on the server for 1-3 seconds and then timed out for whatever reason.

**Comment by MysticAura** [comment]
Can confirm. Someone on my server is having the same issue. Twice in one night, same crash log. Same mod and mc version. He is also having the time out issue on first connection to the server.
[Crash Log](http://pastebin.com/hgZrJGwX)

**Comment by utoc** [comment]
Just a kind heads up; this is still happening.  It only happens once the player has been connected to the server, disconnects for example to go to single player for testing, and then reconnects to the server.  It doesn't always crash when the user logs back in but the scenario leading up to the crash is consistent.

**Comment by Eufranio** [comment]
Still happening.

**Comment by Kobata** [comment]
I didn't link this to the other ones for some reason, but e073cca should fix this as well.
