### ISSUE TITLE
Sort buttons can't be clicked when they overlap JEI

### ISSUE THREAD

**Issue by InsaneJ** [Inventory-Tweaks/inventory-tweaks#386]
**Minecraft Version:** 1.10.2
**Inventory Tweaks Version:** 1.61-58
- Set GUI scale to auto.
- Open an iron chest or other large inventory.
- The sort buttons on the top-right overlap with JEI.
- The sort buttons can't be clicked, instead you're selecting items in JEI.

The sort button tool tips appear. But you can't seem to click them.
Tested with ironchest-1.10.2-7.0.9.796 and jei_1.10.2-3.9.0.244.

**Comment by Kobata** [comment]
This only even works with NEI because there's a bit to specifically move them when it's active, and I have never even looked at JEI to see if it's simple to detect yet.

**Comment by InsaneJ** [comment]
JEI has, in NEI's absence, performed the recipe lookup function for Minecraft 1.8 and 1.9. Only recently has NEI been ported to 1.10 but it's still a bit shaky. Would you consider adding JEI support?

**Comment by Kobata** [comment]
I tried to look into how to figure out if JEI is visible, but I don't know my way around it, so I think for this the best solution is for someone who knows JEI's code better to do a PR in the style of the NEI checks (i.e., use Forge/FML functions and reflection -- no direct references to anything from other mods)

**Comment by thetaCriterion** [comment]
Hey guys. I experienced what I _think_ is a related issue to this, and [reported the issue to JEI](https://github.com/mezz/JustEnoughItems/issues/519). They directed me here. Thought you might want to see their comment on the issue, in case it's helpful to you?

**Comment by mezz** [comment]
I think I can PR a fix later. Please ping me in a few days if I forget.

**Comment by mezz** [comment]
Made the PR:

![2016-10-14_01 11 23](https://cloud.githubusercontent.com/assets/916092/19380306/8fa7afd0-91ab-11e6-9215-20d8a4c6bcf7.png)

![2016-10-14_01 03 34](https://cloud.githubusercontent.com/assets/916092/19380325/a9100a94-91ab-11e6-8ec3-94d1c9236a3f.png)

All the Inventory-Tweaks buttons are clickable without activating JEI.

**Comment by CausticLasagne** [comment]
Could you just move the sort buttons to the left instead of the right? The JEI and NEI main windows are on the right.
