### ISSUE TITLE
crash during mod construction

### ISSUE THREAD

**Issue by LordVladneutral** [Inventory-Tweaks/inventory-tweaks#388]
**Minecraft Version:** 1.8.9
**Inventory Tweaks Version:** 1.60 - 40
OS : Arch Linux

whatever I try, minecraft will always be stuck with the same error and I can't launch the game at all, even if the mod is alone with forge.

http://pastebin.com/D6zvxFr9

or this sometimes http://pastebin.com/8wgYX2de

I'm not asking for a fix, or a release to change that, just maybe a way to work around the problem.

PS : just realised I hadn't tried with a clean minecraft folder... and same thing

**Comment by Kobata** [comment]
>  Java Version: 1.7.0_111, Oracle Corporation

Inventory Tweaks requires Java 8
