### ISSUE TITLE
ghost-items on spigot servers

### ISSUE THREAD

**Issue by Platinteufel** [Inventory-Tweaks/inventory-tweaks#390]
**Minecraft Version:** 1.10.2
**Inventory Tweaks Version:** 1.61

If I try to sort chests on my server (latest PaperSpigot 1.10.2) I'll get ghost items into my inventory/hand. Here's a short video that describes my issue: https://www.youtube.com/watch?v=WWses_dgJiA

I've also talked about the issue with the PaperSpigot dev, but he says it needs to be fixed on client side.
There are some threads from other users where you can read that this problem occurs since Minecraft 1.7.10, but unfortunately I can't confirm that.
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1288184-inventory-tweaks-1-61-jul-11?page=70#c1431

**Comment by Kobata** [comment]
On vanilla servers (or any server without the mod installed on the server) Inventory Tweaks does nothing other than sending standard item movement packets. 'Ghost' items and partial sorting followed by reverting are caused by the server either forcing a revert or not correctly updating the client.

Bukkit and Spigot have been known to react badly due to their massive messing with the item movement handling to support plugin control.

**Comment by Kobata** [comment]
A bit more clarity: [Here](https://github.com/Inventory-Tweaks/inventory-tweaks/blob/develop/src/main/java/invtweaks/forge/ClientProxy.java#L100) is the main item movement code, specifically the version used without the specialized server support. This is almost as close as possible to _actually_ moving the mouse and sending simulated clicks possible.

My testing of similar issues with modded items a long time ago confirmed that **anything you can cause to happen with inventory Tweaks, you can cause to happen by actually clicking.**

It's sometimes impractical to trigger issues, frequently you have to be very fast, but it's _always_ possible to get to happen either through actual clicks or with automation help (e.g., autohotkey)

There might be an exception in rare cases for behavior with the server-assist module, but that won't be active in a normal bukkit-type server, and even that acts very closely to normal clicks.
