### ISSUE TITLE
Comparison method Bug

### ISSUE THREAD

**Issue by SashaGelert** [Inventory-Tweaks/inventory-tweaks#397]
**Minecraft Version:** -- MC 1.7.10 Forge 10.13.4.1614
**Inventory Tweaks Version:** -- 159-dev-152

Reported this to AE2 github, and Yueh pointed out it would be better filed over here :) 
CopyPasta:

Not sure who to blame for this crash, but it's under very specific circumstances.
Forewarning: MC 1.7.10 Forge 10.13.4.1614. Bit dated, but i like having lots of nicely working mods.

Single Player Worlds: no issues, everything works fine as expected.

Multiplayer Worlds: When in an ME terminal GUI, whether basic or crafting, if the first letter entered in the search box is 'm' or 'u' then the client crashes, in all four search modes (Auto, Standard, NEI Sync Auto, NEI Sync Standard).

I can't seem to find out what is causing this, especially as 'm' isn't bound as a hotkey to anything. 'u' is bound to swapping Tinkers Construct Travelers belt, which i've never had issues with before.

Full crash log, if anyone can help pin down the cause of this bug it would be appreciated:
http://pastebin.com/s6ncyQH9

**Comment by Kobata** [comment]
I can't see anything specifically in the log that points to inventory tweaks, although I do believe AE has a sorting mode based on inventory tweaks order?

It's probably possible there's some subtle issue in the item comparison (that would also explain some of the weirdness of normal sorting too), but I'm not seeing anything 100% obvious.

**Comment by SashaGelert** [comment]
Did some quick testing among the other AE Sort modes.  This is quite irritating, but you are correct, the issue only occurs in InvTweaks sort mode within the terminal, Thankyou.
