### ISSUE TITLE
Dupe bug that works on any SMP server

### ISSUE THREAD

**Issue by vanZeben** [Inventory-Tweaks/inventory-tweaks#40]
This is something I dont quite understand. Im not quite sure how, when this is done, that the items are valid items and not client side "ghosts". Here is the process for it.

You first grab an item that you want to dupe and hover over a slot that would be "processed for sorting" and not be filled up after sorting. Then click on the slot and immediately hit your sorting hot-key. This will sort your inventory, moving the item you clicked into the sorting position as well as the slot that you clicked, resulting in 2 of the item. 

This issue is extremely bad, and although it can be prevented by disabling InvTweaks for users totally, it's a bad way to correct it

**Comment by Kobata** [comment]
If this is creative mode and your 'sort hotkey' is the mouse middle-click/pick block key, it's processing the creative duplicate action and sorting at the same time...

If it isn't, well, the mod does nothing that cannot be simulated entirely with mouse clicks so it should be reproducible in some way without the mod...

**Comment by Kobata** [comment]
Still can't get this to happen, and it really isn't something the mod should be technically capable of doing because of how it works.
