### ISSUE TITLE
[1.10.2] Odd Sort Crash

### ISSUE THREAD

**Issue by Shadows-of-Fire** [Inventory-Tweaks/inventory-tweaks#401]
https://paste.ee/p/PQMnr
This happens in both 1.61 and 1.62-dev but I have no idea what's causing it.  It seems to be a mod interaction since it wasn't present in my last instance.

**Comment by Kobata** [comment]
You've got a mod with an old version of the API files in it, go find & delete those from their jar.

Probably AE2, since that's the only mod I know of that uses it for anything.
