### ISSUE TITLE
[Bug - Minor] Config Loaded Msg Bug

### ISSUE THREAD

**Issue by ElvenChaos** [Inventory-Tweaks/inventory-tweaks#407]
**Minecraft Version:1.10.2**
**Inventory Tweaks Version:1.61-58**

When I have my config set to this:
`enableConfigLoadedMesssage=false`
...I still get the line _"InvTweaks: Configuration Loaded"_ when a world is loaded into.

**Comment by xSparky911x** [comment]
I didn't notice your bug report here but the solution is located in the one I just posted...
https://github.com/Inventory-Tweaks/inventory-tweaks/issues/423
