### ISSUE TITLE
ME Terminal Crashes when the ME Network has a Storage Bus Attached to a Storage Drawer Network

### ISSUE THREAD

**Issue by Whimsyturtle** [Inventory-Tweaks/inventory-tweaks#409]
**Minecraft Version:**
1.7.10

**Inventory Tweaks Version:**
1.59-dev-152

https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/2601
https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/2452

According to the Guys Over at AE2, this is a Inventory Tweaks Issue?

**Comment by Kobata** [comment]
#397

**Comment by Kobata** [comment]
#397
