### ISSUE TITLE
[1.7.10] Sorting with number id not working

### ISSUE THREAD

**Issue by Spook2U** [Inventory-Tweaks/inventory-tweaks#410]
**Minecraft Version:** 1.7.10
**Inventory Tweaks Version:** 1.59-dev-152

I want to sort Custrom mods and added as example salt from PamsHarvestCraft:
<salt id="4588"/>
I got the ID from NotEnoughItems, and no it dont have damage value

I tried also to replace the
<coal id="coal" damage="0"/>
with
<coal id="263" damage="0"/> (263 is correct id for coal)

As soon as I do, coal gets Sorten last as if ist a not knows Item
I did save the file, I dont get any error and the sorting work normal besides that.

**Comment by Kobata** [comment]
Find the item's internal name (use F3+H with inventory tweaks installed in 1.7, it's vanilla in 1.8+)
