### ISSUE TITLE
Mod incompatibility with Multi Page Chest

### ISSUE THREAD

**Issue by DatrixTHLK** [Inventory-Tweaks/inventory-tweaks#411]
**Minecraft Version:** 1.10.2
**Inventory Tweaks Version:** 1.62-dev-66

Hello,

I'm unable to sort the inventory in a Multi Page Chest. This works in a regular minecraft chest and in the inventory screen.
Could this be made compatible with [Multi Page Chest](https://minecraft.curseforge.com/projects/multi-page-chest). If that mod should be made compatible with inventory tweaks let me know and I will send this issue towards CubeX2.

**Comment by Kobata** [comment]
#406

**Comment by DatrixTHLK** [comment]
How did I miss that issue...Thanks Kobata. I'm closing this one then.

**Comment by DatrixTHLK** [comment]
I'll let CubeX2 know then to add compatibility to this mod, if possible.
