### ISSUE TITLE
Crash on loading world.

### ISSUE THREAD

**Issue by MaciejJaromin** [Inventory-Tweaks/inventory-tweaks#412]
**Minecraft Version: 1.10.2**
**Inventory Tweaks Version: 1.61-58**
[crash-2016-11-21_18.40.27-client.txt](https://github.com/Inventory-Tweaks/inventory-tweaks/files/604351/crash-2016-11-21_18.40.27-client.txt)

Doesn't happen the first few times upon loading a fresh world, but once it starts happening, it doesn't go away.

**Comment by Kobata** [comment]
This looks maybe related to #394 ?

**Comment by MaciejJaromin** [comment]
I think I found the culprit in Crafting Harmonics - it's a MineTweaker style mod whose main feature is allowing recipe changes during gameplay. I was using it pretty heavily and I suspect it was causing a lot of lag when loading a world.
