### ISSUE TITLE
multipage sorting

### ISSUE THREAD

**Issue by darkshadow543** [Inventory-Tweaks/inventory-tweaks#413]
**Minecraft Version:** 1.10
**Inventory Tweaks Version:**1.62-dev-66

When sorting in multipage inventory,  A bug occurs where it does not look into the entire inventory, but just the current page.  It also can make it so that you cannot access the other pages.  Its a bit of an issue when working with Actually Additions Crates

**Comment by Kobata** [comment]
The mod can only interact with things currently visible on the screen, as a fundamental design due to working with completely vanilla servers.
