### ISSUE TITLE
Requires Forge I already have...

### ISSUE THREAD

**Issue by Jakathera** [Inventory-Tweaks/inventory-tweaks#416]
**Minecraft Version:** 1.11
**Inventory Tweaks Version:** 1.61-58
**Forge  Version:**  release 1.11-forge1.11-13.19.0.2176
--This is "above" the required version for inventory tweaks

When I load minecraft, everything loads great until I get this message with the above combination:

INVENTORY TWEAKS is missing mods it depends on.  Include the following mods or remove Inventory Tweaks.
FORGE 12.17.0 or above, see 'fml-client-latest.log' for technical information.

EDIT:
I tried pasting the log, but i'll just leave it as an attachment because it takes up so much space...

**Comment by Kobata** [comment]
There is no 1.11 release version of inventory tweaks yet.
