### ISSUE TITLE
Sending too many packages

### ISSUE THREAD

**Issue by azatoth** [Inventory-Tweaks/inventory-tweaks#417]
**Minecraft Version:** 1.11
**Inventory Tweaks Version:** 1.62-dev-74

Issuing a middle-click sorting in a chest with multiple different items on an external server (spigot based) results for me getting disconnected for "Sending too many packages".
There's no debug information available in the logs nor any apparent crashes.

**Comment by Kobata** [comment]
Spigot, bukkit, sponge, and other major modified servers other than forge + standard mods can and will do things that can break the mod, there's not much I can do about that.

(It is a tad excessive on the packet front to do major sorting, but the way it has to work on non-forge servers doesn't give me much room to do anything about that.)

**Comment by azatoth** [comment]
I just felt this was strange as it didn't happen before in 1.10

**Comment by azatoth** [comment]
@Kobata it seems to only happen when using the "Z" sorting; it doesn't happen when using column or rows sorting...
