### ISSUE TITLE
automatic next stack

### ISSUE THREAD

**Issue by animalnl078** [Inventory-Tweaks/inventory-tweaks#418]
**Minecraft Version:1.11
**Inventory Tweaks Version: latest for 1.11

question try to get the next stack of blocks when building but need to use de middle mouseB to get the next stack in the inventory

Same thing when using tools, next tool will not get in the hotbar, when the old tool is olmost depleted

sorry for any typo\s or any grammor error\s but i'm Dutch.

Maybe i\m doing it wrong and some of the settings are wrong!!!!

So can you help.

**Comment by Cuteminded** [comment]
Nederlands lekker makkelijk  
je moet in de IT menu middle click off zetten
dan krijg je meteen een nieuwe stack
