### ISSUE TITLE
Glitchy quick move shortcuts

### ISSUE THREAD

**Issue by Lunatrius** [Inventory-Tweaks/inventory-tweaks#42]
I tried it with W/S, it's most likely the same with other keys.

http://i.imgur.com/wpAeCLp.jpg (with buffs/debuffs)
http://i.imgur.com/PF54WsT.jpg (without buffs/debuffs)

If I hold down W and click on the golden helmet while I have a buff/debuff active it won't move the helmet but the carrots instead.

**Comment by Kobata** [comment]
There's been talk of something similar with dropping items, which is really weird because the click injector never uses the screen coordinates of anything, it just works on the slot numbers directly...
