### ISSUE TITLE
Does not detect Forge.

### ISSUE THREAD

**Issue by ghost** [Inventory-Tweaks/inventory-tweaks#422]
**Minecraft Version:1.11.2**
**Inventory Tweaks Version:1.61-58**
Whenever I try to run the game, the client says that the mod needs forge to run. I know I've installed it correctly because forge runs fine with other mods, it's just this one. You can even see in the log that forge is looking for mods to run, I don't know what to do, please help.

http://pastebin.com/1z5iZ2tx

**Comment by Reftinmac** [comment]
Ok I'm fucking stupid, I thought 1.10.2 was the latest release, when its actually 1.11.2...I'm sorry. I'll wait for the new release of this mod. My bad.

**Comment by Kobata** [comment]
The dev versions for 1.11 should most likely work for 1.11.2 as well. (although there will shortly be a dev version compiled on 1.11.2 anyway)
