### ISSUE TITLE
enableConfigLoadedMessage boolean backwards

### ISSUE THREAD

**Issue by xSparky911x** [Inventory-Tweaks/inventory-tweaks#423]
**Minecraft Version:**
1.10.2
Forge 2185
**Inventory Tweaks Version:**
1.6.2-dev-66

As the title implies - enableConfigLoadedMessage=false shows the mod loaded when joining a world
enableConfigLoadedMessage= true does not show the loaded message. Minor issue but still...

**Comment by Kobata** [comment]
You know, I did kinda wonder why people occasionally complained because I was fairly certain that worked.

**Comment by fcpwiz** [comment]
@Kobata This issue is still in the 1.10.2 version. Do you plan to push another 1.10.2 update that contains this fix?
