### ISSUE TITLE
Distribute items in backpack to appropriate chests on command 

### ISSUE THREAD

**Issue by ghost** [Inventory-Tweaks/inventory-tweaks#428]
It'd be really nice if I could with a click of a button or a single command have everything in my backpack deposited into nearby chests that have same items in them. So when I come back from a mining expedition  and my backpack is full of a variety of blocks, I can avoid the "chest dance" where I open all the chests depositing blocks into those chests.

There a couple of Bukkit plugins that do something similar to this (AutomaticInventory and MondoChest) but they're both currently not maintained -- and not Forge mods. Seemed like this feature might be logical addition to InventoryTweaks.

**Comment by Kobata** [comment]
This cannot be done with the client-side only mode, so it's not an appropriate addition to this mod.
