### ISSUE TITLE
Mekanism Auto Refill

### ISSUE THREAD

**Issue by duncanwebb** [Inventory-Tweaks/inventory-tweaks#429]
**Minecraft Version: 1.10.2**
**Inventory Tweaks Version: 1.61-58**

Mekanism uses the damage value to distinguish between different item. like this:
```
<ElectricPump id="mekanism:MachineBlock" damage="12"/>
<personalChest id="mekanism:MachineBlock" damage="13"/>
```
The auto-fill seems to replace the used item with the highest damage value item, so when there are a number of pumps in my inventory it replaced the used pump with the personal chest.

Is it possible to configure Inventory Tweaks so that is uses the same damage value first?

Thanks

**Comment by Kobata** [comment]
It *should* but auto-refill is a bit of a mess currently and I haven't been able to get it to work correctly for a bit.
