### ISSUE TITLE
Option to 'ignore' certain drops

### ISSUE THREAD

**Issue by ZephireNZ** [Inventory-Tweaks/inventory-tweaks#43]
For example, you could tell inventory tweaks to not pick up cobblestone, either temporarily, for a specific configuration, or globally.

This would help a tonne when you're mining for a while. Your inventory fills up with cobble stone, meaning you might accidentally leave behind some ores - there's no space with all the cobblestone.

**Comment by Kobata** [comment]
Inventory Tweaks is primarily a client-side mod, so it cannot prevent you from picking up items, as that is a server-side function (Even in 'single-player' mode there is a separation between the two sides since MC1.3).
