### ISSUE TITLE
[1.10.2] [Bug] Crash on respawn

### ISSUE THREAD

**Issue by Dijkstra1-zz** [Inventory-Tweaks/inventory-tweaks#430]
My client crash every time I respawn [Crash Report](https://gist.github.com/Dijkstra1/83c07870f87fcca2dc5a74cf3a461cf0)

**Minecraft Version:** Look Uo ^^^
**Inventory Tweaks Version:** IDK Lastest on curse as of 25/01/17

**Comment by Kobata** [comment]
Probably related to #394 -- various things that go wrong when the player doesn't really 'exist' for some reason or another.
