### ISSUE TITLE
Null Pointer Exception when sorting Actually Additions Storage Crate inventory.

### ISSUE THREAD

**Issue by Zarepheth** [Inventory-Tweaks/inventory-tweaks#431]
```
Minecraft Version:               1.11.2
Inventory Tweaks Version:   1.62-dev-75
Forge Version:                     2220
```
When attempting to use the Inventory Tweaks buttons to sort/organize the inventory within an Actually Additions storage crate, a Null Pointer Exception occurs, leaving the inventory unsorted.

[latest.log.txt](https://github.com/Inventory-Tweaks/inventory-tweaks/files/737353/latest.log.txt)

**Comment by Kobata** [comment]
I *think* you have a messed up sorting rule somewhere, since that's the most related thing I can find.

It probably shouldn't crash, but it looks more like a config-related issue than something major going wrong.

**Comment by Zarepheth** [comment]
@Kobata 
Thanks you. Your changes fixed the sorting, though it also spawns error messages. From reviewing the code, the error messages are intentional. So... I figure you want to see what they are.

I've attached the "_latest.log_" and "_fml-client-latest.log_" files along with my Inventory Tweaks config files in the attached *.zip files. In the log files, review time-stamp 23:14:37 it will show the errors I now see in the chat window as well as the exception's stack trace. I have no idea how to relate the log "rule" with what I see in the config files. As far as I can tell, the config files are just the default from installing Inventory Tweaks.

[logs.zip](https://github.com/Inventory-Tweaks/inventory-tweaks/files/752779/logs.zip)
[config.zip](https://github.com/Inventory-Tweaks/inventory-tweaks/files/752780/config.zip)

**Comment by Kobata** [comment]
Hmm, yeah, those are weird -- but given the timing of them I'm betting they're related to horizontal/vertical sort -- which is fairly broken with differently-sized containers but I thought it was also set to not happen on those.

**Comment by Zarepheth** [comment]
Yeah, the errors occurred when I click the Horizontal or Vertical sorting buttons for Actually Additions' storage chests. And they are of non-standard height and width. After reporting this error, I discovered I could click on the plain sort button and it worked without error.

After your previous change to display and log the errors, the horizontal and vertical sorting actually worked (mostly), despite the error messages. Before that, I'd get a message but no sorting.
