### ISSUE TITLE
Autofill Not Working

### ISSUE THREAD

**Issue by KingJul** [Inventory-Tweaks/inventory-tweaks#432]
**Minecraft Version:1.11.2**
**Inventory Tweaks Version:1.62-dev-77**

When I run out of seeds or a block, it seems that my stack does not automatic refill. I have tried switching the option on and off; did not fix the problem. This problem also includes refilling tools.

**Comment by thenelgonz** [comment]
I figured out it only happens when you switch to that item by middle click

**Comment by canichols2** [comment]
I am having the same issue. Even removed all mods except Inventory-Tweaks. But still broken. Sorting is working and I can edit mod options in game so it is loading the mod and it's working, except this feature.

**Comment by Elainasaurus** [comment]
I'm also having this issue.  It's a dealbreaker, honestly
