### ISSUE TITLE
Sort By Item Name

### ISSUE THREAD

**Issue by Fortist** [Inventory-Tweaks/inventory-tweaks#435]
**Minecraft Version:*Doesnt Matter*
**Inventory Tweaks Version:*Whatever is latest*

How exactly do you set it up to sort by Item name/Alphabetically?
I figured out how to sort it by Alphabetically by MOD ID, by deleting the "stuff" section, but even this is not Ideal.

Another thing I'd like to know is how to separate Blocks and Items to sort one after the other.
Ergo, Blocks first then Items sorted in that order.

**Comment by Kobata** [comment]
Sorting will mostly follow the order in the item tree file.

Obviously, for very specific modes, this is a good bit of work to set up, but it's the easiest form of flexibility possible, and even if there were special options for things, they may not always match what a person is trying to do.

**Comment by Fortist** [comment]
So is that a "Yes, it's possible"? For the first part at least. Alphabetical is the priority.
Documentation for something like this doesnt seem to exist.

**Comment by Kobata** [comment]
As long as you're willing to explicitly list *every item* in the order you want you can make it do whatever you want just by reordering where they are in the tree file.

You can also list the same one multiple times, it should sort as it's first appearance, allowing groupings for rules to be added after the exhaustive list.

**Comment by Fortist** [comment]
Ah. Gross. Well thats worthless and extremely inefficient. Worth a try at least. Thanks for the answer. 
Good sorting mods fuckin' WHEN. 
But then again I am using logistics pipes.
