### ISSUE TITLE
[1.7.10] Repair-Friendly Mode Crash

### ISSUE THREAD

**Issue by DarianLStephens** [Inventory-Tweaks/inventory-tweaks#436]
**Minecraft Version: 1.7.10**
**Inventory Tweaks Version: 1.59-dev-152**

I know 1.7.10 is REALLY outdated in terms of this mod's development, but there's a crash occurring with Repair-Friendly mode.
If your inventory is full and you wear out a tool to the level the mod would try to protect it by moving it out of your hotbar, the game will crash. It sounds like a relatively simple fix, but it could hamper the Repair-Friendly-ness since players could fill up their inventory while mining, and their enchanted pick could suddenly break because there's no room to protect it.
Perhaps that could be fixed by, if there's no space to move it and no other tool to replace it, it would just swap the in-peril tool for a non-tool, alerting the player of their tool's condition while their inventory's full.

**Comment by Kobata** [comment]
1.7.10 isn't getting any fixes.

**Comment by DarianLStephens** [comment]
Not even something like 'If inventory full, swap current slot and first slot without tool' to prevent a crash?
If you're not willing to do it, but you can provide the 1.7.10 source, I'll make the change myself for personal use.
