### ISSUE TITLE
Can't Run Minecraft With Mod? Wrong Forge? 

### ISSUE THREAD

**Issue by EDAboii** [Inventory-Tweaks/inventory-tweaks#437]
**Minecraft Version: 1.11.2**
**Inventory Tweaks Version: 1.61-58**
**Forge Version: 1.11.2-13.20.0.2201**

Okay, so when I start up the game it stops on a screen. This screen:
![image](https://cloud.githubusercontent.com/assets/25863553/23093060/daf943ca-f5d0-11e6-8cb7-0248664de30c.png)

Meanwhile, I have the latest version of Minecraft, the latest version of Inventory Tweaks, and the latest version of Forge... 

I have no idea what's wrong... Please help?

**Comment by Kobata** [comment]
Please pay attention to what the Curse download page says the compatible versions are.

**Comment by EDAboii** [comment]
@Kobata I have. I have none of the mods Inventory Tweaks isn't compatible with, infact except for Forge I have no other mods. Meanwhile, I have the most recent version of forge, installed with the forge installer. Plus, I have the vanilla minecraft launcher. I have payed attention, and I have everything necessary, yet am still met with this issue...

So, PLEASE, can you offer me something that actually helps, instead of closing the thread and offering extremely vague advice!

**Comment by Kobata** [comment]
![versions](https://cloud.githubusercontent.com/assets/2323933/23096907/eef32ea8-f5f4-11e6-99ca-43c228963a84.png)
