### ISSUE TITLE
CompactStorage support?

### ISSUE THREAD

**Issue by DeadSix27** [Inventory-Tweaks/inventory-tweaks#439]
Any chance you'll add CompactStorage support in 1.10.2? 

https://github.com/tobystrong/CompactStorage
https://minecraft.curseforge.com/projects/compactstorage

**Comment by Kobata** [comment]
Support requires mods to use the API to specify the correct things, there is nothing I can do.

**Comment by DeadSix27** [comment]
@Kobata Ah, ye I was gonna add "or do the mod authors need to access your API?" which i guess they do, lemme ask on their issue tracker.
