### ISSUE TITLE
5000 entry limit in tree file

### ISSUE THREAD

**Issue by drakray** [Inventory-Tweaks/inventory-tweaks#442]
**Minecraft Version:**
1.11.2
**Forge Version:**
2260
**Inventory Tweaks Version:**
1.62 dev-78

Is there a way/plan to support more than 5000 entry in the InvTweaksTree file?
I made myself a fairly large file to sort Metallic/Gems stuff, and Harvestcraft stuff too, and I tested to see why stuff past a certain point stopped being sorted as I want, and 5000 is the last one to be.

**Comment by Kobata** [comment]
I wasn't aware of any such limit, and I can't find anything obvious that might be imposing it.

A quick look *does* show the parsing is probably slower than it could be because it goes through the whole file twice, though.

**Comment by drakray** [comment]
The only place with 5000 in the code is in [InvTweaksItemTree.java](https://github.com/Inventory-Tweaks/inventory-tweaks/blob/f3105ea341812860566ee2d1057cab8c47f4f5ba/src/main/java/invtweaks/InvTweaksItemTree.java) , if that could be relevant

**Comment by Kobata** [comment]
Hmm.. that is where it sticks all the default entries, so it might be that the ones past 5000 are *loaded*, but just end up effectively *ignored*

That whole thing is a bit awkward though, and it really should be made to just place them more consistently.

**Comment by drakray** [comment]
[InvTweaksTree.txt](https://github.com/Inventory-Tweaks/inventory-tweaks/files/868918/InvTweaksTree.txt)
Here is my file if you want to test

**Comment by drakray** [comment]
something weird:
my 5000 mark is at line 5485, harvestcraft:firmtofuitem
if I change order for thing in `<harvestcraftRawProteins>,` they don't change order in inventory
but if I change bucket order in `<item>,` they change order in inventory

**Comment by drakray** [comment]
ok, new infos:
it seems that thing ARE ordered by the file, for everything listed.
Problem seems to come from thing WITHOUT sorted entry, like HC meal in my file, which are not listed.
They seems to insert themself ~~randomly~~ after 5000, sorted alphabetically by mod, then code name, unless specified in file

**Comment by Kobata** [comment]
> that is where it sticks all the default entries

Anything not there gets set to a priority of 5000, which is equivalent to the 5000th entry.

This has mostly been around forever, in older versions it did a bit more spacing based on numerical IDs of things but in practice it still *started* at 5000 for the first items.

This number is possibly a bit low with current mods, but just randomly raising it a bit won't really solve the issue (or some of the other things related to that default not always being the best thing)
