### ISSUE TITLE
Auto-Refill

### ISSUE THREAD

**Issue by IronBoar** [Inventory-Tweaks/inventory-tweaks#445]
Minecraft Version: 1.11.2
Inventory Tweaks Version: 1.62-dev-80

When I throw a block (dirt in my tests) from my main hand, auto-refill works like a charm.
When I place a block with by main hand...bupkis.

**Comment by Kobata** [comment]
Well, I think I found the actual issue this time, since it kept thinking you always had air due to not properly copying the item stack.
