### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by McModknower** [Inventory-Tweaks/inventory-tweaks#450]
Minecraft Version: 1.7.10
Inventory Tweaks Version: InventoryTweaks-1.59-dev-152
crash report:
[crash-2017-04-16_17.52.31-client.txt](https://github.com/Inventory-Tweaks/inventory-tweaks/files/924403/crash-2017-04-16_17.52.31-client.txt)

BTW: I am playing a public modpack.

**Comment by Kobata** [comment]
No support is provided for 1.7.10 at this point
