### ISSUE TITLE
Space+click to move all items not working with Ender storage

### ISSUE THREAD

**Issue by steinjorn** [Inventory-Tweaks/inventory-tweaks#453]
Minecraft Version: 1.10.2
Inventory Tweaks Version: 1.61-58

When I use shortcut: space+click, it will not work with the ender chest or the ender pouch from the mod 
ender storage 1.8+ version 1.10.2-2.2.1.106-universal

**Comment by Kobata** [comment]
Does *anything* work with those, such as the sorting? Everything's tied together so if they aren't using the API to mark them up correctly none of the additions will work.

**Comment by steinjorn** [comment]
Ya, none if it works with them as far as I can see.

**Comment by magneticflux-** [comment]
This needs to be fixed by Ender Storage in issue TheCBProject/EnderStorage/issues/54.
