### ISSUE TITLE
[Modpack] Can't sort in Diamond Chest

### ISSUE THREAD

**Issue by Mindstorm95** [Inventory-Tweaks/inventory-tweaks#455]
**Minecraft Version:** 1.10.2
**Inventory Tweaks Version:** 1.61-58
**Iron Chest Mod version:** 1.10.2-7.0.11.797

When pressing both line sort in the diamond chest it wont work and an error message comes up in the chat log. 

The 2 buttons that has the error message pop up
![Buttons](https://cloud.githubusercontent.com/assets/2625527/25478675/679a131c-2b42-11e7-9f95-46dd4d590577.png)

This is error message
![2017-04-27_12 02 38](https://cloud.githubusercontent.com/assets/2625527/25478706/7f8feef6-2b42-11e7-8220-7d6be201c2aa.png)

**Comment by Kobata** [comment]
This has been since fixed, and isn't present in current versions. see 4165ce4

There are no plans to backport any fixes to older versions.
