### ISSUE TITLE
[1.10][Bug][Modpack][Crossmod] AA Medium storage crate sorting

### ISSUE THREAD

**Issue by ibedek** [Inventory-Tweaks/inventory-tweaks#458]
I'm playing FTB Beyond 1.5.3 on server (default config), MC 1.10.2.

Steps to reproduce:
- Create AA small storage crate, fill it up
- Apply small to medium crate upgrade, fill up first "page"
- Start filling second page
- take some items (stacks) from first page
- try to sort it with middle mouse button
    -> error in chat, and sorting doesn't work (will upload screenshot of error if needed)

Expected behavior: to pull items from second page into free slots on first one and sort items

Could be related to #455

**Comment by Kobata** [comment]
Well, without the error I can't say much, and it also helps to have the full error from the log files.

After the last few reports people have had with mods though, I'm going to lean towards "it's **probably** their fault" without any extra information though.

**Comment by ibedek** [comment]
Here's everything from log:
https://pastebin.com/jAUAxWs6

**Comment by Kobata** [comment]
This has been since fixed, and isn't present in current versions. see 4165ce4014e113468754b771ceede3f6d360ac11

There are no plans to backport any fixes to older versions.
