### ISSUE TITLE
Vertical sorting crash

### ISSUE THREAD

**Issue by JelmarG** [Inventory-Tweaks/inventory-tweaks#46]
Clicking the vertical alignment button (or middle mouse clicking until the vertical alignment comes up) in chests seems to crash the client. Reproduced by two other people. Other mods installed are Rei Minimap, Liteloader, Forge, Macromod, WorldEdit CUI and OptiFine. 

Possibly a conflict with another mod, but the bug is new in 1.5.2.

**Comment by Kobata** [comment]
You should include a link to ForgeModLoader-Client-0.log with all crash reports.

**Comment by JelmarG** [comment]
Did see some errors in the log, but my knowledge is lacking. Here it is, hope it helps: http://pastebin.com/mhepqTYJ

**Comment by Kobata** [comment]
Unfortunately that doesn't say anything, so I'll have to see if I can get anything to happen here.

**Comment by Kobata** [comment]
Cannot get any crashes to happen with 1.5.2 and any sorting mode, even with a double chest full of random items.
