### ISSUE TITLE
Crash report (info below)

### ISSUE THREAD

**Issue by Kylebartaous** [Inventory-Tweaks/inventory-tweaks#460]
Mine craft Version: 1.11.2
Inventory Tweaks Version: InventoryTweaks-1.62+beta.87
Forge Build: ( with lite loader install mix in) 1.11.2-LiteLoader1.11.2-forge-13.20.0.2296
Using the curse / twitch app launcher
It seems to be a problem with Inventory tweaks and opt define mods. Then i don't have opt define ticked on as a running mod it seems to work fine but then i tick it on and select the right forge version it seems to load and then closes and goes the vanilla launcher crash screen, The crash log is attracted below.

[crash-2017-05-11_19.07.08-client.txt](https://github.com/Inventory-Tweaks/inventory-tweaks/files/994729/crash-2017-05-11_19.07.08-client.txt)

[logs.zip](https://github.com/Inventory-Tweaks/inventory-tweaks/files/994731/logs.zip)

**Comment by Kylebartaous** [comment]
#update seems inventory tweaks ( InventoryTweaks-1.62+beta.87 ) had a update a hour ago as i was posting this.

**Comment by Kobata** [comment]
It *looks* like you have some x-ray mod that's not compatible with optifine.

In general though, optifine is known to occasionally break things so if you have an issue with it, the only solution is to uninstall it.
