### ISSUE TITLE
Inventory Tweaks and Forge

### ISSUE THREAD

**Issue by ghost** [Inventory-Tweaks/inventory-tweaks#464]
Minecraft Version 1.11.2
InventoryTweaks Version 1.61
Minecraft Forge Version 13.20.0.2228

So this happens every time I try to launch it.

![image](https://cloud.githubusercontent.com/assets/29054274/26567480/ad50835a-44c9-11e7-9f1a-106ef4fbb088.png)

The view log file button also doesn't do anything.

**Comment by Kobata** [comment]
Check the MC version listed on curseforge for the file you downloaded.

**Comment by ghost** [comment]
Sorry, i dont see the mc version list on curseforge.

**Comment by ghost** [comment]
oh nvm
