### ISSUE TITLE
Client crash on mod loading

### ISSUE THREAD

**Issue by Maximeus** [Inventory-Tweaks/inventory-tweaks#466]
Minecraft Version:1.11.2
Inventory Tweaks Version:1.62+beta.89
Crash when loading mod
[crash log.txt](https://github.com/Inventory-Tweaks/inventory-tweaks/files/1046252/crash.log.txt)

**Comment by Kobata** [comment]
`Caused by: java.io.FileNotFoundException: C:\Users\Play\Documents\Curse\Minecraft\Instances\Guns ! (Le fichier spécifié est introuvable)`

I think Java doesn't really like characters like `!` in folder names.

**Comment by Maximeus** [comment]
Thanks ! Deleting the ! resolved the issue
