### ISSUE TITLE
Cannot disable R key for sorting

### ISSUE THREAD

**Issue by Warhand** [Inventory-Tweaks/inventory-tweaks#467]
**Minecraft Version:1.7.10**
**Inventory Tweaks Version:1.59-dev-152**
No matter what i have done, i cannot disable the R key for sorting, which is infuriating since its the same key i use to look up recipes with NEI, i have edited the configs, changed the keybinds, went back to previous versions, tried a few mods to replace Inventory tweaks and no other solutions work, if you dont have time to release a new 1.7.10 version can you at least tell me where i can find and edit the code that binds the sorting to that key?

or if there is another solution i missed i would be happy if someone directed me towards that.

**Comment by Kobata** [comment]
The keybind screen *should* change it, but you probably need to specifically set it to another key. I don't think it will work correctly set to nothing.

**Comment by Warhand** [comment]
That doesnt work either.
