### ISSUE TITLE
Cannot disable R key for sorting (second time ive posted this, see description)

### ISSUE THREAD

**Issue by Warhand** [Inventory-Tweaks/inventory-tweaks#470]
Minecraft Version:1.7.10
Inventory Tweaks Version:1.59-dev-152
No matter what i have done, i cannot disable the R key for sorting, which is infuriating since its the same key i use to look up recipes with NEI, i have edited the configs, changed the keybinds, went back to previous versions, tried a few mods to replace Inventory tweaks and no other solutions work, if you dont have time to release a new 1.7.10 version can you at least tell me where i can find and edit the code that binds the sorting to that key?

or if there is another solution i missed i would be happy if someone directed me towards that.

(Kobata suggested binding it to a key instead of binding it to nothing, and then closed the issue immediately, while i get he figured that would fix the issue i would have really prefered if he had waited to see if it did fix the issue instead of assuming.   needless to say that fix didnt work, the R key still sorts the inventory)

**Comment by Kobata** [comment]
I closed it because you're still on 1.7.10, so nothing's getting fixed.

Remapping *should* work, but if you can't make it work, this isn't an appropriate place for issues exclusively with old versions.

**Comment by Warhand** [comment]
then where am i supposed to go for help on this issue? i cant find help anywhere else and i cant find any versions that fix the issue, can you at least point me to where i can find the code to try and fix the issue myself?
