### ISSUE TITLE
Actually Additions compatibilty

### ISSUE THREAD

**Issue by tahg** [Inventory-Tweaks/inventory-tweaks#471]
**Minecraft Version:**
1.11.2
**Inventory Tweaks Version:**
1.62+beta.88
**AA Version:**
r109

Actually Additions adds a virtual crafting table (Crafting Table on a Stick).  Is there any way to add compatibility so shift-clicking (and with w,s, etc) work in that GUI?

**Comment by Kobata** [comment]
https://github.com/Inventory-Tweaks/inventory-tweaks/tree/develop/src/main/java/invtweaks/api/container
