### ISSUE TITLE
Port to 1.12

### ISSUE THREAD

**Issue by chfzdn** [Inventory-Tweaks/inventory-tweaks#472]
**Minecraft Version: 1.12**
**Inventory Tweaks Version: Future**

Sorry if I wrong. Can you port this mod to 1.12? Along with the new blocks compatibility. Also, for lightweightness and your mod isn't affect gameplay (your mod just simulate clicks), can you port to Liteloader?

Thank you.

**Comment by Kobata** [comment]
I'll deal with 1.12 sometime (probably mostly after Forge has had some time to make sure all their stuff works right)

There is no plan to add versions for other mod loaders.
