### ISSUE TITLE
enableConfigLoadedMessage issue on 1.10.2

### ISSUE THREAD

**Issue by fcpwiz** [Inventory-Tweaks/inventory-tweaks#479]
**Minecraft Version:** 1.10.2
**Inventory Tweaks Version:** InventoryTweaks-1.62-dev-66.jar

Hi,

I noticed that https://github.com/Inventory-Tweaks/inventory-tweaks/issues/423 & https://github.com/Inventory-Tweaks/inventory-tweaks/issues/407 was fixed for the 1.11.2+ MC versions, though it didn't get fixed for the 1.10.2 branch. Can you please push a hotifx for the 1.10.2 branch?

Thank you.

**Comment by Kobata** [comment]
As a general rule I don't ever backport anything, sorry.

**Comment by fcpwiz** [comment]
@Kobata Aw that’s too bad. I think a lot of people would love that fix.

**Comment by ajakk** [comment]
You could always do it yourself. InvTweaks is under an open source license, of course.
