### ISSUE TITLE
button10px.png

### ISSUE THREAD

**Issue by VirtualPhilipp** [Inventory-Tweaks/inventory-tweaks#484]
**Minecraft 1.12
Inventory Tweaks 1.62**

In the FAQ there is a statement about custom button textures.
it says to add this texture to the resourcepack:

**assets/inventorytweaks/textures/gui/button10px.png**

the textures won't change therefore i can't create a mod 
support for my resourcepack.

Cheers!

**Comment by Kobata** [comment]
Do you have an example pack with that file I can use to test?

**Comment by VirtualPhilipp** [comment]
Here you go:
https://www.planetminecraft.com/texture_pack/echelon-3980223/

this is my own one. i wanted to add support for your great mod

**Comment by Kobata** [comment]
It seems to work?

![2017-07-12_08 30 34](https://user-images.githubusercontent.com/2323933/28117680-6d51842c-66dc-11e7-8cd2-87a6e8511669.png)

If it wasn't those button backgrounds should be grey if I recall how it works correctly.

**Comment by VirtualPhilipp** [comment]
this is really weird which forge version are you using?

im running 14.21.1.2407 with Minecraft 1.12 and no other mods, only yours

(they should be golden like on your sceenshot)

![2017-07-12_15 32 51](https://user-images.githubusercontent.com/26393504/28120148-7dfe7240-6717-11e7-8cbb-36bc02cc69ec.png)
![2017-07-12_15 32 38](https://user-images.githubusercontent.com/26393504/28120149-7dfff296-6717-11e7-8744-b7de070d117b.png)
![2017-07-12_15 32 43](https://user-images.githubusercontent.com/26393504/28120150-7e093a0e-6717-11e7-8f86-3a9c0e28610c.png)

**Comment by Kobata** [comment]
I just threw it in my debug copy (which is the same as 105, which isn't approved yet, but there weren't any actual code changes from 100) and enabled the resource pack.

It's on Forge 14.21.0.2376, since that's the one currently specified for building.

**Comment by VirtualPhilipp** [comment]
are you running the test directly through eclipse (or etc)? it looks like you are using the debug mode (you have no skin and the gui & pov is at standard) if so, try using the mod in your normal minecraft client

**Comment by Kobata** [comment]
Edit: uhh... 1.62 actually works on 1.12? That's news. That one's built for 1.11.2

**Comment by VirtualPhilipp** [comment]
uhh i dind't know it was for 1.11....

**Comment by Kobata** [comment]
https://minecraft.curseforge.com/projects/inventory-tweaks/files/2448972

Try that version, that's the most recent for 1.12 that's been approved.

**Comment by VirtualPhilipp** [comment]
i will test a 1.11 client now

**Comment by VirtualPhilipp** [comment]
ah okay

**Comment by Kobata** [comment]
Ok yeah, looking through the diff for 1.12 I can see [some changes to the button drawing](https://github.com/Inventory-Tweaks/inventory-tweaks/commit/cfe4ff3cdd8047d1079a6ccc9dd6f609803bee73#diff-42f2adb9c4a5429f6ab8a82a2a737ec6L29) -- and it's also noticeable on your screenshot the buttons have letters instead of the symbols on them, meaning that the custom drawing isn't working.

Still, interesting that it happens to work well enough outside of that issue.

**Comment by VirtualPhilipp** [comment]
im on the dev build now, the button show up now and the correct letters are shown. then this was a bug with the older version. the thing is i code spigot stuff. my plugins usualy need to be updated to work on a new version, didn't expect 1.62 to be for 1.11.2 becaus it worked without any bug. so a big thanks that you have looked into it!

**Comment by Kobata** [comment]
Usually mods need updated too, but FML does some crazy stuff so if the changes are minor enough it doesn't always break in obvious ways.

Frequently things work at least through minor versions, which is why I don't run explicit MC version checks anywhere.
