### ISSUE TITLE
[Cross-mod support] Better Storage Too lockers

### ISSUE THREAD

**Issue by ghost** [Inventory-Tweaks/inventory-tweaks#493]
**Minecraft Version:**
1.10

I put in a request at [Better Storage Too](https://github.com/TehStoneMan/BetterStorageToo/issues/7) for IT support. (I can't do any of the fancy shift-clicking stuff in their lockers.) If there's something they need to do, or not do, to let these two mods play together, a pointer would be appreciated.

**Comment by Kobata** [comment]
Mod support isn't a thing I explicitly add. Much less for old MC versions.
