### ISSUE TITLE
Null pointer for onTickInGUI

### ISSUE THREAD

**Issue by Kinomora** [Inventory-Tweaks/inventory-tweaks#494]
Minecraft: 1.10.2
Forge: 12.18.3.2316
Invtweaks: 1.61-58-a1fd884

I was playing on my server trying to craft something in a crafting station but was experiencing connection issues, I was dropped for a general network timeout twice (which is odd since I have pretty decent ping to the server but that's besides the point) and after reconnecting I was unable to open a crafting station. I tried breaking and replacing it but still could not open one. Then I crashed \o/

Crash report: https://pastebin.com/n5jZEsSc

**Comment by Kobata** [comment]
#394, probably.

Fixed in 1.11+
