### ISSUE TITLE
Moving Items Around With Scroll Will Not Work

### ISSUE THREAD

**Issue by HyperStryker** [Inventory-Tweaks/inventory-tweaks#50]
So in Minecraft 1.5.2 I was on a MP server, opened a chest with some cobble blocks, and since I wanted some cobble, I hovered my mouse over the stack and scrolled [up/down].  Nothing happened.  One by one, the cobblestone blocks WERE supposed to go into my inventory, which seems to be broken in 1.5.2 and not in 1.4.7.  I have Forge and Optifine installed into the .jar and InvTweaks in the mod folder.

**Comment by Kobata** [comment]
See #41
