### ISSUE TITLE
Refined Storage inventory sorting - Crossmod Issue

### ISSUE THREAD

**Issue by DBotThePony** [Inventory-Tweaks/inventory-tweaks#500]
https://github.com/raoulvdberge/refinedstorage/issues/1431

Showup of bug - https://dbot.serealia.ca/sharex/2017/08/302dfb22e9_%25pn_-2017-08-19_20-45-07.webm

**Minecraft Version:** 1.12 (Forge Build 2443)
**Inventory Tweaks Version:** 1.63 (Build 106)

**Comment by Kobata** [comment]
I don't have any specific implementations for modded inventories, it's their fault if they aren't correctly marking what slots correspond to what parts of the inventory.

**Comment by Galaxy2Alex** [comment]
The developer says that he is unaware of any such slot correspondation.
https://github.com/raoulvdberge/refinedstorage/issues/1431
