### ISSUE TITLE
Auto refill feature doesn't work for signs 

### ISSUE THREAD

**Issue by frameperfec** [Inventory-Tweaks/inventory-tweaks#501]
**Minecraft Version: 1.12**
**Inventory Tweaks Version: 1.63 beta 1.08**

As the title says. You might think "why would someone want to put down such a large quantity of signs that this would be a problem?" Well, if you want to remove bedrock, there's a method involving dragon eggs, signs, and lazy chunks. Placing down a full inventory of signs was downright painful. Your mod has spoiled me!

**Comment by Kobata** [comment]
I'm going to WONTFIX this one because it's due to the sign placement opening a UI screen.

While the sign UI is open I can't move items around, so it can't refill when the sign gets removed.
