### ISSUE TITLE
Sorting not working and ... button not available with some mods

### ISSUE THREAD

**Issue by WarKittens** [Inventory-Tweaks/inventory-tweaks#502]
**Minecraft Version:** 1.11.2
**Inventory Tweaks Version:** 1.6.2

I've never run into this before, but sorting, the ... button, and all clicking isn't working on most non-vanilla containers. The Bag of Holding from Extra Utils, anything from Compact Storage, Forestry backpacks, but it DOES work with CoFH mod stuff like Thermal Expansion satchels. Any other info you need? It's not a huge issue but it's just weird.

**Comment by Kobata** [comment]
Mods do stuff differently, and there's no way to know for certain how a mod has internally laid out its containers unless that mod provides that info using the invtweaks API.
