### ISSUE TITLE
Downloading wrong version 1.6.2

### ISSUE THREAD

**Issue by EmergencyTemporalShift** [Inventory-Tweaks/inventory-tweaks#505]
**Minecraft Version:** 1.10.2
**Inventory Tweaks Version:** 1.6.1
I'm trying to download version 1.6.1 but everything I try to download downloads 1.6.2 instead.
Don't know if it's just me, or a problem with Curse but, I tried searching for this problem and nothing came up.
If the problem is just me, could I get a non Curse link? thanks in advance.

**Comment by Kobata** [comment]
I'm... not really sure what you're saying, but the link for 1.61 is https://minecraft.curseforge.com/projects/inventory-tweaks/files/2315240
