### ISSUE TITLE
Item sort not working since i added rules to the file

### ISSUE THREAD

**Issue by JonoRig** [Inventory-Tweaks/inventory-tweaks#515]
Hi,

I am using latest minecraft and inventory-tweaks in tekkit, i attempted to write my own sorting rules, but now my inventory sort doesnt work for me either with middle mouse or r (r just shows me recipes now). The other's on my servers see no issues, and chest's still work fine, it's only my own inventory.

I attempted to write the following:
D locked
1 sword
D2 torch
D3 edibleFood
7 shovel
8 axe
9 pickaxe

but now it doesnt respond

**Comment by Kobata** [comment]
Please make sure to include the default issue header, with *specific* version information ('latest' is incredibly not helpful)

**Comment by JonoRig** [comment]
I am sorry - i have figured the issue out now myself however, so i'll close this.
