### ISSUE TITLE
1.5 Modloader

### ISSUE THREAD

**Issue by AsaAyers** [Inventory-Tweaks/inventory-tweaks#52]
What happened to ModLoader support? It looks like it was silently removed when Minecraft updated to 1.5. I searched but couldn't find any explanation or statement of it being removed.

**Comment by Kobata** [comment]
Read the MCF thread, this has been gone over about 50 times.

**Comment by AsaAyers** [comment]
(top hit on google) http://www.minecraftforum.net/topic/323444-147-inventory-tweaks-150-jan-17/

Linked from above, no mention of modloader on the first page. Not in the FAQ, I guess this isn't a frequently asked question.
http://www.minecraftforum.net/topic/1720872-15x-inventory-tweaks-154-may-1/

It must be in the official docs then. The FAQ here is different... still no mention of ModLoader.
https://inventory-tweaks.readthedocs.org/en/latest/

Didn't find it anywhere on that site, it must be in the issue tracker on github.
    Read the MCF thread, this has been gone over about 50 times.

Thanks, now I completely understand why it was removed. I really appreciate your complete explanation and link to the original discussion.

**Comment by AsaAyers** [comment]
Now for anyone who finds this looking for an expalation, I will link to the explanation.
http://www.minecraftforum.net/topic/1720872-15x-inventory-tweaks-154-may-1/page__st__20#entry21392899

**Comment by LepkoQQ** [comment]
> (top hit on google) http://www.minecraftforum.net/topic/323444-147-inventory-tweaks-150-jan-17/

right under the link to the new thread it says:
_(PS: The new versions don't support ModLoader anymore, please switch to Forge)_

**Comment by AsaAyers** [comment]
Right, but there's no telling if it's a temporary problem or I need to find
a new inventory addon. I'm a developer so a temporary incompatibility might
get fixed by me.
