### ISSUE TITLE
Please do not oredict shulker boxes with chests (request)

### ISSUE THREAD

**Issue by bogger33** [Inventory-Tweaks/inventory-tweaks#523]
I can understand how from a logical standpoint this makes sense, but in practice it unfortunately has a bunch of consequences that make gameplay a tiny bit worse

-it means you can't tell your autocrafting of choice to pull any oredicted chest for a recipe, because one of the hardest to obtain vanilla items shares an oreDict with one of the easiest

-JEI loops through shulker boxes in recipes. For modded recipes, this can have confusing effects. For example, while playing direwolf20 for a good two hours I thought the refined storage disk drive recipe had been changed to require a shulker box, before realizing that JEI was just looping through chest oredict entries. Then later I watched direwolf20 make the same mistake for a second in his let's play.

uh yeah I think that's it. I guess i only really had two. However, I don't really see any benefit to this config, as you wouldn't want to use a shulker box instead of a chest in a recipe basically ever. So I think reversing this decision would make sense.

e: actually, I just thought of a third reason as well: it makes it hard to list all recipes in JEI that genuinely require a shulker box

**Comment by Kobata** [comment]
...
I don't add anything to oredict so whatever you're talking about here has nothing to do with this.

**Comment by bogger33** [comment]
dang, sorry. I was grepping the config folder and assumed this bit in the itemtree was doing it:


            <chests>
                <chest id="chest"/>
                <enderChest id="ender_chest"/>
                <whiteShulkerBox id="white_shulker_box"/>
                <blackShulkerBox id="black_shulker_box"/>
                <redShulkerBox id="red_shulker_box"/>
                <greenShulkerBox id="green_shulker_box"/>
                <brownShulkerBox id="brown_shulker_box"/>
                <blueShulkerBox id="blue_shulker_box"/>
                <purpleShulkerBox id="purple_shulker_box"/>
                <cyanShulkerBox id="cyan_shulker_box"/>
                <silverShulkerBox id="silver_shulker_box"/>
                <grayShulkerBox id="gray_shulker_box"/>
                <pinkShulkerBox id="pink_shulker_box"/>
                <limeShulkerBox id="lime_shulker_box"/>
                <yellowShulkerBox id="yellow_shulker_box"/>
                <lightBlueShulkerBox id="light_blue_shulker_box"/>
                <magentaShulkerBox id="magenta_shulker_box"/>
                <orangeShulkerBox id="orange_shulker_box"/>
            </chests>
