### ISSUE TITLE
Server Issues

### ISSUE THREAD

**Issue by adracamas** [Inventory-Tweaks/inventory-tweaks#524]
**Minecraft Version:** 1.12.2
**Inventory Tweaks Version:** 1.6.3

Playing online and when sorting I will get kicked from the server for "Sending too many packets"

I'm assuming this is too many packets in a short time frame because if I sort a smaller inventory I don't have this issue. Is there a way to delay sending of packets maybe so this won't happen?

**Comment by Kobata** [comment]
#380
