### ISSUE TITLE
Inventory Tweaks Allows Players In Spectator Mode To Take Items From Inventories

### ISSUE THREAD

**Issue by TeetoKaziim** [Inventory-Tweaks/inventory-tweaks#525]
**Minecraft Version:** 1.12.2
**Inventory Tweaks Version:** 1.63

Using Control+Click, or Space+Click, a player in Spectator Mode can swipe items from chests.

In vanilla minecraft, Spectator mode players are not allowed to interact with items in inventories.

**Comment by Kobata** [comment]
Mojang really *had* to choose the one spot to put validation in that'd break, huh.

Anyway, this should make sure on a few levels that spectators can't do stuff.

**Comment by TeetoKaziim** [comment]
I don't know the technical background, but super thanks for sniping this one :D
