### ISSUE TITLE
Crash with latest version of TE

### ISSUE THREAD

**Issue by Sang-bin** [Inventory-Tweaks/inventory-tweaks#527]
**Minecraft Version:** 1.12.2
**Inventory Tweaks Version:** Inventory Tweaks 1.63

Clients close when they get items

**Comment by Kobata** [comment]
Need a crash log or I can't tell you anything.

**Comment by Sang-bin** [comment]
forge 1.12.2-14.23.1.255
CodeChickenLib-1.12.2-3.1.5.331-universal.jar[635 KiB]
CoFHCore-1.12.2-4.3.9.2-universal.jar[743 KiB]
CoFHWorld-1.12.2-1.1.0.11-universal.jar[387 KiB]
InventoryTweaks-1.63.jar[257 KiB]
jei_1.12.2-4.8.5.138.jar[523 KiB]
RedstoneArsenal-1.12.2-2.3.9.2-universal.jar[220 KiB]
RedstoneFlux-1.12-2.0.1.2-universal.jar[32 KiB]
ThermalCultivation-1.12.2-0.1.4.2-universal.jar[60 KiB]
ThermalDynamics-1.12.2-2.3.9.2-universal.jar[699 KiB]
ThermalExpansion-1.12.2-5.3.9.2-universal.jar[2053 KiB]
ThermalFoundation-1.12.2-2.3.9.4-universal.jar[1975 KiB]

+ ---- Minecraft Crash Report ----
+ 
+ WARNING: coremods are present:
+   Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
+ Contact their authors BEFORE contacting forge
+ 
+ // Ouch. That hurt :(
+ 
+ Time: 1/4/18 8:18 PM
+ Description: Ticking player
+ 
+ java.lang.NoClassDefFoundError: cofh/thermalexpansion/gui/container/storage/ContainerSatchel
+ 	at cofh.thermalexpansion.proxy.EventHandler.handleEntityItemPickup(EventHandler.java:30)
+ 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_61_EventHandler_handleEntityItemPickup_EntityItemPickupEvent.invoke(.dynamic)
+ 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
+ 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
+ 	at net.minecraftforge.event.ForgeEventFactory.onItemPickup(ForgeEventFactory.java:439)
+ 	at net.minecraft.entity.item.EntityItem.func_70100_b_(EntityItem.java:396)
+ 	at net.minecraft.entity.player.EntityPlayer.func_71044_o(EntityPlayer.java:600)
+ 	at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:571)
+ 	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2167)
+ 	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234)
+ 	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382)
+ 	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173)
+ 	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209)
+ 	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285)
+ 	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:179)
+ 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:788)
+ 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
+ 	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
+ 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
+ 	at java.lang.Thread.run(Unknown Source)
+ Caused by: java.lang.ClassNotFoundException: cofh.thermalexpansion.gui.container.storage.ContainerSatchel
+ 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
+ 	at java.lang.ClassLoader.loadClass(Unknown Source)
+ 	at java.lang.ClassLoader.loadClass(Unknown Source)
+ 	... 20 more
+ Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer invtweaks.forge.asm.ContainerTransformer@3e66b031 from coremod Inventory Tweaks Coremod
+ 	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:262)
+ 	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
+ 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
+ 	... 22 more
+ Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: cofh.thermalexpansion.gui.container.storage.ContainerSatchel$1
+ 	at org.objectweb.asm.ClassWriter.getCommonSuperClass(Unknown Source)
+ 	at org.objectweb.asm.ClassWriter.a(Unknown Source)
+ 	at org.objectweb.asm.Frame.a(Unknown Source)
+ 	at org.objectweb.asm.Frame.a(Unknown Source)
+ 	at org.objectweb.asm.MethodWriter.visitMaxs(Unknown Source)
+ 	at org.objectweb.asm.tree.MethodNode.accept(Unknown Source)
+ 	at org.objectweb.asm.tree.MethodNode.accept(Unknown Source)
+ 	at org.objectweb.asm.tree.ClassNode.accept(Unknown Source)
+ 	at invtweaks.forge.asm.ContainerTransformer.transform(ContainerTransformer.java:419)
+ 	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:258)
+ 	... 24 more

but ThermalExpansion next new version is fixed
