### ISSUE TITLE
Crashed Client Upon Using /back

### ISSUE THREAD

**Issue by janagyjr** [Inventory-Tweaks/inventory-tweaks#528]
**Minecraft Version: 1.7.10
**Inventory Tweaks Version: 1.59 dev 152

https://github.com/janagyjr/tcgs-chill-pack/issues/3

I've been searching this out and those with the same bug report seem to have had an issue with Inventory Tweaks (related thread [here](http://www.minecraftforum.net/forums/support/modded-client-support/2656884-modpack-crash-pls-help)), however, there is no other version for 1.7.10.

**Comment by Kobata** [comment]
1.7.10 is not supported, please re-open if you have issues with 1.12.2
