### ISSUE TITLE
Compatibility with Thermal Expansion Satchels

### ISSUE THREAD

**Issue by pinter-gabor-at** [Inventory-Tweaks/inventory-tweaks#534]
**Minecraft Version: 1.12.2**
**Inventory Tweaks Version: 1.63+release.109.220f184 or 1.64-dev+release.110.b4fac73**
**Thermal Expansion Version: 5.3.10.14**
It does not sort items in Satchels. No buttons, no shortcut keys, no support.
![inventory tweeks - satchel](https://user-images.githubusercontent.com/6544011/35849130-d5d75a92-0b20-11e8-8189-d3efdbec1936.jpg)

**Comment by Kobata** [comment]
See #502 #530 and probably many others.
