### ISSUE TITLE
[Mod Support] Support Minecolonies' racks

### ISSUE THREAD

**Issue by Sandriell** [Inventory-Tweaks/inventory-tweaks#537]
Currently inventory tweaks is not compatible (or least I can't get it to work) with the racks added by Minecolonies. No sort buttons are presented in the GUI and the middle mouse button does not have any effect.

**Comment by Kobata** [comment]
See the comments on every other request for mod-specific support.

**Comment by Szasdragon** [comment]
Try [this](http://inventory-tweaks.readthedocs.io/en/latest/#adding-configured-compatibility-info)!
