### ISSUE TITLE
Take iron block as iron etc.

### ISSUE THREAD

**Issue by Akxe** [Inventory-Tweaks/inventory-tweaks#54]
I like to use the block version of minerals, but then if I hit: sort in columns it place blocks in a different column. I would love to have the blocks and then have the mineral itself... ex.:Below

PS: if possible have the raw mineral at end of column

![snmek obrazovky 19](https://f.cloud.github.com/assets/2001798/601781/6164f712-cc89-11e2-8a21-4c94bf6fee66.png)
.

**Comment by Kobata** [comment]
The current organization of the tree file doesn't make it really easy to do this. You can always edit your own copy to put whatever items you want in the same category, however.
