### ISSUE TITLE
Actually Additions storage crates bug

### ISSUE THREAD

**Issue by Tiviacz1337** [Inventory-Tweaks/inventory-tweaks#558]
**Minecraft Version: 1.12.2**
**Inventory Tweaks Version: 1.64-dev**

Wrong placement of sorting buttons:

EDIT: Same thing happens in Multi Page Chest from MultiPageChest Mod

![actually additions](https://user-images.githubusercontent.com/34790800/47258822-49560f00-d4a1-11e8-856e-9a3dcb7a9d19.png)

**Comment by Draskh** [comment]
This is also the case in 1.63.

**Comment by SirTwsted** [comment]
yes, I can confirm this.  
its a bit annoying as it gets in the way.

**Comment by Kobata** [comment]
This is mostly intentional: You'll notice if you hide JEI (with whatever key that's set to by default? O?) it moves out: the buttons of 'large' chests are pushed into the UI a little to make sure they're out of the way of that.

**Comment by SirTwsted** [comment]
But who will hide the JEI every time they want to quickly sort the chest.?
Why not put the buttons on the top then ?
Ive seen a few menus that have the buttons on top.  If this is intentional, then something is seriously wrong.
because many players have been complaining about it. maybe most of them wont report it
but they do complain about it because its annoying.
Specially when after sorting, things drop on the floor and you have to pick them back up
and put them back into the inventory and it will still be out of its sorting.

**Comment by Kobata** [comment]
I don't control if the mod sets the setting to move the buttons to the side. It's intended for thing like the old EE2 alchemical chests which have some border on the side but are setup so placing buttons on top would overlap the slots.

**Comment by SirTwsted** [comment]
Huh?
You're the coder of the mod and you have no control ?
Im a python coder and I can control where everything goes and how they are set.
you're saying in Java no one has control to what they do ? im a bit confused.

**Comment by Kobata** [comment]
I don't do any special handling for mod things, just supply a setup to allow the mods to specify their properties. If Actually Additions is saying it wants them placed on the side instead of the top, that's *them* saying that, not me.

**Comment by SirTwsted** [comment]
I have no clue what your talking about, because I have not mentioned anything about Actually Additions mod.

**Comment by Kobata** [comment]
Did you not read the title of this issue?

**Comment by SirTwsted** [comment]
aah ok but this is happening on any chests including AA that has this kind of windowing for inventory.
such as multi-page chest and others.
Let me ask, did you create this mod from scratch or are you just a version maintainer.  
Just curiously asking.

**Comment by KenyMylankca** [comment]
@ellpeck can you fix this please :(
