### ISSUE TITLE
Items without meta differences but different names do not sort well.

### ISSUE THREAD

**Issue by IMarvinTPA** [Inventory-Tweaks/inventory-tweaks#564]
Minecraft Version:  1.12
Inventory Tweaks Version: 1.64.

Items like Bees and Roost's Chicken don't sort well because the item is identical (ID+Meta) and the different names don't trigger the hasDisplayName flag.

**Comment by Kobata** [comment]
It's not really feasible to provide sensible sorting for items with only arbitrary data-tag differences without a significant amount of special casing on a per-item basis that is fairly out of scope.

**Comment by IMarvinTPA** [comment]
https://github.com/Inventory-Tweaks/inventory-tweaks/pull/565
It isn't that deep of a change.  I posted the bug thinking I'd have the pull request up faster.

**Comment by Kobata** [comment]
Well, you did do that in a different way that's more targeted.

Also, for anyone reading the above comment later: While it's true fairly arbitrary data tag checks aren't a thing for the core 'fallback' sorter, the item tree *does* support defining items based on tags in a similar manner to the vanilla commands that allow checking for the presence of items and blocks. (See, for instance, the potion entries)
