### ISSUE TITLE
spectator mode

### ISSUE THREAD

**Issue by Sunekaer** [Inventory-Tweaks/inventory-tweaks#571]
**Minecraft Version:**
1.12.2 Forge-14.23-5.2796
**Inventory Tweaks Version:**
1.63

While in spectator mode:
if you use the options to sort the chest it temporarily puts items in your hand/inventory. By spamming the sorting, you can get items from the chest and keep it.

https://github.com/FTBTeam/FTB-Presents-Stoneblock-2/issues/45

**Comment by Kobata** [comment]
As far as I can tell it's already making sure the player isn't a spectator before commiting any actions on the server side: https://github.com/Inventory-Tweaks/inventory-tweaks/blob/develop/src/main/java/invtweaks/network/packets/ITPacketClick.java#L49

**Comment by DerSoftwerker** [comment]
Sadly the items to get removed from the chest. The sorting does get send to the server too. You can see the items moving in there if a visitor uses the buttons.

The visitor had the items in his inventory, they were gone from the chest and he could give them back to me in the spawn area.

**Comment by Kobata** [comment]
Oh, re-reading timing this fix wasn't in the current release (It is however, literally the first 1.64-dev *after* 1.63). Duplicate #525

**Comment by Sunekaer** [comment]
Are the 1.64 stable enough for being in a pack tho?

**Comment by Kobata** [comment]
https://minecraft.curseforge.com/projects/inventory-tweaks/files/2514356

This one is *just* 1.63 + the spectator stuff basically, so it... should be alright?

And it's not like I really heavily test even the release versions myself anyway.
