### ISSUE TITLE
Inventory Tweaks Issues

### ISSUE THREAD

**Issue by oliverdacre** [Inventory-Tweaks/inventory-tweaks#574]
Minecraft Version: 1.8.9
Inventory Tweaks Version: 1.60

Hey there. I just got Inventory Tweaks and I'm loving it, but I have some issues. I am trying to make a profile for PvP, but fire charges/fireballs, ender pearls and golden apples don't work (although gapples work is you use 'apple').

Any help possible would be greatly appreciated.

**Comment by Kobata** [comment]
You can find the names in the item tree file (the default is visible [here](https://github.com/Inventory-Tweaks/inventory-tweaks/blob/develop/src/main/resources/assets/inventorytweaks/itemtree.xml), but there will also be a copy in the config folder of your minecraft profile)

For instance, golden apples would be `appleGolden`
