### ISSUE TITLE
Support for GregTech Community Edition Chests in 1.12 Please.

### ISSUE THREAD

**Issue by StoneLegion** [Inventory-Tweaks/inventory-tweaks#583]
**Minecraft Version:** 1.12
**Inventory Tweaks Version:** InventoryTweaks-1.64+dev.146

This what the interface looks like:
https://i.imgur.com/MEcamXb.png

It has a sort button and don't care much about it but I can't space / shift click bunch items in at once sadly. It's used as the main chest in many packs like FTB Interactions so having basic manipulation would be quite amazing. 

Thanks.

**Comment by Kobata** [comment]
Supporting mod containers is entirely on that mod providing the correct info.

**Comment by Archengius** [comment]
and on you at least making your mod run in dev environment and providing adequate API behavior.
