### ISSUE TITLE
Storage Crates from Actually Additions buttons conflicts with inventory spaces.

### ISSUE THREAD

**Issue by RepoDraghon** [Inventory-Tweaks/inventory-tweaks#584]
1.12.2
1.63+release.109.220f184
![Untitled](https://user-images.githubusercontent.com/8423696/57358496-6810b000-712a-11e9-9ccc-2ccda623684f.jpg)

**Comment by Kobata** [comment]
#558

**Comment by RepoDraghon** [comment]
No mention that it's been fixed or any reply? just closed? ok......
