### ISSUE TITLE
Such Mod Compatibility Issues

### ISSUE THREAD

**Issue by KenyMylankca** [Inventory-Tweaks/inventory-tweaks#585]
**Minecraft Version:**1.12.2
**Inventory Tweaks Version:**InventoryTweaks-1.64+dev.146

Used Forge 2836. And it also breaks the JEI GUI:
![aaa](https://user-images.githubusercontent.com/41585837/57385959-157fd400-71bc-11e9-8152-63a5851adedd.PNG)

**Comment by KenyMylankca** [comment]
And ah, it doesn't work with Applied Energistics' Skystone Chest too.

**Comment by KenyMylankca** [comment]
Aaaand, the buttons are inside the items grid(GUI) in Actually Additions' Storage Crate:
![sdsd](https://user-images.githubusercontent.com/41585837/57386333-cdad7c80-71bc-11e9-980b-7a0e03dcbeeb.PNG)

**Comment by Kobata** [comment]
#583 etc, #558
