### ISSUE TITLE
Item icons missing or partially visible.

### ISSUE THREAD

**Issue by AdamHH11** [Inventory-Tweaks/inventory-tweaks#59]
I use magic launcher for my mods, this is my setup for 1.5.2:

Mods:
minecraftforge-universal (v725)
Click Mining Fix
Optifine HD Ultra D3
liteloader

External Mods: 

Audiotori r6
InventoryTweaks v1.54b (or 1.53)
MAtmos

The problem is that that all my icons for anything except block entities are invisible or half there. This only occurs with texture packs other than default, however. The fix I have at the moment is using optifine to switch textures back and forth in-game.

Any ideas?

**Comment by Kobata** [comment]
Wrong place, this isn't a bug in inventory tweaks since we don't do rendering.

It's probably optifine, however, since it loves to break other mods quite frequently.
