### ISSUE TITLE
Buttons are not at the right place for the CookingForBlockheads' fridge

### ISSUE THREAD

**Issue by ExDomino** [Inventory-Tweaks/inventory-tweaks#590]
**Minecraft Version:** 1.12.2
**Inventory Tweaks Version:** 1.64+dev.146
**Cooking For Blockheads Version:** 6.4.70

Hello,

The buttons from Inventory Tweaks are not at the right place when opening the fridge from Cooking For Blockheads. They should be placed at the top right as a normal chest.

**Screenshot:** https://image.noelshack.com/fichiers/2019/23/7/1560061699-2019-06-09-02-27-18.png
**Fridge Item ID:** ```<cookingforblockheads:fridge>```

Thank you in advance!

**Comment by Kobata** [comment]
#558

**Comment by ExDomino** [comment]
I open an issue on their side then.
**Reference Issue:** https://github.com/blay09/CookingForBlockheads/issues/379

**Comment by BlayTheNinth** [comment]
The naming and docs of `IsLargeCallback` could use some clarification, I misunderstood (or copied from someone who misunderstood, can't remember) it as a single vs. double chest thing rather than a "don't put buttons at the top" thing.

**Comment by Kobata** [comment]
The original use was for things like EE2's alchemical chests (i.e., much bigger than a double chest, and I think at least at one point they had very thin top borders)
