### ISSUE TITLE
No 1.14 support?

### ISSUE THREAD

**Issue by UpwardCabbage3** [Inventory-Tweaks/inventory-tweaks#604]
**Minecraft Version:**
**Inventory Tweaks Version:**

**Comment by Azagwen** [comment]
Why no 1.14 support ? Where are all the old mods like IT ?

**Comment by mkalam-alami** [comment]
In case you missed our recent announcement:

> There are currently no plans to upgrade Inventory Tweaks to Minecraft 1.13+. Due to major changes in the game code and in Forge's API, supporting the newest versions of the game would require a major mod rewrite, which the current maintainers do not have the time for.

This is a problem that affected pretty much all historic mods out there, and depending on the type of mod some were harder than others to port. For InvTweaks we've opened up the mod to applications for new maintainers, but the most probable future is that a brand new alternative will be eventually created and published. Our best chance currently is [Landmasters "IT Reborn" effort](https://github.com/Inventory-Tweaks/inventory-tweaks/issues/612)!
