### ISSUE TITLE
Impossible to gradle

### ISSUE THREAD

**Issue by Reithsaw** [Inventory-Tweaks/inventory-tweaks#607]
When i want to start " gradlew genEclipseRuns " They give me this : 

FAILURE: Build failed with an exception.                                                                                > root project
> root project
* Where:
Build file 'F:\Minecraft\inventory-tweaks-develop\build.gradle' line: 132

* What went wrong:
A problem occurred evaluating root project 'inventory-tweaks-develop'.
> You must specify the full forge version, including MC version in your build.gradle. Example: 1.12.2-14.23.5.2811

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s

**Comment by Kobata** [comment]
You can just edit [the line in `gradle.properties`](https://github.com/Inventory-Tweaks/inventory-tweaks/blob/develop/gradle.properties#L6) if needed, forge seems to keep changing how you need to write that.
