### ISSUE TITLE
better storage not supported anymore?

### ISSUE THREAD

**Issue by skreeby** [Inventory-Tweaks/inventory-tweaks#61]
There is no sort button on the gui of the chests from better storage
running latest versions of both mods.

**Comment by ChrisLane** [comment]
I believe it was changed so that other mods have to hook into InvTweaks' API to enable sorting due to previous issues with unsupported modded inventories.

**Comment by skreeby** [comment]
is there any way to get this working myself?

**Comment by Kobata** [comment]
It should work on dev versions (and possibly release + recent better storage), but I can't make it magically work when the people making mods decide to rename things. This is why the API exists though, so I don't have to constantly keep up with every semi-popular mod and every time they decide to rename their classes.

**Comment by skreeby** [comment]
thank you kindly
