### ISSUE TITLE
Autorefill prefers Cracked/Mossy Stone Bricks (id. 98.1-2) over Stone Bricks (id. 98.0).

### ISSUE THREAD

**Issue by competentfake** [Inventory-Tweaks/inventory-tweaks#62]
I noted that a similar issue was presented here: ( https://github.com/Kobata/inventory-tweaks/issues/45 ), but while the Autofill function does seem to respect metadata on wool, when a stack of Stone Bricks runs out, it persistently autorefills with Cracked or Mossy Stone Bricks if there are any available in the inventory alongside the regular variety.  Thanks!  :)  ~Fake

**Comment by Kobata** [comment]
It should treat them the same as wool, are you testing in the versions that actually have that fixed? (It's not in 1.54b)

**Comment by competentfake** [comment]
I'm running 1.5.2.  I'll try updating to .4.  Sorry, I didn't know to check the milestones.
