### ISSUE TITLE
Error while sorting

### ISSUE THREAD

**Issue by nicolas-abril** [Inventory-Tweaks/inventory-tweaks#63]
When I click to sort the inventory it seems to get every item out of the bar except  pickaxes wich are moved to the last slot of the hotbar.
My seetings are
 D LOCKED
D1 pickaxe
D2 shovel
D3 axe
D4 sword
D9 torch

**Comment by nicolas-abril** [comment]
Also the auto-refill is not working and when i try to open the shortvuts mapping file it gives a message that says Acess denied.
The only other mod that I have is Aether 2

**Comment by Kobata** [comment]
Aether 2 is not compatible because it edits the player's base inventory.
