### ISSUE TITLE
Mushroom Stew does not autorefill correctly

### ISSUE THREAD

**Issue by aintrandom** [Inventory-Tweaks/inventory-tweaks#65]
The soups won't refill by themselves, and they aren't refilling either when I press the sort key. (The empty bowls are just staying on the hotbar)

My config file :

```
D LOCKED
D1 sword
D2 pickaxe
D3 edibleFood
D3-D7 mushroomStew
D8 blocks
D9 compass
```

**Comment by Kobata** [comment]
Probably fallout from making wool & other colored blocks not refill with different colors than you had selected normally.

**Comment by aintrandom** [comment]
I don't understand what you mean with wool, and stuff like that.

BTW, my config had a typo, it's "D8 block" (but it still doesn't refill properly)

**Comment by Kobata** [comment]
Probably caused by the reversed priorities. Unable to reproduce in latest.
