### ISSUE TITLE
Buggy Sorting

### ISSUE THREAD

**Issue by Rjwrocks** [Inventory-Tweaks/inventory-tweaks#66]
When sorting, I push the sort key and then it sorts for a second, then resets, and puts either my shovel or my bow in my hand. In my hand meaning when you open the inventory, it is where your cursor is.
![2013-07-09_15 11 13](https://f.cloud.github.com/assets/4977010/771502/e7870ca0-e8e4-11e2-994d-f8a968804752.png)

**Comment by ChrisLane** [comment]
When you're doing your sorting are you on a server?

**Comment by Rjwrocks** [comment]
You are correct. (A.K.A) yes

**Comment by ChrisLane** [comment]
From what I understand this is usually just an issue with either nocheatplus or just with servers in general. You need to have invtweaks installed server side for there to be better compatibility.

**Comment by Rjwrocks** [comment]
But with 1.54B it wasn't a problem.

**Comment by roger21** [comment]
i have exaclty that problem on a bukkit server without nocheat plugin (it is new with the 1.6.2 update, it worked before)

as said in the forum it usually fails when there are enchanted items involved  - or maybe just tools and weapons since i only have enchanted tools and weapons - and it apparently never fails when there are just basic stackable items involved

**Comment by Rjwrocks** [comment]
So do you have a solution, anyone?

**Comment by Kobata** [comment]
This is server stuff that is out of my control as a general rule. Getting the mod installed on the server can help by bypassing the checks the server does, but this seems to be an issue with Bukkit in particular, so there's probably a subtle bug in their handling of clicks if it's not being blocked by a specific plugin.

**Comment by bendem** [comment]
It seem to be related to items with durability / enchantment... Maybe it's nbt related ? (Would be happy to see it fixed... Maybe I can help you in some ways, i'm interrested in bukkit dev)

**Comment by Kobata** [comment]
All I can say is basically what I said before: These things are practically impossible to fix in the mod (Other than the lazy 'bypass all the checks totally' thing the server-install module does, but that requires a Forge or MCPC+ server, it's not a bukkit plugin)

It _should_ be possible to cause the same issue by taking two of the items it doesn't like and rapidly clicking between them to pick them up/place them. If you can get that to happen, it's probably better to file a bukkit bug report and not mention this mod at all.

**Comment by bendem** [comment]
Will see that and come back with an answer (or not if it don't work :wink: )

**Comment by Kobata** [comment]
While going through and testing stuff I tried throwing a bunch of NBT/non-NBT items in a chest on a bukkit server and had no problems sorting it, so it's probably a plugin-related issue (or something they fixed more recently, although I doubt that).
