### ISSUE TITLE
Crashes when running Better Sprinting 1.6.2 at the same time

### ISSUE THREAD

**Issue by Stolan00** [Inventory-Tweaks/inventory-tweaks#67]
Whenever I try to run this with Better Sprinting for Minecraft 1.6.2, it crashes when I open my inventory. It just says "Shutting down an internal server" and then the game closes. Anyone have an idea if there's a fix or a different version or anything?

**Comment by Kobata** [comment]
Tell Better Sprinting to stop replacing classes entirely in his transformer or, at least, to make everything in the replaced classes public so that replacing it doesn't break things expecting to change access levels of members of that class.

**Comment by Stolan00** [comment]
Thanks. He seems to have just updated it for Forge, so maybe it's an issue he's working on. Thanks anyway. Great mod, by the way.
