### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by kyleboze** [Inventory-Tweaks/inventory-tweaks#68]
Inv tweaks will not work and crashes minecraft. Forge, Rei Minimap, and optfine being used.

**Comment by ghost** [comment]
No one can help you if you don't include a crash log...

**Comment by kyleboze** [comment]
Here it is

---- Minecraft Crash Report ----
// I just don't know what went wrong :(

Time: 7/12/13 1:04 PM
Description: Exception in server tick loop

java.lang.NullPointerException
    at net.minecraft.server.MinecraftServer.c(SourceFile:800)
    at bkw.a(IntegratedServer.java:115)
    at bkw.d(IntegratedServer.java:139)
    at net.minecraft.server.MinecraftServer.run(SourceFile:314)
    at hh.run(SourceFile:582)

## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.6.2
    Operating System: Mac OS X (x86_64) version 10.7.5
    Java Version: 1.6.0_51, Apple Inc.
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Apple Inc.
    Memory: 314528288 bytes (299 MB) / 362676224 bytes (345 MB) up to 362676224 bytes (345 MB)
    JVM Flags: 2 total; -Xms350m -Xmx350m
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Suspicious classes: IWrUpdater, Config, WrUpdaterThreaded, ...[cpw.mods.fml.client.FMLClientHandler, CustomModLoadingErrorDisplayException, GuiWrongMinecraft, ...], [cpw.mods.fml.client.registry.ISimpleBlockRenderingHandler, RenderingRegistry], [cpw.mods.fml.common.LoaderException, FMLCommonHandler, TickType, ...], [cpw.mods.fml.common.modloader.BaseModProxy], [cpw.mods.fml.common.network.FMLPacket, EntitySpawnPacket, EntitySpawnAdjustmentPacket, ...], [cpw.mods.fml.common.registry.EntityRegistration], [cpw.mods.fml.common.toposort.ModSortingException], [cpw.mods.fml.relauncher.Side], [net.minecraftforge.client.ForgeHooksClient, ItemRenderType, IItemRenderer, ...], [net.minecraftforge.client.event.DrawBlockHighlightEvent, RenderWorldLastEvent, TextureStitchEvent, ...], [net.minecraftforge.common.MinecraftForge, ForgeInternalHandler, ForgeHooks, ...], [net.minecraftforge.event.EventBus, IEventListener, ListenerList, ...], [net.minecraftforge.event.entity.EntityEvent], [net.minecraftforge.event.entity.item.ItemEvent, ItemTossEvent], [net.minecraftforge.event.entity.living.LivingEvent, LivingSetAttackTargetEvent, LivingUpdateEvent, ...], [net.minecraftforge.event.world.WorldEvent, Load, Unload, ...], [net.minecraftforge.fluids.FluidRegistry, FluidRegisterEvent, Fluid, ...], [reifnsk.minimap.ReiMinimap, GuiScreenInterface, GuiOptionScreen, ...]
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    Profiler Position: N/A (disabled)
    Player Count: 0 / 8; []
    Type: Integrated Server (map_client.txt)
    Is Modded: Very likely; Jar signature invalidated

**Comment by Kobata** [comment]
Forge is not installed correctly, as shown by your log showing bkw. instead of net.minecraft.server.integrated.IntegratedServer

Use the forge installer and import that profile into whatever launcher you're using.
