### ISSUE TITLE
Russian translation display bug

### ISSUE THREAD

**Issue by Black-Sunlight** [Inventory-Tweaks/inventory-tweaks#70]
Everything in this screenshot
InvTweaks v1.55
<center><a href="http://s6.hostingkartinok.com/uploads/images/2013/07/83d112bd29e7604b56aa1756e34199a1.png"><img src="http://s4.hostingkartinok.com/uploads/images/2013/07/b9f94e308b7c413a648e2d3b268c151d.jpg" border=0></a>&nbsp;&nbsp;</center>

**Comment by Kobata** [comment]
Already fixed b5f99e37908efe58ac765a7baab06c3fa7e1f7d9
