### ISSUE TITLE
Wont Sort Special Text Items

### ISSUE THREAD

**Issue by BMK2** [Inventory-Tweaks/inventory-tweaks#72]
The server that I play on has a plugin that allows items to have special text below their names. When I try to sort a chest with an item like that in it, it goes all weird and trys to give me the item. It works sometimes when there is only 1 item like that in it, but definately not with more than 1. 

None of these items have th special text
![2013-07-17_08 40 17](https://f.cloud.github.com/assets/5030972/811704/9e1af4c8-eede-11e2-81c0-a58bf5233b3d.png)
And they sort just fine
![2013-07-17_08 40 25](https://f.cloud.github.com/assets/5030972/811703/9e1d7cac-eede-11e2-8903-58117a8ce4e7.png)
But these items
![2013-07-17_08 40 48](https://f.cloud.github.com/assets/5030972/811706/9e1d2824-eede-11e2-9c91-07e3c899ad9d.png)
all have a special text on them
![2013-07-17_08 40 45](https://f.cloud.github.com/assets/5030972/811705/9e1e6d10-eede-11e2-8410-cae0ac083dc5.png)
![2013-07-17_08 40 52](https://f.cloud.github.com/assets/5030972/811707/9e1e2a58-eede-11e2-98c5-70b403319284.png)
![2013-07-17_08 40 55](https://f.cloud.github.com/assets/5030972/811708/9e23c4cc-eede-11e2-81bb-2e90f63e9f5a.png)
And when I try to sort them, it goes all weird like this and puts 1 of the items into my hand like below with the redstone
![2013-07-17_08 41 02](https://f.cloud.github.com/assets/5030972/811709/9e24b954-eede-11e2-937e-857c4edd7f68.png)

If there is something that I need to do let me know. Otherwise please fix this soon, because the server is filling more and more items with special text.

**Comment by Kobata** [comment]
These are server-side bugs with item handling, nothing I can directly fix. All bugs that result in this issue are trigger-able without this mod by anything that can cause clicking rapidly enough.
