### ISSUE TITLE
Crash when opens inventory

### ISSUE THREAD

**Issue by b7love** [Inventory-Tweaks/inventory-tweaks#76]
I have Forge and Zan's minimap installed that work fine but when I go to install inv tweaks and load up, it works fine until I go to my inventory and then the game crashes...here is my error info:

---- Minecraft Crash Report ----
// Shall we play a game?

Time: 7/23/13 9:45 PM
Description: Unexpected error

java.lang.NoClassDefFoundError: net/minecraft/util/ResourceLocation
    at invtweaks.InvTweaks.handleGUILayout(InvTweaks.java:756)
    at invtweaks.InvTweaks.onTickInGUI(InvTweaks.java:139)
    at invtweaks.forge.ForgeClientTick.tickEnd(ForgeClientTick.java:43)
    at cpw.mods.fml.common.SingleIntervalHandler.tickEnd(SingleIntervalHandler.java:34)
    at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:141)
    at cpw.mods.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:367)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1956)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:898)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:826)
    at net.minecraft.client.main.Main.main(SourceFile:101)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:57)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:18)
Caused by: java.lang.ClassNotFoundException: net.minecraft.util.ResourceLocation
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:179)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 16 more
Caused by: java.lang.NullPointerException
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at invtweaks.InvTweaks.handleGUILayout(InvTweaks.java:756)
    at invtweaks.InvTweaks.onTickInGUI(InvTweaks.java:139)
    at invtweaks.forge.ForgeClientTick.tickEnd(ForgeClientTick.java:43)
    at cpw.mods.fml.common.SingleIntervalHandler.tickEnd(SingleIntervalHandler.java:34)
    at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:141)
    at cpw.mods.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:367)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityClientPlayerMP['b7love'/321, l='MpServer', x=124.67, y=91.62, z=77.21]]
    Chunk stats: MultiplayerChunkCache: 441
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: World: (56,64,256), Chunk: (at 8,4,0 in 3,16; contains blocks 48,0,256 to 63,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 2795167 game time, 2888107 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
    Forced entities: 125 total; [EntityLeashKnot['entity.LeashKnot.name'/317, l='MpServer', x=101.50, y=67.50, z=144.50], EntityLeashKnot['entity.LeashKnot.name'/316, l='MpServer', x=99.50, y=66.50, z=141.50], EntityLeashKnot['entity.LeashKnot.name'/319, l='MpServer', x=101.50, y=66.50, z=144.50], EntityLeashKnot['entity.LeashKnot.name'/318, l='MpServer', x=99.50, y=67.50, z=141.50], EntityLeashKnot['entity.LeashKnot.name'/320, l='MpServer', x=98.50, y=67.50, z=142.50], EntityChicken['Chicken'/383, l='MpServer', x=77.63, y=98.00, z=58.38], EntityChicken['Chicken'/379, l='MpServer', x=53.47, y=77.00, z=45.41], EntityChicken['Chicken'/410, l='MpServer', x=130.56, y=67.00, z=19.56], EntityItem['item.item.egg'/411, l='MpServer', x=135.56, y=66.13, z=21.28], EntityChicken['Chicken'/409, l='MpServer', x=139.56, y=65.00, z=15.41], EntityChicken['Chicken'/415, l='MpServer', x=146.44, y=64.00, z=-0.56], EntitySpider['Spider'/143, l='MpServer', x=54.84, y=84.00, z=73.84], EntityZombie['Zombie'/142, l='MpServer', x=68.40, y=71.00, z=79.25], EntityChicken['Chicken'/402, l='MpServer', x=112.59, y=69.00, z=-0.56], EntityChicken['Chicken'/403, l='MpServer', x=121.41, y=68.00, z=-0.41], EntitySlime['Slime'/133, l='MpServer', x=45.31, y=15.00, z=74.69], EntityCreeper['Creeper'/132, l='MpServer', x=47.50, y=15.00, z=73.50], EntityItem['item.item.egg'/395, l='MpServer', x=91.88, y=98.13, z=49.25], EntityChicken['Chicken'/394, l='MpServer', x=91.25, y=107.00, z=55.53], EntityChicken['Chicken'/153, l='MpServer', x=74.34, y=111.00, z=76.47], EntityChicken['Chicken'/393, l='MpServer', x=91.53, y=98.00, z=50.31], EntityItem['item.item.egg'/154, l='MpServer', x=72.72, y=111.13, z=77.03], EntityItem['item.item.egg'/392, l='MpServer', x=84.97, y=91.13, z=55.88], EntitySlime['Slime'/155, l='MpServer', x=75.31, y=14.00, z=133.31], EntitySlime['Slime'/156, l='MpServer', x=76.31, y=13.00, z=132.31], EntitySlime['Slime'/157, l='MpServer', x=76.31, y=13.00, z=135.33], EntityChicken['Chicken'/398, l='MpServer', x=119.56, y=113.00, z=38.41], EntityPig['Pig'/158, l='MpServer', x=94.47, y=61.00, z=77.53], EntityItem['item.item.egg'/397, l='MpServer', x=103.13, y=88.13, z=25.22], EntityChicken['Chicken'/159, l='MpServer', x=94.84, y=61.00, z=77.16], EntityChicken['Chicken'/396, l='MpServer', x=106.34, y=90.00, z=24.78], EntityZombie['Zombie'/144, l='MpServer', x=53.00, y=84.00, z=72.31], EntityChicken['Chicken'/145, l='MpServer', x=50.53, y=104.00, z=68.59], EntityItem['item.item.egg'/386, l='MpServer', x=77.53, y=114.13, z=63.19], EntityChicken['Chicken'/385, l='MpServer', x=71.66, y=110.00, z=56.47], EntityHorse['Horse'/147, l='MpServer', x=53.00, y=37.00, z=115.25], EntityChicken['Chicken'/384, l='MpServer', x=84.47, y=113.00, z=60.53], EntityHorse['Horse'/148, l='MpServer', x=61.34, y=70.00, z=116.84], EntityItem['item.item.egg'/391, l='MpServer', x=81.88, y=89.13, z=58.03], EntitySkeleton['Skeleton'/149, l='MpServer', x=48.50, y=30.00, z=141.50], EntityItem['item.item.egg'/390, l='MpServer', x=89.09, y=72.13, z=44.88], EntityChicken['Chicken'/389, l='MpServer', x=90.47, y=73.00, z=44.47], EntitySlime['Slime'/171, l='MpServer', x=100.31, y=18.02, z=101.69], EntitySlime['Slime'/170, l='MpServer', x=102.63, y=17.47, z=101.38], EntityItem['item.item.slimeball'/169, l='MpServer', x=110.13, y=11.13, z=100.13], EntitySlime['Slime'/168, l='MpServer', x=89.31, y=20.00, z=129.72], EntitySlime['Slime'/175, l='MpServer', x=99.31, y=34.81, z=109.54], EntitySlime['Slime'/174, l='MpServer', x=99.77, y=36.00, z=99.31], EntitySlime['Slime'/173, l='MpServer', x=107.22, y=25.00, z=98.41], EntitySlime['Slime'/172, l='MpServer', x=110.69, y=22.47, z=109.69], EntitySquid['Squid'/163, l='MpServer', x=88.13, y=61.00, z=86.41], EntitySquid['Squid'/162, l='MpServer', x=88.50, y=59.00, z=82.28], EntitySlime['Slime'/434, l='MpServer', x=198.31, y=17.00, z=17.31], EntitySquid['Squid'/161, l='MpServer', x=87.97, y=61.00, z=79.50], EntityChicken['Chicken'/435, l='MpServer', x=193.53, y=116.00, z=29.56], EntityChicken['Chicken'/160, l='MpServer', x=85.56, y=64.00, z=78.47], EntitySlime['Slime'/167, l='MpServer', x=83.20, y=11.00, z=126.79], EntityHorse['Horse'/166, l='MpServer', x=86.38, y=55.00, z=97.50], EntityHorse['Horse'/165, l='MpServer', x=89.28, y=53.00, z=96.72], EntitySquid['Squid'/164, l='MpServer', x=91.06, y=61.25, z=88.44], EntitySlime['Slime'/186, l='MpServer', x=114.78, y=35.00, z=110.78], EntitySkeleton['Skeleton'/187, l='MpServer', x=112.09, y=36.00, z=108.50], EntitySlime['Slime'/427, l='MpServer', x=190.69, y=14.08, z=12.72], EntityHorse['Horse'/184, l='MpServer', x=117.16, y=68.00, z=83.44], EntityChicken['Chicken'/426, l='MpServer', x=180.47, y=94.00, z=-2.53], EntitySlime['Slime'/185, l='MpServer', x=115.69, y=22.14, z=104.67], EntitySlime['Slime'/190, l='MpServer', x=118.38, y=34.64, z=127.38], EntityChicken['Chicken'/429, l='MpServer', x=188.47, y=113.00, z=25.56], EntitySlime['Slime'/428, l='MpServer', x=183.69, y=12.00, z=11.69], EntitySlime['Slime'/188, l='MpServer', x=118.78, y=34.18, z=124.78], EntitySlime['Slime'/189, l='MpServer', x=127.69, y=34.00, z=120.69], EntityItem['item.item.egg'/430, l='MpServer', x=187.03, y=113.13, z=25.88], EntityPig['Pig'/178, l='MpServer', x=104.50, y=59.00, z=115.31], EntityHorse['Horse'/179, l='MpServer', x=101.66, y=66.00, z=139.59], EntitySquid['Squid'/176, l='MpServer', x=104.75, y=60.16, z=100.94], EntitySquid['Squid'/177, l='MpServer', x=113.34, y=61.34, z=99.50], EntityChicken['Chicken'/421, l='MpServer', x=174.28, y=104.00, z=11.06], EntityHorse['Horse'/182, l='MpServer', x=99.29, y=66.00, z=144.68], EntityHorse['Horse'/183, l='MpServer', x=101.05, y=66.00, z=143.08], EntitySlime['Slime'/420, l='MpServer', x=175.31, y=10.00, z=13.69], EntityHorse['Horse'/180, l='MpServer', x=101.06, y=66.00, z=141.20], EntityHorse['Horse'/181, l='MpServer', x=99.32, y=66.00, z=142.54], EntityWaypoint['unknown'/1972, l='MpServer', x=-2984.00, y=56.00, z=344.00], EntitySlime['Slime'/205, l='MpServer', x=148.53, y=19.02, z=79.69], EntityPig['Pig'/207, l='MpServer', x=145.53, y=72.00, z=78.31], EntitySlime['Slime'/206, l='MpServer', x=147.38, y=19.00, z=78.69], EntityWaypoint['unknown'/1968, l='MpServer', x=126.00, y=11.00, z=23.00], EntitySlime['Slime'/200, l='MpServer', x=137.66, y=17.00, z=103.16], EntityWaypoint['unknown'/1969, l='MpServer', x=-1008.00, y=64.00, z=1496.00], EntityWaypoint['unknown'/1970, l='MpServer', x=112.00, y=63.00, z=64.00], EntityWaypoint['unknown'/1971, l='MpServer', x=-2848.00, y=59.00, z=72.00], EntitySlime['Slime'/197, l='MpServer', x=140.63, y=16.00, z=108.38], EntitySlime['Slime'/196, l='MpServer', x=132.31, y=19.00, z=103.31], EntitySlime['Slime'/199, l='MpServer', x=133.31, y=19.00, z=104.69], EntitySlime['Slime'/198, l='MpServer', x=143.31, y=17.07, z=97.43], EntityChicken['Chicken'/193, l='MpServer', x=150.28, y=62.46, z=94.03], EntitySlime['Slime'/192, l='MpServer', x=139.31, y=18.00, z=94.31], EntitySlime['Slime'/195, l='MpServer', x=141.31, y=16.00, z=99.31], EntitySlime['Slime'/194, l='MpServer', x=143.20, y=16.47, z=99.21], EntitySlime['Slime'/212, l='MpServer', x=159.65, y=19.00, z=111.69], EntitySlime['Slime'/213, l='MpServer', x=145.51, y=16.47, z=109.69], EntityPig['Pig'/214, l='MpServer', x=148.31, y=63.00, z=99.81], EntitySlime['Slime'/208, l='MpServer', x=145.31, y=18.00, z=94.31], EntitySlime['Slime'/209, l='MpServer', x=145.84, y=16.00, z=101.80], EntitySlime['Slime'/210, l='MpServer', x=158.89, y=19.00, z=111.69], EntitySlime['Slime'/211, l='MpServer', x=148.49, y=16.02, z=100.20], EntitySheep['Sheep'/234, l='MpServer', x=170.84, y=69.00, z=142.88], EntitySlime['Slime'/233, l='MpServer', x=165.22, y=33.00, z=113.22], EntitySlime['Slime'/232, l='MpServer', x=166.31, y=23.00, z=120.69], EntitySlime['Slime'/231, l='MpServer', x=161.69, y=19.00, z=99.31], EntitySlime['Slime'/230, l='MpServer', x=162.38, y=19.00, z=100.63], EntityLeashKnot['entity.LeashKnot.name'/502, l='MpServer', x=119.50, y=69.50, z=83.50], EntitySlime['Slime'/229, l='MpServer', x=162.69, y=19.00, z=109.69], EntityZombie['Zombie'/228, l='MpServer', x=160.50, y=20.00, z=76.50], EntitySlime['Slime'/227, l='MpServer', x=160.69, y=20.00, z=78.31], EntitySlime['Slime'/226, l='MpServer', x=163.31, y=21.04, z=71.35], EntitySlime['Slime'/225, l='MpServer', x=172.69, y=21.00, z=78.31], EntityOcelot['Ocelot'/250, l='MpServer', x=196.63, y=80.00, z=139.88], EntityOcelot['Ocelot'/251, l='MpServer', x=188.99, y=79.00, z=138.44], EntityOcelot['Ocelot'/248, l='MpServer', x=201.16, y=77.00, z=142.94], EntityOcelot['Ocelot'/249, l='MpServer', x=200.66, y=77.00, z=142.44], EntityOcelot['Ocelot'/247, l='MpServer', x=201.69, y=77.00, z=143.69], EntityOcelot['Ocelot'/242, l='MpServer', x=182.50, y=85.00, z=129.50], EntityClientPlayerMP['b7love'/321, l='MpServer', x=124.67, y=91.62, z=77.21], EntitySlime['Slime'/241, l='MpServer', x=176.69, y=27.00, z=104.69]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:440)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2298)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:851)
    at net.minecraft.client.main.Main.main(SourceFile:101)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:57)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:18)

-- System Details --
Details:
    Minecraft Version: 1.6.2
    Operating System: Windows 8 (amd64) version 6.2
    Java Version: 1.7.0_17, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 1053613840 bytes (1004 MB) / 2378956800 bytes (2268 MB) up to 3817799680 bytes (3640 MB)
    JVM Flags: 1 total; -Xmx4G
    AABB Pool Size: 15587 (872872 bytes; 0 MB) allocated, 1712 (95872 bytes; 0 MB) used
    Suspicious classes: FML and Forge are installed
    IntCache: cache: 0, tcache: 0, allocated: 3, tallocated: 63
    FML: MCP v8.04 FML v6.2.6.777 Minecraft Forge 9.10.0.777 5 mods loaded, 5 mods active
    mcp{8.04} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    FML{6.2.6.777} [Forge Mod Loader](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Forge{9.10.0.777} [Minecraft Forge](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    inventorytweaks{1.55b} [Inventory Tweaks](InventoryTweaks-MC1.6.2-1.55b-b61.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    mod_ZanMinimap{0.9.4} [Zan's Minimap](ZansMinimap1.6.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Launched Version: Forge9.10.0.777
    LWJGL: 2.9.0
    OpenGL: GeForce GT 620/PCIe/SSE2 GL version 4.3.0, NVIDIA Corporation
    Is Modded: Definitely; Client brand changed to 'fml,forge'
    Type: Client (map_client.txt)
    Resource Pack: LB Photo Realism x256 10.0.0-converted-1374012707213.zip
    Current Language: English (US)
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 4863 (272328 bytes; 0 MB) allocated, 694 (38864 bytes; 0 MB) used

**Comment by Kobata** [comment]
Forge 778 or higher.
