### ISSUE TITLE
Auto-refill doesn't work

### ISSUE THREAD

**Issue by 4EverLonely** [Inventory-Tweaks/inventory-tweaks#77]
I was fishing around and the rod broke,and it didn't refill right away, I had to open the inventory and somehow right clicked, and the rod jumped to the slot where the previous one broke

**Comment by Kobata** [comment]
Sometimes this happens in multiplayer because of how the server sends signals like that back -- sometimes it also replaces things too early when the client thinks it broke but the server doesn't. It's not really something very easy to fix.
