### ISSUE TITLE
Minecraft won't open when installed

### ISSUE THREAD

**Issue by Jammie98** [Inventory-Tweaks/inventory-tweaks#79]
When I install it with MagicLauncher it gets to the Mojang screen then just closes.

Edit: I'm an idiot. I didn't read that it had to be in the mods folder. Sorry for bothering you.

**Comment by Kobata** [comment]
Not enough detail to say anything. I do not advise using magic launcher for anything in 1.6, because it has a tendency to screw things up a large amount unless you know exactly what to do. It is much easier to use the Forge installer and the profile that creates in the standard launcher.
