### ISSUE TITLE
Add item tree support for enchanted items.

### ISSUE THREAD

**Issue by Kobata** [Inventory-Tweaks/inventory-tweaks#8]
Allow sorting specific enchantments on items separately from other versions of the item.

**Comment by sehrgut** [comment]
I'd be incredibly happy with this! I've had to manually resort my book chests a couple times when I've accidentally middle-clicked them.

**Comment by ChrisLane** [comment]
This would be fantastic to sort swords. Since Minecraft displays how much damage a sword can do on its tooltip, I think swords should be sorted for the highest damaging used first by default.
There are likely arguments against that default of course.

**Comment by Kobata** [comment]
Sword damage is an attribute, not an enchantment, and I haven't even come up with a way of letting people mess with enchantments that isn't too complex to expect anyone to easily figure out yet.

However, if you set sorting for a group (e.g., 'sword' instead of 'ironSword') they are preferred in the order they appear in the Item Tree file: currently (for swords) that goes iron->diamond->stone->gold->wood. The orders for these are from before I took over so I don't know why they're in that specific order.

**Comment by ChrisLane** [comment]
Ah well I had not noticed that the order was like that.
Seems like it might be useful to change that to have the diamond sword first for the default file for those who don't modify the files.

Thanks for responding, I've changed my sword ordering at least :)
