### ISSUE TITLE
No buttons, only R and some text.

### ISSUE THREAD

**Issue by kirillsemyonkin** [Inventory-Tweaks/inventory-tweaks#80]
There is no mods, only InvTweaks and SkinServer. I don't see any icons from mod, i can only sort by R and see some time text like "/u273r/u421b/"(Thats not real text was in game). It's in singleplayer. Sorry for bad English, i'm from Russia.

**Comment by Kobata** [comment]
You installed the mod incorrectly, and are not using the latest version which fixed the translation files.

**Comment by kirillsemyonkin** [comment]
I just leave latest version in /mods folder. Forge - latest. Installed forge with Installer. Using Magic Launcher. R working only if i not in inventory. Please help, i need to sort items in chests.

**Comment by kirillsemyonkin** [comment]
Sorry for wasting time, i really has an invalid version.
