### ISSUE TITLE
my game crashes when i open my inventory

### ISSUE THREAD

**Issue by ghost** [Inventory-Tweaks/inventory-tweaks#83]
here is the crash report

---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 7/31/13 11:31 AM
Description: Unexpected error

java.lang.IllegalAccessError: tried to access field net.minecraft.client.gui.GuiScreen.field_73887_h from class invtweaks.InvTweaksObfuscation
    at invtweaks.InvTweaksObfuscation.getControlList(InvTweaksObfuscation.java:177)
    at invtweaks.InvTweaks.handleGUILayout(InvTweaks.java:735)
    at invtweaks.InvTweaks.onTickInGUI(InvTweaks.java:139)
    at invtweaks.forge.ForgeClientTick.tickEnd(ForgeClientTick.java:43)
    at cpw.mods.fml.common.SingleIntervalHandler.tickEnd(SingleIntervalHandler.java:34)
    at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:141)
    at cpw.mods.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:367)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1956)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:898)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:826)
    at net.minecraft.client.main.Main.main(SourceFile:101)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:57)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:18)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at invtweaks.InvTweaksObfuscation.getControlList(InvTweaksObfuscation.java:177)
    at invtweaks.InvTweaks.handleGUILayout(InvTweaks.java:735)
    at invtweaks.InvTweaks.onTickInGUI(InvTweaks.java:139)
    at invtweaks.forge.ForgeClientTick.tickEnd(ForgeClientTick.java:43)
    at cpw.mods.fml.common.SingleIntervalHandler.tickEnd(SingleIntervalHandler.java:34)
    at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:141)
    at cpw.mods.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:367)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityClientPlayerMP['jose0009'/198, l='MpServer', x=2994.08, y=111.62, z=-1098.54]]
    Chunk stats: MultiplayerChunkCache: 441
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: World: (160,64,228), Chunk: (at 0,4,4 in 10,14; contains blocks 160,0,224 to 175,255,239), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 989414 game time, 104713 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
    Forced entities: 113 total; [EntityZombie['Zombie'/274, l='MpServer', x=2938.23, y=25.00, z=-1169.53], EntityZombie['Zombie'/273, l='MpServer', x=2960.00, y=27.00, z=-1174.50], EntityZombie['Zombie'/279, l='MpServer', x=2948.50, y=15.00, z=-1152.50], EntityCow['Cow'/258, l='MpServer', x=2928.75, y=65.00, z=-1102.63], EntityCreeper['Creeper'/259, l='MpServer', x=2932.09, y=43.00, z=-1059.88], EntityCow['Cow'/256, l='MpServer', x=2936.59, y=64.00, z=-1108.31], EntitySkeleton['Skeleton'/257, l='MpServer', x=2931.50, y=16.00, z=-1093.47], EntityZombie['Zombie'/260, l='MpServer', x=2928.50, y=38.00, z=-1044.50], EntitySheep['Sheep'/261, l='MpServer', x=2931.06, y=71.00, z=-1050.09], EntityBat['Bat'/306, l='MpServer', x=2965.00, y=31.13, z=-1169.03], EntitySkeleton['Skeleton'/309, l='MpServer', x=2972.88, y=29.00, z=-1158.56], EntityCow['Cow'/310, l='MpServer', x=2966.32, y=65.08, z=-1139.47], EntityWaypoint['unknown'/524, l='MpServer', x=2985.00, y=74.00, z=-1060.00], EntityWaypoint['unknown'/525, l='MpServer', x=3056.00, y=60.00, z=-1112.00], EntityWaypoint['unknown'/526, l='MpServer', x=3280.00, y=60.00, z=-744.00], EntityWaypoint['unknown'/527, l='MpServer', x=3048.00, y=15.00, z=-925.00], EntityWaypoint['unknown'/528, l='MpServer', x=2981.00, y=75.00, z=-1062.00], EntityCreeper['Creeper'/343, l='MpServer', x=3004.50, y=50.00, z=-1061.50], EntitySlime['Slime'/342, l='MpServer', x=2998.69, y=26.00, z=-1056.70], EntityCow['Cow'/341, l='MpServer', x=2993.53, y=85.00, z=-1076.13], EntityZombie['Zombie'/340, l='MpServer', x=2992.97, y=82.00, z=-1117.59], EntityCow['Cow'/339, l='MpServer', x=3002.38, y=77.00, z=-1129.47], EntityZombie['Zombie'/346, l='MpServer', x=2996.97, y=31.00, z=-1031.47], EntitySlime['Slime'/345, l='MpServer', x=2998.69, y=26.02, z=-1055.84], EntitySlime['Slime'/344, l='MpServer', x=2998.69, y=27.00, z=-1040.69], EntityChicken['Chicken'/327, l='MpServer', x=2978.53, y=64.00, z=-1178.56], EntityCreeper['Creeper'/332, l='MpServer', x=2992.00, y=7.00, z=-1133.56], EntityCow['Cow'/333, l='MpServer', x=2988.09, y=73.00, z=-1131.84], EntityCreeper['Creeper'/331, l='MpServer', x=2985.50, y=15.00, z=-1165.50], EntityItem['item.item.egg'/381, l='MpServer', x=3037.84, y=68.13, z=-1159.88], EntityChicken['Chicken'/380, l='MpServer', x=3032.34, y=69.00, z=-1163.59], EntityCow['Cow'/383, l='MpServer', x=3028.63, y=75.00, z=-1087.50], EntityZombie['Zombie'/377, l='MpServer', x=3034.50, y=44.00, z=-1178.50], EntityChicken['Chicken'/379, l='MpServer', x=3038.50, y=68.00, z=-1156.50], EntityChicken['Chicken'/378, l='MpServer', x=3034.44, y=67.00, z=-1172.53], EntityCow['Cow'/356, l='MpServer', x=3022.47, y=79.39, z=-1081.53], EntityZombie['Zombie'/357, l='MpServer', x=3018.50, y=26.00, z=-1071.50], EntityCow['Cow'/358, l='MpServer', x=3021.72, y=80.00, z=-1069.63], EntityZombie['Zombie'/359, l='MpServer', x=3019.06, y=21.00, z=-1047.50], EntityChicken['Chicken'/352, l='MpServer', x=3009.41, y=74.00, z=-1171.47], EntityChicken['Chicken'/353, l='MpServer', x=3016.47, y=70.00, z=-1165.44], EntityCow['Cow'/354, l='MpServer', x=3014.69, y=71.00, z=-1138.50], EntityCow['Cow'/355, l='MpServer', x=3016.06, y=72.00, z=-1128.84], EntityZombie['Zombie'/360, l='MpServer', x=3016.50, y=18.00, z=-1023.50], EntitySpider['Spider'/361, l='MpServer', x=3014.50, y=30.00, z=-1019.50], EntityCreeper['Creeper'/408, l='MpServer', x=3043.00, y=54.00, z=-1021.53], EntityCreeper['Creeper'/409, l='MpServer', x=3050.50, y=55.00, z=-1019.50], EntityBat['Bat'/683, l='MpServer', x=2937.09, y=37.29, z=-1064.71], EntityCow['Cow'/402, l='MpServer', x=3042.97, y=77.00, z=-1046.94], EntitySkeleton['Skeleton'/403, l='MpServer', x=3042.50, y=16.00, z=-1035.50], EntitySkeleton['Skeleton'/400, l='MpServer', x=3042.50, y=24.00, z=-1075.50], EntityCreeper['Creeper'/401, l='MpServer', x=3044.50, y=44.00, z=-1039.97], EntityCreeper['Creeper'/406, l='MpServer', x=3042.50, y=16.00, z=-1037.50], EntityCreeper['Creeper'/407, l='MpServer', x=3043.50, y=16.00, z=-1037.50], EntityBat['Bat'/404, l='MpServer', x=3037.34, y=16.26, z=-1034.31], EntitySpider['Spider'/405, l='MpServer', x=3045.50, y=18.00, z=-1026.50], EntityChicken['Chicken'/395, l='MpServer', x=3054.56, y=66.00, z=-1158.41], EntityChicken['Chicken'/394, l='MpServer', x=3042.44, y=67.00, z=-1161.41], EntitySkeleton['Skeleton'/399, l='MpServer', x=3040.50, y=24.00, z=-1074.50], EntityCow['Cow'/398, l='MpServer', x=3041.56, y=86.00, z=-1100.31], EntityChicken['Chicken'/397, l='MpServer', x=3055.59, y=71.00, z=-1126.44], EntityItem['item.item.egg'/396, l='MpServer', x=3043.59, y=66.13, z=-1159.13], EntityCow['Cow'/387, l='MpServer', x=3038.53, y=72.00, z=-1024.78], EntitySkeleton['Skeleton'/386, l='MpServer', x=3035.84, y=16.00, z=-1043.09], EntityBat['Bat'/385, l='MpServer', x=3030.16, y=23.85, z=-1062.75], EntityZombie['Zombie'/384, l='MpServer', x=3035.50, y=22.00, z=-1057.50], EntityCow['Cow'/388, l='MpServer', x=3038.79, y=73.00, z=-1030.53], EntitySkeleton['Skeleton'/440, l='MpServer', x=3070.28, y=37.00, z=-1130.66], EntitySkeleton['Skeleton'/441, l='MpServer', x=3066.50, y=38.00, z=-1109.50], EntityCow['Cow'/442, l='MpServer', x=3070.47, y=73.00, z=-1108.72], EntityCreeper['Creeper'/443, l='MpServer', x=3058.36, y=36.99, z=-1077.31], EntityZombie['Zombie'/444, l='MpServer', x=3058.50, y=38.00, z=-1083.50], EntityCreeper['Creeper'/445, l='MpServer', x=3066.25, y=12.00, z=-1060.03], EntityCreeper['Creeper'/447, l='MpServer', x=3052.69, y=12.00, z=-1059.50], EntityChicken['Chicken'/432, l='MpServer', x=3068.41, y=69.00, z=-1123.44], EntityItem['item.item.egg'/434, l='MpServer', x=3057.22, y=71.13, z=-1126.66], EntitySpider['Spider'/435, l='MpServer', x=3070.50, y=25.00, z=-1106.50], EntityCreeper['Creeper'/436, l='MpServer', x=3060.50, y=25.00, z=-1105.50], EntityCreeper['Creeper'/437, l='MpServer', x=3060.50, y=25.00, z=-1106.50], EntityZombie['Zombie'/438, l='MpServer', x=3070.55, y=37.00, z=-1131.83], EntityZombie['Zombie'/439, l='MpServer', x=3069.66, y=37.00, z=-1118.06], EntitySkeleton['Skeleton'/425, l='MpServer', x=3064.50, y=31.00, z=-1147.50], EntityZombie['Zombie'/427, l='MpServer', x=3062.50, y=37.00, z=-1151.50], EntityZombie['Zombie'/426, l='MpServer', x=3057.50, y=26.00, z=-1150.50], EntityBat['Bat'/429, l='MpServer', x=3068.53, y=26.48, z=-1133.69], EntityBat['Bat'/428, l='MpServer', x=3068.41, y=27.10, z=-1133.75], EntityBat['Bat'/431, l='MpServer', x=3061.25, y=39.10, z=-1132.25], EntitySkeleton['Skeleton'/430, l='MpServer', x=3070.85, y=37.00, z=-1132.69], EntitySkeleton['Skeleton'/421, l='MpServer', x=3057.50, y=38.00, z=-1156.50], EntityZombie['Zombie'/420, l='MpServer', x=3057.50, y=26.00, z=-1154.50], EntityChicken['Chicken'/423, l='MpServer', x=3068.44, y=65.00, z=-1161.56], EntityZombie['Zombie'/422, l='MpServer', x=3077.69, y=37.00, z=-1149.69], EntityBat['Bat'/474, l='MpServer', x=3074.50, y=34.17, z=-1101.53], EntityCow['Cow'/475, l='MpServer', x=3074.94, y=75.00, z=-1047.84], EntityChicken['Chicken'/468, l='MpServer', x=3072.47, y=67.17, z=-1122.86], EntityMinecartChest['entity.MinecartChest.name'/464, l='MpServer', x=3073.50, y=37.34, z=-1112.78], EntityClientPlayerMP['jose0009'/198, l='MpServer', x=2994.08, y=111.62, z=-1098.54], EntityChicken['Chicken'/458, l='MpServer', x=3076.88, y=64.00, z=-1166.59], EntityCow['Cow'/450, l='MpServer', x=3061.97, y=74.00, z=-1036.94], EntityCow['Cow'/449, l='MpServer', x=3061.47, y=72.00, z=-1031.16], EntityCow['Cow'/448, l='MpServer', x=3073.63, y=75.00, z=-1048.69], EntityZombie['Zombie'/715, l='MpServer', x=3063.50, y=33.00, z=-1143.50], EntityZombie['Zombie'/254, l='MpServer', x=2935.50, y=16.00, z=-1136.50], EntitySpider['Spider'/255, l='MpServer', x=2930.00, y=34.00, z=-1108.00], EntitySlime['Slime'/252, l='MpServer', x=2936.69, y=24.00, z=-1157.31], EntityCow['Cow'/253, l='MpServer', x=2932.94, y=79.00, z=-1162.03], EntitySheep['Sheep'/246, l='MpServer', x=2919.50, y=64.00, z=-1031.78], EntityZombie['Zombie'/244, l='MpServer', x=2926.72, y=20.00, z=-1092.31], EntityZombie['Zombie'/245, l='MpServer', x=2928.53, y=23.00, z=-1094.57], EntityBat['Bat'/242, l='MpServer', x=2918.44, y=23.53, z=-1127.88], EntitySkeleton['Skeleton'/243, l='MpServer', x=2921.88, y=15.00, z=-1100.44], EntitySheep['Sheep'/240, l='MpServer', x=2934.53, y=72.00, z=-1169.44], EntityZombie['Zombie'/241, l='MpServer', x=2922.50, y=25.00, z=-1137.50]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:440)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2298)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:851)
    at net.minecraft.client.main.Main.main(SourceFile:101)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:57)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:18)

-- System Details --
Details:
    Minecraft Version: 1.6.2
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.7.0_21, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 341752520 bytes (325 MB) / 828899328 bytes (790 MB) up to 2863333376 bytes (2730 MB)
    JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G
    AABB Pool Size: 18931 (1060136 bytes; 1 MB) allocated, 1423 (79688 bytes; 0 MB) used
    Suspicious classes: FML and Forge are installed
    IntCache: cache: 0, tcache: 0, allocated: 1, tallocated: 63
    FML: MCP v8.04 FML v6.2.19.789 Minecraft Forge 9.10.0.789 16 mods loaded, 16 mods active
    mcp{8.04} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    FML{6.2.19.789} [Forge Mod Loader](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Forge{9.10.0.789} [Minecraft Forge](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BetterSprinting{v10} [Better Sprinting Coremod](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    mod_bspkrsCore{v3.03(1.6.2)} [bspkrsCore]([1.6.2]bspkrsCorev3.03.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    mod_ArmorStatusHUD{v1.12(1.6.2)} [ArmorStatusHUD]([1.6.2]ArmorStatusHUDv1.12.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    mod_StatusEffectHUD{v1.14(1.6.2)} [StatusEffectHUD]([1.6.2]StatusEffectHUDv1.14.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    TreeCapitator{Forge 1.6.2.r01} [TreeCapitator]([1.6.2]TreeCapitator.Forge.1.6.2.r01.Uni.CoreMod.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Backpack{1.12.13} [Backpack](backpack-1.12.13-1.6.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BiblioCraft{1.3.4} [BiblioCraft](BiblioCraft[v1.3.4].zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    eplus{1.16.3} [Enchanting Plus](EnchantingPlus-1.16.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    InfernalMobs{1.3.3} [Infernal Mobs](InfernalMobs_1.6.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    inventorytweaks{1.55b} [Inventory Tweaks](InventoryTweaks-MC1.6.2-1.55b-b61.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    AS_Ruins{10.6} [Ruins Spawning System](Ruins_1.6.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    AS_UpdateCheck{1.1.0} [AtomicStryker Update Check Mod](UpdateCheckerMod_1.6.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    mod_ZanMinimap{0.9.4} [Zan's Minimap](ZansMinimap1.6.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Launched Version: 1.6.2-Forge9.10.0.789
    LWJGL: 2.9.0
    OpenGL: ATI Mobility Radeon HD 4650 GL version 2.1.8789, ATI Technologies Inc.
    Is Modded: Definitely; Client brand changed to 'fml,forge'
    Type: Client (map_client.txt)
    Resource Pack: Soartex_Fanver.zip
    Current Language: English (US)
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 1355 (75880 bytes; 0 MB) allocated, 222 (12432 bytes; 0 MB) used

**Comment by Kobata** [comment]
Mod incompatibility with something.

Maybe BetterSprinting, see if there's an update for that.
