### ISSUE TITLE
Mouse-pointer moves crazy when transfering whole inventory

### ISSUE THREAD

**Issue by WhatIsThisHere** [Inventory-Tweaks/inventory-tweaks#84]
When transfering the whole inventory, or everything of the same sort, the mose keeps jumping upwards, without any reason.

How to reproduce: 
1. fill you inventory
2. shift everything with space + left click
3. watch your mose pointer jump everytime.

**Comment by Kobata** [comment]
Cannot reproduce in single-player, on Windows.
