### ISSUE TITLE
Sorting with the three buttons in chests fails

### ISSUE THREAD

**Issue by WhatIsThisHere** [Inventory-Tweaks/inventory-tweaks#85]
If you try to sort weapons or tools with the three buttons on the right hand top, it will give you one of them into your inventory and one to your hand and leave the rest where they are.

How to reproduce:
1. Find a chest with more than 1 tool
2. try to sort them using the three buttons
3. get one of them into your hand
attached are 1st unsorted and 2nd sorted using the middle one.

![2013-08-02_08 40 54](https://f.cloud.github.com/assets/5140902/899369/978f8148-fb3e-11e2-8d44-fd23b389c37f.png)
![2013-08-02_08 41 03](https://f.cloud.github.com/assets/5140902/899368/978e65ec-fb3e-11e2-839f-96177cac5197.png)

**Comment by bendem** [comment]
Confirmed... It occurs sometimes...

**Comment by Kobata** [comment]
Duplicate #66 
See my response there, issues of this type while sorting are fundamentally not resolvable on the client-side alone.
