### ISSUE TITLE
Suggestion : Workaround for NoCheatPlus

### ISSUE THREAD

**Issue by Mundfre** [Inventory-Tweaks/inventory-tweaks#92]
HI, 

I love this mod and I can't leave without it... But i play on server :-( 

I think the code can be adapt to handle the actual way and a 'server way' wich work more slowly to be like a player. A new parameter 'Mode slow' can active the changes for this new way. 

In this way the modifications are : 

SORTING
- Elements are sort in memory to minimize the number of move. 
- Moves are done by swapping the item in position N with the item that should go in position N (if they are différents)
- If 'Mode slow' a wait is done between each moves
- This means that it could take some time to sort a full double chest, but i prefer seeing the computer working than doing the work with the mouse
- At slow speed a beep at the end of the operation could be nice
- At slow speed sort can be done only if the inventory or chest is open,and a test should be done before each move to stop process if inventory or chest is closed. (in this mode "R" working in background is no more possible)

TRANSFERTS (Ctrl + Shift clic, Space + Clic, ...)
- If 'Mode slow' moves are done with a wait between two moves and a test to verify if inventory or chest is open is done between 2 moves

HOW TO SWAP OBJECT
A way to handle the swap between two objects is to have two parameters working in this way
- Take object_O in slot_S
- Wait for "param_1" milliseconds
- Put object_O in slot_T, (thus take object_P if slot_T is not empty)
- If object_P wait for "param_1" milliseconds
- If object_P put it in slot_T
- Wait "param_2" milliseconds before newt swap

With the possibility to défine param_1 and param_2 the swap could be optimized depending of the server.
- param_1 should be short because there is an object pending on the cursor (between 50 and 250 milliseconds)
- param_2 should be longer to simulate player reflexion (between 100 and 500) milliseconds

I hope this can help.
Mundfre

PS : Sorry for my english. A lot of people say that my french is better :-)

**Comment by Kobata** [comment]
The sorting code is not interruptable, it will cause the client to freeze entirely if any attempt to slow it down is done without a major rewrite of how it works.
