### ISSUE TITLE
You need to tweak your manifest

### ISSUE THREAD

**Issue by cpw** [Inventory-Tweaks/inventory-tweaks#93]
Add in "FMLCorePluginContainsFMLMod: true" so that FML will reparse your coremod jar as a mod jar as well..

https://github.com/MinecraftForge/FML/commit/dec9a3924d361bc016cb7f6b3e95764158cf5ae1

**Comment by Kobata** [comment]
Thanks for the heads up on that, fixed.

**Comment by ProsperCraft** [comment]
Is there a new build I can download?

**Comment by Kobata** [comment]
Since I keep redirecting people here: This affects Forge versions 831 and above, so don't use those until an update to the mod is released.
