### ISSUE TITLE
[Crash] With Forge 9.10.0.835 crash on pressing /

### ISSUE THREAD

**Issue by ProsperCraft** [Inventory-Tweaks/inventory-tweaks#95]
When I first log in to a server and press / I get this crash.

java.lang.NullPointerException
at invtweaks.forge.InvTweaksMod.setTextboxModeStatic(InvTweaksMod.java:74)

http://paste.md-5.net/hukupuceko.coffee

**Comment by Kobata** [comment]
Duplicate #93
