### ISSUE TITLE
On-going bug when sorting on multiplayer.

### ISSUE THREAD

**Issue by xAceAngelx** [Inventory-Tweaks/inventory-tweaks#98]
Ever since I first used Inventory-tweaks, I noticed this bug where if I try to sort a chest with a few complex items I time out of the server. If there like dirt, some wood, and cobble it will sort fine. But if there are a lot of items in the chest and i middleclick to sort, it shows me that its been sorted, but then when i exit the chest, I can't re-open it because I am timing out. and if i wait a few seconds, i just get disconnected. is there a fix for this?

**Comment by Kobata** [comment]
Duplicate #66
