### ISSUE TITLE
java.lang.NullPointerException when i click "Create a New World"

### ISSUE THREAD

**Issue by ghost** [Inventory-Tweaks/inventory-tweaks#99]
I updated the Forge to version 9.10.0.840, and i got this problem:

---- Minecraft Crash Report ----
// Oh - I know what I did wrong!

Time: 20/08/13 12:27
Description: Updating screen events

java.lang.NullPointerException
    at invtweaks.forge.InvTweaksMod.setTextboxModeStatic(InvTweaksMod.java:74)
    at net.minecraft.client.gui.GuiTextField.func_73796_b(SourceFile:437)
    at net.minecraft.client.gui.GuiCreateWorld.func_73866_w_(GuiCreateWorld.java:123)
    at net.minecraft.client.gui.GuiScreen.func_73872_a(SourceFile:94)
    at net.minecraft.client.Minecraft.func_71373_a(Minecraft.java:720)
    at net.minecraft.client.gui.GuiSelectWorld.func_73875_a(SourceFile:124)
    at net.minecraft.client.gui.GuiScreen.func_73864_a(SourceFile:69)
    at net.minecraft.client.gui.GuiScreen.func_73867_d(SourceFile:128)
    at net.minecraft.client.gui.GuiScreen.func_73862_m(SourceFile:107)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1554)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:898)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:826)
    at net.minecraft.client.main.Main.main(SourceFile:101)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:57)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:18)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at invtweaks.forge.InvTweaksMod.setTextboxModeStatic(InvTweaksMod.java:74)
    at net.minecraft.client.gui.GuiTextField.func_73796_b(SourceFile:437)
    at net.minecraft.client.gui.GuiCreateWorld.func_73866_w_(GuiCreateWorld.java:123)
    at net.minecraft.client.gui.GuiScreen.func_73872_a(SourceFile:94)
    at net.minecraft.client.Minecraft.func_71373_a(Minecraft.java:720)
    at net.minecraft.client.gui.GuiSelectWorld.func_73875_a(SourceFile:124)
    at net.minecraft.client.gui.GuiScreen.func_73864_a(SourceFile:69)
    at net.minecraft.client.gui.GuiScreen.func_73867_d(SourceFile:128)
    at net.minecraft.client.gui.GuiScreen.func_73862_m(SourceFile:107)

-- Affected screen --
Details:
    Screen name: net.minecraft.client.gui.GuiCreateWorld
Stacktrace:
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1554)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:898)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:826)
    at net.minecraft.client.main.Main.main(SourceFile:101)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:57)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:18)

-- System Details --
Details:
    Minecraft Version: 1.6.2
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.7.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 185165424 bytes (176 MB) / 547880960 bytes (522 MB) up to 954466304 bytes (910 MB)
    JVM Flags: 1 total; -XX:MaxPermSize=1000M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Suspicious classes: FML and Forge are installed
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v8.04 FML v6.2.54.840 Minecraft Forge 9.10.0.840 83 mods loaded, 83 mods active
    mcp{8.04} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    FML{6.2.54.840} [Forge Mod Loader](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Forge{9.10.0.840} [Minecraft Forge](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    CodeChickenCore{0.9.0.3} [CodeChicken Core](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ImmibisMicroblocks{56.0.4} [Immibis's Microblocks](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Micdoodlecore{} [Micdoodle8 Core](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    NotEnoughItems{1.6.1.2} [Not Enough Items](NotEnoughItems 1.6.1.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    PlayerAPI{1.1} [Player API](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    mod_bspkrsCore{v3.03(1.6.2)} [bspkrsCore](bspkrs Core 3.03.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    IC2{1.118.31-experimental} [IndustrialCraft 2](Industrialcraft 2 1.118.31 Experimental.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ImmibisCore{56.0.3} [Immibis Core](Immibis Core 56.0.3 1.6.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    AdvancedMachines{56.0.0} [Advanced Machines](Advanced Machines 56.0.0 1.6.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    AdvancedRepulsionSystems{56.0.0} [Advanced Repulsion Systems](Advanced Repulsion Systems 56.0.0 1.6.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    mod_AnimalBikes{1.0} [mod_AnimalBikes](AnimalBikes 1.6.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    iChunUtil{2.0.0} [iChunUtil](iChun Util 2.0.0 1.6.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Grinder{2.0.0} [Grinder](Attachable Grinder 2.0.0 1.6.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Backpack{1.12.15} [Backpack](Backpack 1.12.15 1.6.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    BattleTowers{1.3.6} [Battle Towers](BattleTowers_1.6.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    BuildCraft|Core{4.0.1} [BuildCraft](Buildcraft A 4.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    BuildCraft|Builders{4.0.1} [BC Builders](Buildcraft A 4.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    BuildCraft|Energy{4.0.1} [BC Energy](Buildcraft A 4.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    BuildCraft|Factory{4.0.1} [BC Factory](Buildcraft A 4.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    BuildCraft|Transport{4.0.1} [BC Transport](Buildcraft A 4.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    BuildCraft|Silicon{4.0.1} [BC Silicon](Buildcraft A 4.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ChestTransporter{1.1.7} [Chest Transporter](ChestTransporter 1.1.7 Universal 1.6.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ChickenChunks{1.3.3.1} [ChickenChunks](Chicken Chunks 1.3.3.1 1.6.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ComputerCraft{1.56} [ComputerCraft](ComputerCraft 1.56.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    CCTurtle{1.56} [ComputerCraft Turtles](ComputerCraft 1.56.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    CrossbowMod2{a0.1.5} [Crossbow Mod 2](Crossbow Mod 2 a0.1.5.21 1.6.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    mod_CrystalWing{ML 1.6.2.r03} [CrystalWing](Crystal Wing ModLoader r03 1.6.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    CustomStuff2Core{0.10.6b} [Custom Stuff 2 Core](CustomStuff 2.0.10.6b Universal 1.6.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    DimensionalAnchors{56.0.1} [Dimensional Anchors](Dimensional Anchor 56.0.1 1.6.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    EnderStorage{1.4.3.3} [EnderStorage](EnderStorage 1.4.3.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ExtrabiomesXL{3.14.1} [ExtrabiomesXL](ExtrabiomesXL Universal 3.14.1 1.6.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    FinderCompass{1.6.2B} [Finder Compass](FinderCompass_1.6.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    FloatingRuins{Forge 1.6.2.r02} [FloatingRuins](Floating Ruins Forge r02 Universal 1.6.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Forestry{2.3.0.0} [Forestry for Minecraft](Forestry A 2.3.0.0 1.6.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ForgeMultipart{1.0.0.137} [Forge Multipart](ForgeMultipart-universal-1.6.2-1.0.0.137.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    McMultipart{1.0.0.137} [Minecraft Multipart Plugin](ForgeMultipart-universal-1.6.2-1.0.0.137.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    GalacticraftCore{0.1.39} [Galacticraft Core](Galacticraft a0.1.39.566 1.6.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    GraviGun{2.0.0} [GraviGun](Gravity Gun 2.0.0 1.6.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Hats{2.0.0} [Hats](Hats 2.0.0 1.6.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ImmibisPeripherals{56.0.1} [Immibis's Peripherals](Immibis Peripherals 56.0.1 1.6.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    InfernalMobs{1.3.5} [Infernal Mobs](Infernal Mobs 1.6.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    InfiniTubes{56.0.1} [InfiniTubes](Infini Tubes 56.0.1 1.6.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    mod_IngameInfo{ML 1.6.2.r02} [IngameInfo](Ingame Info ModLoader r02 1.6.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    AS_Kenshiro{1.1.6} [Kenshiro Mod](KenshiroMod_1.6.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    LiquidXP{56.0.2} [Liquid XP](Liquid XP 56.0.2 1.6.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    AS_Minions{1.7.0} [Minions](Minions_1.6.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MoreFurnaces{1.3.5} [More Furnaces](MoreFurnaces 1.3.5 Universal 1.6.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MultiPageChest{1.2.4b} [Multi Page Chest](MultiPageChest 1.2.4b Universal 1.6.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    PaintersFlowerPot{v1.58} [Painter's Flower Pot](Painter's Flower Pot 1.58 1.6.2+.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ClaySpawn{1.5} [Pam's Clay Spawn](Pam's Clay Spawn 1.6.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    pamdesertcraft{1.0} [Pam's DesertCraft](Pam's DesertCraft 1.01 1.6.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    pamextendedglass{1.0} [Pam's Extended Glass](Pam's Extended Glass 1.6.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    GetAllTheSeeds{1.6} [Pam's Get all the Seeds!](Pam's Get all the Seeds 1.6.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    pamharvestcraft{1.0} [Pam's HarvestCraft Base](Pam's HarvestCraft 1.010 1.6.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MushroomSpawn{1.3} [Pam's Huge Mushroom Spawn](Pam's Huge Mushroom Spawn 1.6.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MelonSpawn{1.5} [Pam's Melon Spawn](Pam's Melon Spawn 1.6.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    pammobdropcrops{1.0} [Pam's Mob Drop Crops](Pam's Mob Drop Crops 1.02 1.6.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    SimpleRecipes{1.9} [Pam's Simple Recipes](Pam's Simple Recipes 1.6.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    pamtemperateplants{1.0} [Pam's TemperatePlants](Pam's Temperate Plants 1.6.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    pamweeeflowers{1.1} [Pam's Weee! Flowers](Pam's Weee Flowers 1.04 1.6.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    PetBat{1.2.2} [Pet Bat](Pet Bat 1.6.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    PortalGun{2.0.0} [PortalGun](Portal Gun 2.0.0 1.6.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    RedLogic{56.0.3} [RedLogic](Red Logic 56.0.3 1.6.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    mod_ReiMinimap{v3.4_01 [1.6.2]} [mod_ReiMinimap](Rei's Minimap 3.4_01 1.6.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    RopesPlus{1.4.4} [Ropes+](Rope Plus 1.6.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    AS_Ruins{10.6} [Ruins Spawning System](Ruins_1.6.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Slender{2.0.0} [Slender](Slender 2.0.0 1.6.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    mod_SmartMoving{14.2} [Smart Moving](Smart Moving Universal for ModLoader or Minecraft Forge or MCPC+.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    mod_SmartRender{1.1} [Smart Render](Smart Moving Universal for ModLoader or Minecraft Forge or MCPC+.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    mod_StartingInventory{ML 1.6.2.r01} [StartingInventory](Starting Inventory ModLoader r01 1.6.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Torched{2.0.0} [Torched](Torched 2.0.0 1.6.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    TrailMix{2.0.0} [TrailMix](Trail Mix 2.0.0 1.6.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Translocator{1.1.0.7} [Translocator](Translocator 1.1.0.7 1.6.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Tubestuff{56.0.1} [Tubestuff](Tube Stuff 56.0.1 1.6.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    AS_UpdateCheck{1.1.0} [AtomicStryker Update Check Mod](UpdateCheckerMod_1.6.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    weaponmod{1.6.2 v1.13.5} [Balkon's WeaponMod](WeaponMod 1.13 1.6.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    WR-CBE|Core{1.4.0.4} [WR-CBE Core](WR CBE 1.4.0.4 1.6.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    WR-CBE|Addons{1.4.0.4} [WR-CBE Addons](WR CBE 1.4.0.4 1.6.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    WR-CBE|Logic{1.4.0.4} [WR-CBE Logic](WR CBE 1.4.0.4 1.6.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ForgeMicroblock{1.0.0.137} [Forge Microblocks](ForgeMultipart-universal-1.6.2-1.0.0.137.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Launched Version: 1.6.2 - Forge 9.10.0.840
    LWJGL: 2.9.0
    OpenGL: GeForce GT 630/PCIe/SSE2 GL version 4.3.0, NVIDIA Corporation
    Is Modded: Definitely; Client brand changed to 'fml,forge'
    Type: Client (map_client.txt)
    Resource Pack: Default
    Current Language: English (US)
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: ~~ERROR~~ NullPointerException: null

**Comment by Kobata** [comment]
Duplicate #93
